### ISSUE TITLE
Parsing test262

### ISSUE THREAD

**Issue by syg** [cherow/cherow#10]
I'd like to see what % of test262 tests Cherow is able to parse correctly (whether intended to be parseable or not). It would certainly suss out issues such as the lexical scoping bug just reported.

**Comment by KFlash** [comment]
Hi. There are many factors here. First off I think you refer to `test262-parser tests`? Or the `test262/language` tests?  The first mentioned. `Cherow` should actually parse them all. There are - as far as I know - no such tests as in the reported lexical issue.  I can also add that the `test262-parser` tests is far from complete. You can find some of them in the `test262 folder`.

For the `test262-language` tests it should also pass them all. Once again. This tests mostly focus on early errors, and normal fail / pass. 

Mostly the issues that have been or will be reported is the price I as a developer have to pay as the result of Cherows performance. I'm not going into details on that, but I will try to come up with something that can show how many % of this tests Cherow supports.

**Comment by syg** [comment]
Sorry, I was being vague. By test262 I meant:

- Parser tests should pass.
- Runtime tests that aren't testing early errors should parse in Cherow without error, as a blanket litmus test.

**Comment by KFlash** [comment]
Ok. I'm adding this to my TODO list and will fix this together with the refactoring of the tests that I'm soon going todo. Should we close this one?

**Comment by KFlash** [comment]
Closing this for now.

**Comment by KFlash** [comment]
Test262 parser tests are located [here](https://github.com/cherow/cherow/tree/master/test/specs/test262)
