### ISSUE TITLE
Incorrect comments results by cherow@1.6.6

### ISSUE THREAD

**Issue by achun** [cherow/cherow#101]
See https://jsfiddle.net/achun/6so0cdg9/

**Code**

```js
const code = `
function square(n) {
  return n * n;
}
// comment
`;

const ast = cherow.parse(code, {
    loc: true,
    ranges: true,
    module: true,
    comments: true,
  }
);
JSON.stringify(ast.comments, null, '  ');
```

**Expected behavior:**

```js
[
  {
    "type": "SingleLine",
    "value": " comment",
    "start": 40,
    "end": 51,
    "loc": {
      "start": {
        "line": 5,
        "column": 0
      },
      "end": {
        "line": 5,
        "column": 10
      }
    }
  }
]
```

**Actual behavior:**

```js
[
  {
    "type": "SingleLine",
    "value": " comment\n",
    "start": 40,
    "end": 51,
    "loc": {
      "start": {
        "line": 5,
        "column": 0
      },
      "end": {
        "line": 4,
        "column": 0
      }
    }
  }
]
```

**Comment by KFlash** [comment]
Hi. You got the LT at the end because you have added it, and the comment are sliced after the index position. However I'm in a rush, but I corrected the end column index. I think it was wrong.

@fkleuver I ran into a workflow issue again - uglify isn't a function. So can't build. Do you have time to bundle the files and push to NPM?

**Comment by achun** [comment]
Hi,
LT???  It Is means LF?

As far as I know, other parsers excluding LF.
Because there may be different line ending: LF / CRLF / CR.

It's better to be consistent or add an option like 'trimLineEnding: true'

**Comment by achun** [comment]
If efficiency is taken into account, cherow will still save the line ending, please keep this behavior, do not change.

**Comment by KFlash** [comment]
I use `LT` as a common term for LineTerminator..

```js
LineTerminator::
<LF> <CR> <LS> <PS>
LineTerminatorSequence::
<LF> <CR> [lookahead ≠ <LF> ]
<LS> <PS> <CR> <LF>
```
I will keep this behavior.

Still in the airport, but need to catch a flight now. Let see if this will be pushed soon.

**Comment by KFlash** [comment]
Closing this now. Checkout NPM

**Comment by KFlash** [comment]
take a look at [this](https://github.com/cherow/cherow/blob/master/packages/cherow/src/lexer/comments.ts#L151)

**Comment by achun** [comment]
![image](https://user-images.githubusercontent.com/489285/41189239-26d59b7e-6bfd-11e8-842e-7f5b783d1375.png)

**Comment by KFlash** [comment]
Sorry about this, but I have a hard time figure this out. Look at [Esprima demo](http://esprima.org/demo/parse.html?code=%20%20%20%20%20%20%20%20%20%20%20%20function%20square(n)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%20n%20*%20n%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20comment%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20)

Nothing is 0 there either.

Then I tried this locale and counted manually

```js
            function square(n) {
              return n * n;
            }
            // comment

            ```
If I count from the top I end up with number 4. If I count from left to right I end up with number 12.
