### ISSUE TITLE
support lexical analysis

### ISSUE THREAD

**Issue by Aladdin-ADD** [cherow/cherow#102]

**Comment by KFlash** [comment]
Something like [this](https://github.com/cherow/cherow/blob/recovery/packages/cherow/src/lexer/common.ts#L120) ?

**Comment by Aladdin-ADD** [comment]
more like esprima/espree: https://github.com/Aladdin-ADD/espree/blob/cherow/espree.js#L340

refs: https://github.com/cherow/cherow/issues/96#issuecomment-395169567

**Comment by KFlash** [comment]
It will land in v. 2.0. The API isn't settled yet. Could you contact me on gitter?

**Comment by Aladdin-ADD** [comment]
sorry, non-English speaker, so I'm asking @g-plane to see if there is something we can work together. 😂

**Comment by g-plane** [comment]
@Aladdin-ADD I have replied you on gitter.

**Comment by KFlash** [comment]
Work in progress as you know. `onToken` option have been added.

**Comment by KFlash** [comment]
Closing this. See #173
