### ISSUE TITLE
推荐一种静态类型描述语法, 希望能像 flow 那样被支持

### ISSUE THREAD

**Issue by achun** [cherow/cherow#106]
因为我的英文不够好, 为了避免写英文造成歧义, 所以这里用中文写.

我很偶然的发现 ES 中的 void 运算可以被利用, 用来表示静态类型, 使得 ES 具有静态类型表达能力.
就像 flow 所完成的工作那样, 不同的是, void 表达式是合法的 ES  原生语法, 而且它是无副作用的.
我把它称作 void 类型表达式 --- `void typeExpression`.

实例: 常规的求和函数

```js
function sum(x, y) {
   return x + y;
}
```

周知, 它没有类型约束能力, 如果想要做的类型检查, 原生的方法是在函数主体中先加入 `typeof x === 'number'` 这样的判断.

该函数的另一个版本是加上默认值: 显然这依然不是静态类型描述

```js
function sum(x = 0, y = 0) {
   return x + y;
}
``` 

void typeExpression 的写法:

```js
function sum(x = void !0, y = void !0) {
   void !0;
   return x + y;
}
``` 

三个 `void !0`, 它的语义是:

1. x, y, 和返回值的类型都是 integer , 0 表示 integer
1. 而且必须有输入参数 x, y, 有返回值, 修饰符 `!` 强调了这一点

该示例中只描述了类型, 没有描述默认值, void typeExpressioin 的好处就是可以和默认值无冲突的连接起来

```js
let one = void 0||1;
```

显然, `one === 1` , 默认值生效了, 而且也明确了类型.

更详细的文档在 https://gitlab.com/achun/proposal-static-type-constraints-features

我在 cherow 发贴的目的:

我希望这种方法能吸引到开发者, 得到认同, 更希望 cherow 能出现一个支持 void 类型表达式的插件, 就像 flow 插件一样.
毕竟该表达式虽然合法, 但不是 ECMAScript 标准, 不能直接实现静态类型检查.

要实现静态类型检查有很多工作要做, 最基本的就是在 AST 中生成 typeAnnotation 节点, 就像 flow 插件那样. 这只是第一步, 这属于 cherow 这样的解析器的工作范围, 后续的类型检查将是另外的项目.

我想听到更多的意见, 任何的.

**Comment by KFlash** [comment]
你想让我说什么？ 我理解你。Sorry. My chinese is not so good. But try at least to write in english. Not everyone here that have lived in a chinese speaking country or  speak chinese fluently.

我希望你明白。在gitter上讨论这个问题。

**Comment by achun** [comment]
好的
