### ISSUE TITLE
test failed on windows

### ISSUE THREAD

**Issue by Aladdin-ADD** [cherow/cherow#108]
cherow: 2.0 (400d4b5ad97327c544a288580250396d5f1426f)
node: v10.1.0
npm: 6.1.0

![image](https://user-images.githubusercontent.com/13050025/41199485-8944889c-6cc5-11e8-801f-7e5d5a877913.png)

it passed on my MacOS, not sure why.

**Comment by KFlash** [comment]
@fkleuver Any ideas?

**Comment by fkleuver** [comment]
@Aladdin-ADD What's the exact workflow you're using? The "supported" way is via yarn and with the 8.x LTS release of nodejs. You'll also want to `yarn global add lerna` or `npm i -g lerna` to have the latest version globally available.

After cloning:
- In project root: `yarn install`
- Still in project root: `lerna bootstrap`

Then to run any of the scripts, you have some options
1) Go to `packages/cherow`
  - `yarn test` or `npm run test`
2) Stay in the project root
  - `lerna run test`

This should work for every OS.

**Comment by g-plane** [comment]
Try `lerna run test --scope=cherow` again?

**Comment by fkleuver** [comment]
That should work too. Actually it's a bit quicker as well because the console output is batched.

**Comment by Aladdin-ADD** [comment]
I'm going to close it. it was fixed when updated to the newest code, there might be something wrong in the commit.
