### ISSUE TITLE
Macrobenchmarks

### ISSUE THREAD

**Issue by rattrayalex** [cherow/cherow#11]
The microbenchmarks are unlikely to be representative of a typical workload (namely, parsing a 1~100kb file of code).

Eg; parse all code in a variety of open-source projects with a variety of coding styles, such as `lodash`, `react`, `jquery`, `backbone`,  etc.

You may wish to include such benchmarks in your test suite so that contributors do not introduce performance regressions.

**Comment by KFlash** [comment]
I'm aware of this. And stated in the benchmark that this also varies from computer to computer. Myself are parsing around 40 different libraries before I push something to this repo to avoid regression, plus another test suite that runs 120 micro benchmarks.

My issue here is that my benchmark solution is a huge hack and nothing I can publish online, but will try to find a solution for this issue in the near future.

**Comment by KFlash** [comment]
I added this to my TODO #3 so closing this now.

**Comment by twiss** [comment]
I added Cherow to [Esprima's comparison benchmark](http://esprima.org/test/compare.html), I'll send them a PR soon.
