### ISSUE TITLE
only allow squash commits

### ISSUE THREAD

**Issue by Aladdin-ADD** [cherow/cherow#115]
refs: https://blog.github.com/2016-04-01-squash-your-commits/

**Comment by g-plane** [comment]
I agree. This keeps git log clean.

**Comment by fkleuver** [comment]
@Aladdin-ADD Do you have any ideas for automating this? I was thinking about incorporating `standard-version` into cherow but on the same token it might be better to make a custom build script by hand. This gives some more control over things. I don't like how the whole `nps` script I put together has played out so far. One level of indirection too many if you ask me.

**Comment by Aladdin-ADD** [comment]
I'm assuming you were asking something like [npm-run-all](https://github.com/mysticatea/npm-run-all).

as `squash`, it's in the repo settings, no much work. 😄 
![image](https://user-images.githubusercontent.com/13050025/41202807-f68a32f4-6d00-11e8-8a98-1c559e39b756.png)

**Comment by KFlash** [comment]
Closing. As this is fixed in the settings.
