### ISSUE TITLE
implement comment attachment

### ISSUE THREAD

**Issue by KFlash** [cherow/cherow#116]
See https://github.com/cherow/cherow/issues/64#issuecomment-396035407

Idea is to find an optimal and performant way to support what's illustrated in the 4th comment - counted from the bottom up. A `priorNode` now exist on the parser object as an start.

**Comment by KFlash** [comment]
@g-plane Any progress on this one?

**Comment by g-plane** [comment]
I'm busy these days so I may be inactive for this in several days.

**Comment by KFlash** [comment]
@Aladdin-ADD Want to implement this?

**Comment by KFlash** [comment]
Closing this. See #173
