### ISSUE TITLE
Optimization for tokenizing string literal.

### ISSUE THREAD

**Issue by KFlash** [cherow/cherow#117]
We need to optimize the tokenizer, with string literals and templates.
Do some refactors, replace `String.fromCharCode` with string slices.

**Comment by Aladdin-ADD** [comment]
代码在 2.0 分支上？

**Comment by g-plane** [comment]
@Aladdin-ADD Sure.

**Comment by KFlash** [comment]
I'm closing this as fixed.  It will land in my PR within a few days. 66 000 string literal tests will back up my words!
