### ISSUE TITLE
Improved performance

### ISSUE THREAD

**Issue by KFlash** [cherow/cherow#126]
The main goal for v.2.0 of the Cherow parser is to improve it's performance. 

Here is the most recent benchmark results. 

**Note** v.2.0 has not been optimized yet so it's performance is still horrible comparing to Acorn and Esprima

![perf](https://user-images.githubusercontent.com/31855118/41385454-5644a2ba-6fae-11e8-8230-186948071712.png)

**Comment by fkleuver** [comment]
Awesome job. And see, the new lookups weren't that bad an idea ;)

**Comment by KFlash** [comment]
Closing this now. We got a benchmark to handle this.
