### ISSUE TITLE
What do we do with the raw property?

### ISSUE THREAD

**Issue by KFlash** [cherow/cherow#129]
Cherow v. 1.6x offers raw property on the AST node through option. Esprima offers this by default. 
Because performance has top priority in 2.0, we must think through this.

Current solution could and probably will cause an deoptimization because the raw property are set after the AST node have been created, 

```js
const AST = {};
AST.raw = "foo";  // option is on
```
For 2.0, I may think the best solution to avoid a deopt is this

```js
const AST = { raw: undefined };
AST.raw = "foo";  // option is on
```

This will prevent any deopts, and we will not loose any performance because the extra `slice` is only done when the raw option is set to true.

Two other things to think about.

1) Directives. 
2) String literals

In ESTree, a directive must be a directive AST node, and this node has a raw property. So in this case when parsing string literals the raw property has to be set by default - same as being done in Esprima and Acorn. 

A last think to think about is raw identifiers. Also an option in `v1.6`. This will be solved the same way as for literal AST nodes.

Any thoughts? At least we can't continue creating any possible deopt during each parse.

**Comment by KFlash** [comment]
Both numeric literals and now identifier scanning have a pending TODO when it comes to raw property. Are we choosing the `{ raw: undefined }` solution?

**Comment by fkleuver** [comment]
What do other parsers do with the raw property?

**Comment by KFlash** [comment]
@fkleuver They are slicing from the start, and doesn't offer it as an option.

I'm closing this now. The "raw" are now set to undefined.
