### ISSUE TITLE
Too many duplicated workflow-related files

### ISSUE THREAD

**Issue by g-plane** [cherow/cherow#130]
Looking at each package in `packages` directory, there are too many duplicated workflow-related files in each package, such as some test-related files.

Also, every `packages.json` contains many unused devDependencies.
For example, we just need to install `typescript` and `mocha` even other similar packages once in the root `package.json`, but these dependencies were specify in each `package.json`, which is redundant.

Not necessary: If there are some shared testing-related utils or functions, I recommend to use 3rd-party assertion library, or even use Jest which provides full features out of the box.

/cc @fkleuver

**Comment by fkleuver** [comment]
Agree on the package.json, this could be cleaner. Thanks for looking into that.
We're 100% not going to use Jest though. Jest has a different purpose (like karma). Nice for tests that need a browser environment. For us it's only overhead and unneeded fluff.
We could add on a library like `chai` (and maybe `sinon` + `sinon-chai` if we need mocking) for the assertions. The tests can probably be cleaned up to become more succinct / easier to maintain. Some of them also have the wrong block depth.

Ultimately though, keep in mind that we're going to get around 100k tests at some point. Every couple of cpu cycles added by additional assertion abstractions will significantly increase the test run time.
And this is not a regular app we're testing, 99% of the tests need almost exactly same kinds of assertions. Writing our own specialized efficient function for that is probably better.

**Comment by g-plane** [comment]
I know. However, those shared test-related files can be merged.

**Comment by fkleuver** [comment]
Which shared test-related files? util.ts?

**Comment by g-plane** [comment]
https://github.com/cherow/cherow/blob/master/packages/cherow/test/test-utils.ts

**Comment by fkleuver** [comment]
What would you suggest? Put it in a separate package, put it in the root folder, or in a separate repository?

**Comment by g-plane** [comment]
Create a directory called `test` in root directory, IMHO.

**Comment by fkleuver** [comment]
Can do. Might be a good idea to also add a paths reference in the tsconfigs so we can just `import ... from 'test'` or something among those lines. Was also thinking of doing something similar for the rest. Get rid of those long relative paths.

**Comment by fkleuver** [comment]
Closing in favor of #133
