### ISSUE TITLE
Investigate why tests fail in CLi

### ISSUE THREAD

**Issue by KFlash** [cherow/cherow#132]
CircleCI pass all tests. Travis and Appveyor fails.
No big changes done the last 3 hours. At that time all of them passed.

Also clicking on travis badge take you nowhere.

And locally I run around 6k tests. Something in the CLI blocking the tests so only 4k tests run and coverage fails. Locale coveragr is 89%.

Cc/ @fkleuver

**Comment by g-plane** [comment]
There are no tests in CLI.

**Comment by KFlash** [comment]
@g-plane In your end? CircleCi runs 4140 tests just fine. 

I found out why only 4040 tests are running after checking CircleCI log. All tests in the `test/parser` folder are skipped! You see this if you try to investigate in CircleCi and compare.

**Comment by g-plane** [comment]
You can see [here](https://github.com/cherow/cherow/tree/master/packages/cherow-cli), no any tests.

**Comment by KFlash** [comment]
@g-plane I fixed some of this. My issue was that my computer love to cache everything I do so I can't see things in real time (*same if I buy a new computer*). I guess same as CircleCI does - it passed.

Can you try to figure out why the tests in the parser folder doesn't run?

I'm clocing this, feel free to open a new issue ticket for the non-running 1k tests.
