### ISSUE TITLE
Workflow improvements

### ISSUE THREAD

**Issue by fkleuver** [cherow/cherow#133]
Couple points I'm going to address:

- [x] Remove dependency on nps, change to more flexible/efficient/clean custom scripts
- [ ] Make a bootstrap script for quickly setting up a new package with required configs/deps
- [ ] Automate the release workflow (build + version bump + tag + push + publish)
- [x] Enforce conventional changelog on commit messages for automatic changelog generation
- [ ] Find other ways to protect @KFlash against himself and force him down the path of success :)
- [x] Add .mjs exports

**Comment by g-plane** [comment]
For the first point, I really agree.
For the third point, can we use something like `np`?

**Comment by fkleuver** [comment]
Looks promising. What concerns me is 1) the overhead and 2) locking ourselves in to someone else's workflow (what if we need one little thing that they don't support?).

Looking at the source code of that package, it's not a lot of code. We could create a fork just to be sure, or even just copy-paste into our utils (with a big fat acknowledgement of course)

**Comment by g-plane** [comment]
One more thing, will we add those built files in the `dist` directory to `.gitignore`?

**Comment by fkleuver** [comment]
I think it's better if we have a proper and easily accessible versioned history of our build artifacts together with the corresponding source code for those artifacts. But they should not be checked in arbitrarily. Those commits need to be isolated with release commits which should be automated via a script. Then they can more easily be filtered and don't need to be reviewed.

**Comment by fkleuver** [comment]
Ah right, I see why you're addressing this: https://github.com/cherow/cherow/commit/b2240a64ce267b96701de1ab874725209eb664cf

@KFlash only focuses on code, he doesn't remember stuff we talk about regarding build process :)

There are build tools that allow you to enforce these rules. I'll look into that so he gets a big red warning when he tries to commit build artifacts :)

**Comment by g-plane** [comment]
How to prevent it? Once you committed and pushed, nothing can be changed.

**Comment by KFlash** [comment]
Ups! 😮

**Comment by fkleuver** [comment]
A local hook that intercepts git commits and validates the commit against certain rules, then prevents the commit if those rules are broken :)

**Comment by g-plane** [comment]
I don't agree to be back to npm, because we use lerna and Yarn's workspaces.

**Comment by fkleuver** [comment]
@Aladdin-ADD 

- I'm thinking about `commit-lint` but anything that does the job is fine ultimately.
- Lint config can probably be better, but it can't be too restrictive or it will give @KFlash a headache. If you can find autofix for those formatting issues that would be great though.
- We already have a microbenchmark with node highres timestamps for fairly fine-grained tests, I'll put it in the repo soon-ish. Then you guys can play with it :) It needs some looking into to make it work with small individual parsing functions. Other than that small experiments with jsbench.ch is often still the way to go.
- Yeah @KFlash stop committing dist files. Bad you!
- npm 6 is actually a really good release, so that could be worth looking into. I've heard rumours of typescript coming with project system that solves a similar problem to lerna, so if that feature ever shows up then I'd say time for some big changes.

**Comment by g-plane** [comment]
However npm still doesn't contains some functions like Yarn's workspaces, which is that it will install the same packages many time into different directories.

**Comment by fkleuver** [comment]
Lerna can do that via `--hoist`, but I did say looking into, not necessarily switch :) it will also depend on how typescript project system is going to be

**Comment by Aladdin-ADD** [comment]
what do you think https://github.com/prettier/prettier?
we can do autofix in git precommit.

**Comment by g-plane** [comment]
@fkleuver Not the typescript. If we use npm, it will install packages into different `node_modules` directoires, which cause too much spaces cost.

**Comment by Aladdin-ADD** [comment]
is there some reasons to keep travis-ci and circle-ci? I believe one is enough.

**Comment by KFlash** [comment]
See Esprima, Babylon, Acorn? So don't remove!

**Comment by KFlash** [comment]
@fkleuver What's the progress on this improvements?

**Comment by KFlash** [comment]
I guess this is stall? Inactive for the last 8 days now, and no PR follows this issue or any signs of workflow improvements. This issue will be closed within a few days if no action taken.

cc / @fkleuver @Aladdin-ADD

**Comment by g-plane** [comment]
DO NOT close it for tracking.

**Comment by Aladdin-ADD** [comment]
another thoughts: consider switching to [microbundle](https://github.com/developit/microbundle), so we can remove some dev deps like `rollup`, `rollup-plugin-*`.

**Comment by fkleuver** [comment]
Rollup is fine.

**Comment by g-plane** [comment]
Microbundle uses Rollup internally, so microbundle is fine too.

**Comment by fkleuver** [comment]
> Microbundle uses Rollup internally, so microbundle is fine too.

->

> so we can remove some dev deps like rollup, rollup-plugin-*

By adding another dep?

**Comment by g-plane** [comment]
No, just microbundle.

**Comment by fkleuver** [comment]
Looks a lot like parcel. I don't buy into zero-configuration bundlers, it's a lie. It's just no *bundler-specific* configuration, which still means configuration, but less control.

**Comment by futagoza** [comment]
I just quickly looked through your Rollup configs, and unless you not only want to want to lose automatic version string replacement but also creating multiple outputs via one config, I'de advice against it.

What I would suggest is (and what I usually end up doing in monorepo's it seems), create a local private package (e.g. `tools/rollup`, adding `tools/*` to your `workspaces` field) which does all your bundling via Rollup's API, changing the output options based on flags, and optionally a config file if it exists. I can take a stab at this if you don't mind, and you can then decide 😄

**Comment by fkleuver** [comment]
Don't worry, I'm redoing the rollup config as well. In the process of doing everything that's called via nps from scratch :)
What I had in mind is a bit similar to what you're suggesting - a local script file that calls the rollup API programmatically directly.

**Comment by KFlash** [comment]
@fkleuver what's the state of the workflow? 4 days now and I should be back again

**Comment by fkleuver** [comment]
What are your short term needs with the workflow? You're mostly just interested in quick builds, quick tests and lots of green CI checkmarks right? Or do you want to start publishing asap as well?

**Comment by KFlash** [comment]
When I work I only need the watch task working and the tests. But seems
like people was waiting 2.0 so if publishing nightly builds could be done
too. Plus a REPL

**Comment by g-plane** [comment]
A question: do we need a REPL like AST explorer (https://astexplorer.net) ?

**Comment by KFlash** [comment]
I would need it in my work and cherow isn't on astexplorer. So sometimes I
need to see the last Cherow generate. Plus its OK to have a repl as demo
but also if people encounter a bug. They can use it to pinpoint the bugs
