### ISSUE TITLE
Investigate why CI not running all tests

### ISSUE THREAD

**Issue by KFlash** [cherow/cherow#134]
The tests in the `cherow/test/parser` folder doesn't run in the CI. Total amount of tests is 6k, but the CI only runs 4040 tests.

cc / @fkleuver

**Comment by KFlash** [comment]
@fkleuver @g-plane  Could you try to look into why the coverage also dropped to 37? I guess it's because I added more tests locale that isn't run in the CLI?

Here is how it look like for me (*same files as online*)

![coverage](https://user-images.githubusercontent.com/31855118/41468767-9ee10524-70dd-11e8-8631-d45a96fa14a4.png)

**Comment by g-plane** [comment]
TIP: You can use HTML coverage reporter to see what happened.

**Comment by KFlash** [comment]
All tests with same coverage result runs smooth on 7 of my computers, but not in the CLI

**Comment by KFlash** [comment]
@fkleuver Could you look into this issue? I'm starting on the parser code now and it's kind of needed that the parser tests run in the CLI

**Comment by KFlash** [comment]
Only 427 tests are running in the CLI now. Before it was at least 4040.

@g-plane @fkleuver How to solve this?  A quick look [here](https://github.com/cherow/cherow/tree/master/packages/cherow/test) and you see there exist a parser folder too with tests.

![circle](https://user-images.githubusercontent.com/31855118/41493643-e59ec4ac-713b-11e8-8cb9-72b87183a35d.png)

**Comment by KFlash** [comment]
There also exist around 3000k tests inside a [sub folder of the lexer folder](https://github.com/cherow/cherow/tree/master/packages/cherow/test/lexer/regex) that the CLI doesn't run either.
My guess is the 4040 tests ran before because the regex tests was not an sub folder of the lexer folder

**Comment by g-plane** [comment]
CI not CLI.

**Comment by KFlash** [comment]
Agree. @g-plane Could you fix this?

**Comment by Aladdin-ADD** [comment]
fixed by #139
