### ISSUE TITLE
Too many invalid imports

### ISSUE THREAD

**Issue by g-plane** [cherow/cherow#148]
![image](https://user-images.githubusercontent.com/17216317/41504881-40687ec6-722e-11e8-9d41-c48c354fa947.png)

@KFlash Did you forget to export something?

**Comment by fkleuver** [comment]
No that still needs to be fixed. Those are things that were made internal

**Comment by g-plane** [comment]
Export those members in `cherow`?

**Comment by fkleuver** [comment]
They're marked as `@internal` and we have `stripInternal` enabled. We shouldn't import them anymore.

**Comment by g-plane** [comment]
How can we do if we really need them?

**Comment by fkleuver** [comment]
As much as I hate to say this: copy-paste. Flags are just numbers, and `const enum`s are inlined anyway, so it doesn't lead to a larger library size if the same one is defined multiple times.

**Comment by g-plane** [comment]
It's better to export them.

**Comment by fkleuver** [comment]
@g-plane Actually you're right. I didn't notice that all internals were no longer exported.

@KFlash You realize that removing the exports from `cherow/cherow.ts` broke every other package?

**Comment by KFlash** [comment]
I noticed it now. But little to do with it now I guess

**Comment by KFlash** [comment]
@g-plane @fkleuver I fixed this in d46d96aaa42045f2e9f55a42251f4251752141a3
