### ISSUE TITLE
Circle ci never finish

### ISSUE THREAD

**Issue by KFlash** [cherow/cherow#149]
See latest PR. Circle ci never finish.

**Comment by KFlash** [comment]
@Aladdin-ADD I give you admin rights to fix this. I will remove the rights after 30 min.

**Comment by Aladdin-ADD** [comment]
I'm going to close it, please feel free to reopen if it still happenes.

**Comment by KFlash** [comment]
@Aladdin-ADD CircleCi didn't finish?
