### ISSUE TITLE
Cold start performance

### ISSUE THREAD

**Issue by twiss** [cherow/cherow#15]
So, I replaced Esprima with Cherow in my web app. Unfortunately, in my first unscientific testing, it wasn't faster. (Both around 100ms to parse a few files. When I added some more files it was a bit faster, around 180ms instead of 200ms.)

My first hypothesis was that it had something to do with my files, so I added Cherow and a test file to Esprima's comparison benchmark, but sure enough Cherow was [more than 2x faster](http://rawgit.com/twiss/esprima/cf473f1752337d1276856080cc00766f1bd69e14/test/compare.html) (and also much faster than in my testing.)

My second hypothesis was JIT warmup: the benchmark parses the same file many times, which gives the JIT compiler a chance to optimize the code, while I parse it only once. So I [did some work](https://github.com/twiss/esprima/commit/60ab89101b3d70f974ee64e82e7808cdf6d1de5e) to start a Web Worker for every benchmark cycle, in an attempt to make the code run in a fresh instance of the JIT compiler. (While still only measuring the parse time.) And sure enough, the parse times went up by around 2x, and closer together. [Cherow is still the fastest, but only by around 15%](http://rawgit.com/twiss/esprima/gh-pages/test/compare.html) (or less, for smaller files).

Anyway, my questions are, do you think this is a fair benchmark (or do you think warm JIT is more realistic for most use cases)? I plan to send Esprima a PR and ask them the same thing. And, do you think there's any room left to improve cold-JIT-performance?

**Comment by KFlash** [comment]
@twiss Interesting. It was actually my first time seeing Cherow being used like this :) And there are many factors here. The two most important one is that Cherow do a lot more "behind the scene" when it comes to validation than Esprima. E.g. scope tracker and some other stuff to catch early errors among other things. If I remove that kind of code I would be on the "same level" as Esprima. So for me it was interesting too see that even with all the "things behind the scene" you still got the performance you got.

The second is that you should try this on a couple more files. It take while for JIT to fully warm up. And in fact this was build for large scale scenarios in cases where you are instant parsing multiple, large files.  Both memory usage and the performance are important factors here.

It actually depends on the use case. What's important? For small files I don't think the performance is a huge issue. It's faster indeed, but in cases like that I think the correct output acc. TC-39 is the most important.

However. Thing can be changed to the better. I plan to optimize the code once more for cold start performance soon as I'm sure there aren't many *obvious* bugs left. I can't do it right away  because there exist some code to help me quickly track down issues. I also guess that code got a down side as you have pointed out.

**Comment by KFlash** [comment]
@twiss I did a little change to the performance. Can you check if that helped?

**Comment by twiss** [comment]
I ran the benchmark again and in Chrome, it's about the same, sorry. I'm not sure why. You can test the benchmark yourself [here](http://rawgit.com/twiss/esprima/gh-pages/test/compare.html) (it grabs the latest version from npm). It tests with locations on there but I also tested with them off locally.

By the way, [Chrome lazily parses functions](http://www.mattzeunert.com/2017/01/30/lazy-javascript-parsing-in-v8.html). So part of the measured time in my "new" benchmark is parsing Cherow. According to that post, you can force a function to be parsed at load time by wrapping it in parentheses. So, if you assume that when Cherow is loaded it will parse at least one file (won't always be the case but not an unreasonable assumption) you could do that for functions that will always be called.

**Comment by KFlash** [comment]
@twiss Anywhere we can chat about this?

**Comment by twiss** [comment]
Sure! You could try [Gitter](https://gitter.im), you can make a public room for the repository there pretty easily, and private rooms as well. Or shoot me an email (in profile).

**Comment by bd82** [comment]
> Anyway, my questions are, do you think this is a fair benchmark (or do you think warm JIT is more realistic for most use cases)? I plan to send Esprima a PR and ask them the same thing. And, do you think there's any room left to improve cold-JIT-performance?

Generally if you start a **whole new process** to parse **each single file** and in addition
the parsing of each file is normally counted in **miliseconds** it would be very inefficient...

From a human UI/UX perspective it would also not be noticeable if parsing took 10ms or 20ms.
And to put things in perspective on my 4th Gen I7 mobile CPU it takes Acorn 20ms to parse the lodash.js file (10k+ lines), So Cherow would be what? 10ms?  How many times do you parse files larger than 10k lines? 

The much more important scenario is running the benchmark multiple times
(which is exactly what benchmark.js does automatically). For example if you need to parse 
a whole project made up of hundreds or thousands of files then you would actually
(as a human) notice the difference in performance.

**Comment by twiss** [comment]
> Generally if you start a whole new process to parse each single file and in addition
the parsing of each file is normally counted in miliseconds it would be very inefficient...

Of course, in an application you would not do this. But I do it in the benchmark to simulate the case where you parse a file for the first time. And actually, parsing the same file over and over again is also not realistic, a real application will never do that. Branch prediction will make the parsing faster in the benchmark than in real life.

> From a human UI/UX perspective it would also not be noticeable if parsing took 10ms or 20ms.
And to put things in perspective on my 4th Gen I7 mobile CPU it takes Acorn 20ms to parse the lodash.js file (10k+ lines), So Cherow would be what? 10ms? How many times do you parse files larger than 10k lines?

To give an example, parsing jQuery.Mobile (once) on my laptop's i5 takes 180ms, and on my phone 540ms (like I said, I'm using Cherow in a web app so mobile performance is also important). Quite significant time (half a second) if you have to wait for it, for only one file. But, the (old) benchmark says it takes 80ms and 220ms respectively. That's a big difference, and in some cases, the first numbers are more important. And keep in mind, *even* if you parse a thousand files, you also have to wait for parsing the first file.

> The much more important scenario is running the benchmark multiple times
(which is exactly what benchmark.js does automatically). For example if you need to parse
a whole project made up of hundreds or thousands of files then you would actually
(as a human) notice the difference in performance.

I think the most important scenario is a mix: some cold performance, and some warm performance. But the ratio between cold and warm performance differs per use case, and it's useful to know both numbers.

**Comment by KFlash** [comment]
I'm closing this now. It's up and running.
