### ISSUE TITLE
build process broken

### ISSUE THREAD

**Issue by KFlash** [cherow/cherow#151]
Run `npm run build` inside  `packages/cherow`

```js
nps is executing `build.default` : nps build.before && nps build.all.default
nps is executing `build.before` : nps lint && nps build.clean
nps is executing `lint` : tslint --project configs/tsconfig-build.json
error TS5023: Unknown compiler option 'strict'.
error TS5014: Failed to parse file 'E:/cherow/configs/tsconfig.json': Unexpected token } in JSON at position 2479.
```

cc / @fkleuver

**Comment by Aladdin-ADD** [comment]
does reinstall deps solve it?
```bash
npm install --save-dev typescript@latest
```

**Comment by KFlash** [comment]
Nope. See L2049. It's a typo there. What other issues it is I don't know

**Comment by Aladdin-ADD** [comment]
however I didn't see the error in my local(master) (o|o) 
what branch are you working on? did you modified some configs?

**Comment by Aladdin-ADD** [comment]
there is a related commit: https://github.com/cherow/cherow/commit/90231fde864c978ca2faaa799f1276fe0e98a7ca

 you might need to reinstall all the deps.

**Comment by KFlash** [comment]
I'm on master branch and didn't modify anything

**Comment by fkleuver** [comment]
Can you try `lerna run build --scope cherow` from project root?

**Comment by KFlash** [comment]
On my way to hospital now, but from project root it worked. But not from cherow folder. Same files as online.

**Comment by KFlash** [comment]
The funny thing here is `npm run minify` works from cherow folder, but not `npm run build`

**Comment by fkleuver** [comment]
Well then just run it from the project root for now. [this commit](https://github.com/cherow/cherow/commit/d3def96ef4314176f932e5ea54341dbe440677e5) broke all the local scripts. That said, `test:watch` is the only one that you *need* to run locally anyway

**Comment by fkleuver** [comment]
I think this may be because you don't have the right version of tslint installed globally - it goes to your global version because it's not installed within the package. This is why the deps needed to stay @g-plane  :)
Should be fixed with https://github.com/cherow/cherow/commit/9f13383cfac9eb4644df47e10842ab5156c02ebb
