### ISSUE TITLE
remove numeric separator support

### ISSUE THREAD

**Issue by KFlash** [cherow/cherow#159]
Numeric separators have been "down graded" to stage 2, meaning we have to remove support for it both in the upcoming 2.0  and existing v. 1.6.8.

**Comment by KFlash** [comment]
@Aladdin-ADD Is this something you could take a look at?

**Comment by Aladdin-ADD** [comment]
to follow [semantic versioning](https://semver.org/), I don't think we can remove it in 1.x. 
we can remove it in 2.0(though it might stop users migrating from 1.x)

**Comment by KFlash** [comment]
If that's the case, just hide it under the `experimental flag / option` if you think it can be removed from v. 2.0.

**Comment by KFlash** [comment]
@Aladdin-ADD @g-plane I suggest that you two can [read this](https://github.com/tc39/proposal-numeric-separator#stage-3)

**Comment by g-plane** [comment]
Still in stage 3?

**Comment by KFlash** [comment]
It was stage 3, but because of potential conflict with a potential future feature it is now Stage 2. And Cherow only supports Stage 3

**Comment by KFlash** [comment]
@g-plane You can see it [here](https://github.com/tc39/proposals)

**Comment by g-plane** [comment]
So can we move to `experimental`?

**Comment by KFlash** [comment]
That was what I suggested earlier yes, if you scroll up. Can you or @Aladdin-ADD make a PR for it?

**Comment by Aladdin-ADD** [comment]
I can do it later. removing it in 2.0 might not be a bad idea -- we can always add it back when someday it reach stage-3.

**Comment by KFlash** [comment]
@Aladdin-ADD Sounds great, and removing it now helps simplifying things too. At least 3 methods can be merged into one.
