### ISSUE TITLE
Suggestion: Online Benchmark easily runnable in the browser.

### ISSUE THREAD

**Issue by bd82** [cherow/cherow#16]
I believe that something a user can easily run directly without
any need to clone and setup the project is much more convincing.

Esprima has this:
http://esprima.org/test/compare.html

I thought about migrating a benchmark page I was using for **generic** parsing libraries (Antlr/pegjs/...).
http://sap.github.io/chevrotain/performance/

Thoughts?

**Comment by KFlash** [comment]
I totally agree, but I haven't come up with a good solution yet. Another user asked for it yesterday too. Feel free to put up one if you can come up with a good solution.

**Comment by twiss** [comment]
We could also just copy their benchmark and add Cherow, if they're not interested in adding it on their domain. It's BSD licensed. They also have this: http://esprima.org/test/benchmarks.html, which we could adapt to Cherow.

**Comment by bd82** [comment]
> We could also just copy their benchmark and add Cherow

That may be a better idea as the esprima benchmark uses multiple sample inputs.

**Comment by KFlash** [comment]
@bd82 Should we just copy what @twiss  have made, and adopt it to Cherow after re-design? It kind of important to get it up and running. I guess people expect it

**Comment by bd82** [comment]
> should we just copy what @twiss have made ? 

You mean what he **linked?**

I think this benchmark page is better as it shows relative performance.
http://esprima.org/test/compare.html

I will hopefully find 10minutes to try cherow to that benchmark on esprima's webiste later today.
But adapting and adjusting may be a bigger problem as I am not a web developer
and I don't know how isolated the benchmark is from the rest of esprima webpage.

**Comment by KFlash** [comment]
[this one](http://rawgit.com/twiss/esprima/gh-pages/test/compare.html) I and the one you linked to

**Comment by KFlash** [comment]
See https://github.com/cherow/cherow/issues/15. First post

**Comment by twiss** [comment]
That page is pretty isolated, it shouldn't be hard to copy. If you want, I can finalize #15 by adding a separate button for cold performance and send a PR.

Another option is to just leave it in a fork, at cherow/esprima or twiss/esprima or wherever, and link to that.

**Comment by KFlash** [comment]
Hi. Would be nice if you could send a PR. What about adding it to `gh-pages` branch, and add a button or something there? Would be okay to get it running now when I optimizing for performance as you requested yesterday.

**Comment by KFlash** [comment]
@twiss @bd82 Try to remove the "Esprima" name. I'm not a huge fan.

**Comment by KFlash** [comment]
@twiss Any progress on this one?

**Comment by bd82** [comment]
See this:
https://cherow.github.io/cherow/performance/

* Automatically uses latest cherow/esprima/acorn from npm.
* We are missing version property on the cherow global object so nothing to display next to the name.
* I removed Tracur/Uglify from the benchmark as I've felt benchmarking against pure parsing libraries (direct competitors) is the more interesting scenario.
* Included the copyrights from the original source to maintain license compliance.

**Comment by KFlash** [comment]
Looks great. But what about different colors?

**Comment by KFlash** [comment]
I also thought maybe @twiss was working on something similar? Anyway. Could you try a little redesign?

**Comment by bd82** [comment]
> Looks great. But what about different colors?
> Anyway. Could you try a little redesign?

UX/UI is something I try to stay away from...
I rarely do more than copy/paste in this area and that is for the best 😄

**Comment by twiss** [comment]
Yup, I already added Cherow to that benchmark page in #15, but it's fine. Also @bd82, the Shift parser isn't working on your page.

**Comment by KFlash** [comment]
@bd82 @twiss Shift isn't working? Sounds bad. @twiss Design ideas? And should there be added cold performance?   And what about the other tests that shows only Esprima's benchmark result?

**Comment by bd82** [comment]
> Shift isn't working? 

shift-parser is not working due to mixed-content security policy error.
Basically it cannot be loaded from an HTTPS website (esprima.org is using http).
But the gh-pages uses https by default...

So I guess we will have to do:
1. **remove it**  
2. find another CDN where it is hosted with https support.
3. Bundle it and add to the source code.

I'm leaning towards removing it. as they do not seem to even include a bundled browser ready version in their npm package.

> Yup, I already added Cherow to that benchmark page in #15

Adding a row is not enough, also need to move the code to the cherow **Repo**
and remove no longer relevant UI elements, which is what I've done.

There is still work to do such as UI/UX/Design.
But that is outside my comfort area, @twiss maybe you are more proficient than I am in those areas?

**Comment by KFlash** [comment]
@bd82 Esprima are also loading this from gh-pages, so how can they get Shift working?
And can you add Babylon to that benchmark? Earlier a few persons asked for a fair Babylon comparison. 

I think @twiss got a few ideas.

**Comment by KFlash** [comment]
I'm closing this now. It's up and running.

**Comment by bd82** [comment]
Great I see @twiss found another cdn for shift-parser
https://wzrd.in/standalone/shift-parser@latest
