### ISSUE TITLE
Unreliable benchmark

### ISSUE THREAD

**Issue by KFlash** [cherow/cherow#171]
I have my doubts that we can trust the benchmark in the root folder. It's result  varies from +421% to -319% when the same tests are running over and over again.

In the current Cherow the flow for parsing a false keyword is this

`statement > assignment expr > condital > binary > unary > upate expr > lefthand expr > primary > member expr `

It's a lot of branching happend too during this flow that should slow things down.

In current re-write the flow goes like this:

`statement > primary > assignment` with zero to none validations except for a few super fast binary checks.

The result in the benchmark should reflect this, but the results jumps up and down like a pig.

Look at attached screenshot. I can't classify this as stable.

![hmm](https://user-images.githubusercontent.com/31855118/41909269-300ec36c-7979-11e8-833d-4a7a1256e845.png)

My opionion is that if you cut down on all path to reach the goal - in this case the false keyword - it should be way faster than this. And same thing for the update prefix expression. 

![zz](https://user-images.githubusercontent.com/31855118/41909603-06e31992-797a-11e8-8f33-38311415fd2b.png)

cc / @fkleuver

**Comment by KFlash** [comment]
As seen [in this code](https://github.com/cherow/cherow/blob/2.0-dev/packages/cherow/src/parser/expressions.ts#L80) I pushed you can see it jumps stright to primary expr and memory expr. 

But I doubt this has something to do with the benchmark itself.

**Comment by KFlash** [comment]
Here is another example- Jumping from -70 to +70. And it's only a simple call expression.

![call](https://user-images.githubusercontent.com/31855118/41914912-0960c914-7987-11e8-9360-4aca58ae794d.png)

@fkleuver Any ideas about this?

**Comment by KFlash** [comment]
With call + rest element we got better results, before the benchmark goes crazy again

![rest](https://user-images.githubusercontent.com/31855118/41915445-508b2b8a-7988-11e8-8db6-5b0c5a24ba68.png)

**Comment by KFlash** [comment]
I'm re-open this because I found out the issues has to be related to this benchmark alone.

See screenshot. Parsing out `({})` - empty obj literal - should be way faster than object literal with properties and values. But in the benchmark, a empty object literal is way slower.

![reopen](https://user-images.githubusercontent.com/31855118/41972088-3e0dee00-7a43-11e8-922a-57af61fb6454.png)

cc / @fkleuver

**Comment by KFlash** [comment]
I should add to the story that the Cherow 2.0 version on master branch have few validations (*something that should slow down the benchmark results*) My locale 2.0 version have all validations and still should be faster than master branch.

**Comment by KFlash** [comment]
This screenshot should prove it all. Locale 2.0 with all valiations is way faster than current master branch. It's correct. But look at the empty obj literal, and obj literal with simple identifier. The latter values jumps as a pig.

![warm](https://user-images.githubusercontent.com/31855118/41973112-a35de2bc-7a46-11e8-9aba-e7f2309a2061.png)

**Comment by fkleuver** [comment]
@KFlash We all know that no benchmark can ever be 100% reliable. The jumps have to do with V8 JIT. 

The best thing to do here is try various iteration counts, run them a few times and see if any of them runs somewhat stable. There is no magic bullet.

If you look at the actual numbers (the microseconds per parse) they stay roughly within the same range but there are variations. You can analyze this as much as you want - there is no better way to do it unfortunately. You need to use some common sense here.

Try other iteration and rotation counts. Use averages. It's no different from the browser benchmarks which are far more unreliable.

**Comment by KFlash** [comment]
Well. I now ran 668000 ops and empty object literal still slower. Even if I bail out early. Then tried again with empty array literal. Same thing. 

Anyway. Closing this again.
