### ISSUE TITLE
Unexpected token } in JSON

### ISSUE THREAD

**Issue by KFlash** [cherow/cherow#172]
Running this command `ts-node` in the root folder on the command line give this result:

```ts
TSError: Γ¿» Unable to compile TypeScript:
error TS5023: Unknown compiler option 'strict'.
error TS5014: Failed to parse file 'e:/cherow/configs/tsconfig.json': Unexpected token } in JSON at position 2479.
```

I looked at that file and noticed it doesn't contains 2000 lines.

cc /@fkleuver @Aladdin-ADD

**Comment by fkleuver** [comment]
Not 2000 lines, but it does contain 2000 characters ;)
Why are you trying to run `ts-node`?

**Comment by KFlash** [comment]
I converted the unicode compressor to a .ts file, and need to run it somehow to create the file. I changed how it worked locale based on your table lookup suggestion.

**Comment by fkleuver** [comment]
Can't you just compile it with `tsc ./path-to-file.ts` and then run the js?

**Comment by KFlash** [comment]
Well. I got issues that way too. I may convert it back to js. Else others has to install ts-node global and not everyone does that.

**Comment by KFlash** [comment]
@fkleuver This was working before, but something is weird with this workflow. Compiling as you suggested results in 

```js
scripts/generate-unicode.ts(5,21): error TS2307: Cannot find module 'fs'.
scripts/generate-unicode.ts(16,34): error TS2339: Property 'clz32' does not exist on type 'Math'.
scripts/generate-unicode.ts(121,23): error TS2697: An async function or method must return a 'Promise'. Make sure you have a declaration for 'Promise' or include 'ES2015' in your `--lib` option.
scripts/generate-unicode.ts(129,48): error TS2339: Property 'entries' does not exist on type 'string[]'.
scripts/generate-unicode.ts(139,28): error TS2495: Type 'Uint32Array' is not an array type or a string type.
scripts/generate-unicode.ts(159,5): error TS2304: Cannot find name 'require'.
scripts/generate-unicode.ts(159,22): error TS2304: Cannot find name 'module'.
scripts/generate-unicode.ts(161,21): error TS2304: Cannot find name 'require'.
scripts/generate-unicode.ts(162,22): error TS2304: Cannot find name 'require'.
scripts/generate-unicode.ts(163,16): error TS2304: Cannot find name 'require'.
scripts/generate-unicode.ts(168,22): error TS2304: Cannot find name '__dirname'.
scripts/generate-unicode.ts(172,34): error TS2304: Cannot find name 'Promise'.
scripts/generate-unicode.ts(180,28): error TS2304: Cannot find name 'process'.
```

**Comment by KFlash** [comment]
Closing this for two reasons 1) found a workaround 2) inactivity

**Comment by fkleuver** [comment]
You'd probably need to specify the tsconfig actually. Sounds like it doesn't have the standard `node` types which are normally specified in tsconfig. You generally can't just transform js to ts and expect it to transpile without errors, without looking at the tsconfig. I'll tackle this as well with the project system rework.
