### ISSUE TITLE
Use Prettier on partial files.

### ISSUE THREAD

**Issue by g-plane** [cherow/cherow#178]
The code in this repository is really very messy and it's hard to read. The source code of cherow is worth learning, but I have trouble to read it because of the mess of the code.

I know there are some files which shouldn't be formatted by Prettier, such as https://github.com/cherow/cherow/blob/master/packages/cherow/src/common.ts . Thus, we can run Prettier on partial files, instead of all the source code.

**We can use `.prettierignore`.**

Additionally, we can use husky to add a git `precommit` hook to do the work automatically.

@KFlash @fkleuver What do you think of this?

**Comment by fkleuver** [comment]
I would suggest you try this on a separate branch so we can easily clone it and have a look through it. Reviewing 10.000 replaced lines via Github is impossible.

While I do agree there are a lot of issues with white space and indentation, the alignment is generally fine (and better than what a formatter would provide). I've eluded numerous times that you probably can't automate this. It's simply a lot of code.

And our man @KFlash codes faster than he reads, so he never notices when he messes up the formatting ;)

Also are you sure the code is messy and not just complex? You can't "format" your way out of having to understand advanced parsing program flow. This code is not for the faint of heart.

**Comment by g-plane** [comment]
> And our man @KFlash codes faster than he reads, so he never notices when he messes up the formatting

This is why I suggest using git `precommit` hook which can be done automatically without any manual operations. **Remember to use `.prettierignore`.**

> Also are you sure the code is messy and not just complex?

Complexity is another hand, while the messy code is preventing me from reading and understanding the code.

**Comment by KFlash** [comment]
@g-plane Maybe follow up this issue with a separate branch as @fkleuver suggested?

**Comment by g-plane** [comment]
Well, I will work on a new branch.

**Comment by KFlash** [comment]
@g-plane created the new branch yet?

**Comment by g-plane** [comment]
Not yet. I'm working on other projects sorry, but I will try in next few days.
