### ISSUE TITLE
Don't create PR if you can't finish them

### ISSUE THREAD

**Issue by KFlash** [cherow/cherow#179]
To avoid too much noise on this repo, don't open PR's if you can't or will finish them. At the moment we have 5 open PR. One of this PR have been inactive for the last 15 days - https://github.com/cherow/cherow/pull/153

We also have two PR - closed now - for string literals and `ecmaVersion` option. This also make up some noise on the repo. 

Just be 100% sure before you open a PR. Also be sure that you get reviewers with knowledge enough to understand your way of thinking and the code flow.

https://github.com/cherow/cherow/pull/175 is my last PR. I will from now on push directly due to lack of reviewers and too keep the repo noise down.

cc / @fkleuver @g-plane @Aladdin-ADD

**Comment by g-plane** [comment]
I really don't recommend to push directly.

**Comment by KFlash** [comment]
I have pushed directly from start. As long as I'm only dealing with src folder there is no issue.

**Comment by g-plane** [comment]
I still recommend to open PR. Once you opened a PR and there are no any reviews **in several days**, you can merge by yourself.

**Comment by KFlash** [comment]
The issue is that somneone open PR and 1) never finish them or 2) never merge them
