### ISSUE TITLE
Add link to Gitter in Readme

### ISSUE THREAD

**Issue by twiss** [cherow/cherow#18]
@bd82 @KFlash asked me to ping you about the gitter room

https://gitter.im/cherow/cherow

**Comment by bd82** [comment]
This seems a round about way to go about it.

How about creating a pull request?
I just googled the question and it seems trivial
http://blog.gitter.im/2014/01/27/badgers/

**Comment by twiss** [comment]
I would, but I'm not at home right now ;) I can do it later.

**Comment by bd82** [comment]
I will have a look in the evening after work.

**Comment by bd82** [comment]
https://github.com/cherow/cherow/commit/dbcdf658f48133a0e8d352b183631261a44b94ae
