### ISSUE TITLE
make a eslint-config disallowing some time-consuming functions

### ISSUE THREAD

**Issue by Aladdin-ADD** [cherow/cherow#190]
based on http://incaseofstairs.com/six-speed/, we can figure out an eslint config. it can catch these usage while linting.
refs: https://www.npmjs.com/package/eslint-plugin-es

**Comment by KFlash** [comment]
@Aladdin-ADD do u plan to add a PR for this?

**Comment by Aladdin-ADD** [comment]
sorry to be late!
it's related to #133 , I'd like to see @fkleuver's thoughts on this.

**Comment by KFlash** [comment]
I see. I got some RL trouble to handle this day, but will be active within a few days

**Comment by KFlash** [comment]
Cc @fkleuver

**Comment by fkleuver** [comment]
@Aladdin-ADD what's the precise benefit of this?

**Comment by Aladdin-ADD** [comment]
I've found some ES6+ features are not allowed in the repo(for performance issues), when I made the first contributing. It would be nice that these unexpected usage can be caught by the linter.

just my 2 cents, please feel free to close the issue if you don't think it's worth adding. :)

**Comment by fkleuver** [comment]
@Aladdin-ADD Ah, I see. Sounds pretty interesting actually. Would we need to define custom rules by hand or is there some kind of external source that's kept up-to-date automatically that we can tap into? That would really help I think

**Comment by Aladdin-ADD** [comment]
there are some useful tools to achieve this:

+ [eslint-plugin-es](https://github.com/mysticatea/eslint-plugin-es) lets us disable each syntactic feature individually
+ [typescript-eslint-parser](https://github.com/eslint/typescript-eslint-parser) allow for ESLint to lint TypeScript source code
+ [eslint-plugin-typescript](https://github.com/bradzacher/eslint-plugin-typescript) TypeScript plugin for ESLint
[six-speed](http://incaseofstairs.com/six-speed/) perf test on ES6+ vs. ES5. not well-maintained though :(

seems the only thing we need to do is to figure out an eslint config.

**Comment by g-plane** [comment]
The eco-system of TSLint is not good as ESLint, so there is no plugin like `eslint-plugin-es` in TSLint. Using both can be OK.
