### ISSUE TITLE
cherow-eslint, cherow-ts tests failing

### ISSUE THREAD

**Issue by Aladdin-ADD** [cherow/cherow#193]
version: master

repro:
+ `cd packages/cherow-esint`
+ `npm run test`

some tests failed:(cherow-ts was similar)
<details>

> cherow-eslint@0.4.1 test /Users/weiran/repo/cherow/packages/cherow-eslint
> ava

  ✖ convert › convert comments type Error thrown in test
  ✖ parse › when strict mode error occurs 
  ✔ parse › throw an error when using the `y` regex flag
  ✔ parse › throw an error when using the `u` regex flag
  ✖ parse › reset lastToken on each parse Error thrown in test
  ✖ parse › should not mutate config Error thrown in test
  ✖ tokens › token divide Error thrown in test
  ✖ tokens › regular expression Error thrown in test
  ✖ tokens › JSX closing token Error thrown in test
  ✖ snapshot › normal code Error thrown in test
  ✖ snapshot › latest ES features Error thrown in test
  ✖ snapshot › JSX Error thrown in test
  ✖ snapshot › module mode Error thrown in test
  ✖ snapshot › comments Error thrown in test
  ✖ snapshot › regular expression Error thrown in test

  13 tests failed

  convert › convert comments type

  /Users/weiran/repo/cherow/packages/cherow-eslint/lib/index.js:16

   15: function convertComments(comments) {    
   16:   comments.forEach(comment => {         
   17:     if (comment.type === 'SingleLine') {

  Error thrown in test:

  TypeError {
    message: 'Cannot read property \'forEach\' of undefined',
  }

  convertComments (lib/index.js:16:12)
  Object.parse (lib/index.js:41:3)
  t (test/convert.js:5:22)

  parse › when strict mode error occurs

  /Users/weiran/repo/cherow/packages/cherow-eslint/test/parse.js:5

   4: test('when strict mode error occurs', t => {                              
   5:   const error = t.throws(                                                 
   6:     () => parser.parse('function fn(a, a) {\n}', { sourceType: 'module' }…

  Function threw unexpected exception:

  TypeError {
    message: 'Cannot read property \'forEach\' of undefined',
  }

  Expected instance of:

  Function SyntaxError {}

  parse › reset lastToken on each parse

  /Users/weiran/repo/cherow/packages/cherow-eslint/lib/index.js:16

   15: function convertComments(comments) {    
   16:   comments.forEach(comment => {         
   17:     if (comment.type === 'SingleLine') {

  Error thrown in test:

  TypeError {
    message: 'Cannot read property \'forEach\' of undefined',
  }

  convertComments (lib/index.js:16:12)
  Object.parse (lib/index.js:41:3)
  t (test/parse.js:23:10)

  parse › should not mutate config

  /Users/weiran/repo/cherow/packages/cherow-eslint/lib/index.js:16

   15: function convertComments(comments) {    
   16:   comments.forEach(comment => {         
   17:     if (comment.type === 'SingleLine') {

  Error thrown in test:

  TypeError {
    message: 'Cannot read property \'forEach\' of undefined',
  }

  convertComments (lib/index.js:16:12)
  Object.parse (lib/index.js:41:3)
  t (test/parse.js:32:10)

  tokens › token divide

  /Users/weiran/repo/cherow/packages/cherow-eslint/lib/index.js:16

   15: function convertComments(comments) {    
   16:   comments.forEach(comment => {         
   17:     if (comment.type === 'SingleLine') {

  Error thrown in test:

  TypeError {
    message: 'Cannot read property \'forEach\' of undefined',
  }

  convertComments (lib/index.js:16:12)
  Object.parse (lib/index.js:41:3)
  t (test/tokens.js:5:27)

  tokens › regular expression

  /Users/weiran/repo/cherow/packages/cherow-eslint/lib/index.js:16

   15: function convertComments(comments) {    
   16:   comments.forEach(comment => {         
   17:     if (comment.type === 'SingleLine') {

  Error thrown in test:

  TypeError {
    message: 'Cannot read property \'forEach\' of undefined',
  }

  convertComments (lib/index.js:16:12)
  Object.parse (lib/index.js:41:3)
  t (test/tokens.js:19:29)

  tokens › JSX closing token

  /Users/weiran/repo/cherow/packages/cherow/dist/umd/cherow.js:189

  Error thrown in test:

  SyntaxError {
    column: 4,
    description: 'Unexpected token end of source',
    index: 4,
    line: 1,
    message: 'Line 1, column 4: Unexpected token end of source',
  }

  constructError (/Users/weiran/repo/cherow/packages/cherow/dist/umd/cherow.js:189:23)
  recordErrors (/Users/weiran/repo/cherow/packages/cherow/dist/umd/cherow.js:199:23)
  parsePrimaryExpression (/Users/weiran/repo/cherow/packages/cherow/dist/umd/cherow.js:3790:17)
  parseMemberExpression (/Users/weiran/repo/cherow/packages/cherow/dist/umd/cherow.js:3617:22)
  parseNewOrMemberExpression (/Users/weiran/repo/cherow/packages/cherow/dist/umd/cherow.js:3554:16)
  parseLeftHandSideExpression (/Users/weiran/repo/cherow/packages/cherow/dist/umd/cherow.js:3470:20)
  parseUpdateExpression (/Users/weiran/repo/cherow/packages/cherow/dist/umd/cherow.js:3445:28)
  parseUnaryExpression (/Users/weiran/repo/cherow/packages/cherow/dist/umd/cherow.js:3421:16)
  parseBinaryExpression (/Users/weiran/repo/cherow/packages/cherow/dist/umd/cherow.js:3341:69)
  parseConditionalExpression (/Users/weiran/repo/cherow/packages/cherow/dist/umd/cherow.js:3310:22)

  snapshot › normal code

  /Users/weiran/repo/cherow/packages/cherow-eslint/lib/index.js:16

   15: function convertComments(comments) {    
   16:   comments.forEach(comment => {         
   17:     if (comment.type === 'SingleLine') {

  Error thrown in test:

  TypeError {
    message: 'Cannot read property \'forEach\' of undefined',
  }

  convertComments (lib/index.js:16:12)
  Object.parse (lib/index.js:41:3)
  t (test/snapshot.js:5:21)

  snapshot › latest ES features

  /Users/weiran/repo/cherow/packages/cherow-eslint/lib/index.js:16

   15: function convertComments(comments) {    
   16:   comments.forEach(comment => {         
   17:     if (comment.type === 'SingleLine') {

  Error thrown in test:

  TypeError {
    message: 'Cannot read property \'forEach\' of undefined',
  }

  convertComments (lib/index.js:16:12)
  Object.parse (lib/index.js:41:3)
  t (test/snapshot.js:9:21)

  snapshot › JSX

  /Users/weiran/repo/cherow/packages/cherow/dist/umd/cherow.js:189

  Error thrown in test:

  SyntaxError {
    column: 4,
    description: 'Unexpected token end of source',
    index: 4,
    line: 1,
    message: 'Line 1, column 4: Unexpected token end of source',
  }

  constructError (/Users/weiran/repo/cherow/packages/cherow/dist/umd/cherow.js:189:23)
  recordErrors (/Users/weiran/repo/cherow/packages/cherow/dist/umd/cherow.js:199:23)
  parsePrimaryExpression (/Users/weiran/repo/cherow/packages/cherow/dist/umd/cherow.js:3790:17)
  parseMemberExpression (/Users/weiran/repo/cherow/packages/cherow/dist/umd/cherow.js:3617:22)
  parseNewOrMemberExpression (/Users/weiran/repo/cherow/packages/cherow/dist/umd/cherow.js:3554:16)
  parseLeftHandSideExpression (/Users/weiran/repo/cherow/packages/cherow/dist/umd/cherow.js:3470:20)
  parseUpdateExpression (/Users/weiran/repo/cherow/packages/cherow/dist/umd/cherow.js:3445:28)
  parseUnaryExpression (/Users/weiran/repo/cherow/packages/cherow/dist/umd/cherow.js:3421:16)
  parseBinaryExpression (/Users/weiran/repo/cherow/packages/cherow/dist/umd/cherow.js:3341:69)
  parseConditionalExpression (/Users/weiran/repo/cherow/packages/cherow/dist/umd/cherow.js:3310:22)

  snapshot › module mode

  /Users/weiran/repo/cherow/packages/cherow-eslint/lib/index.js:16

   15: function convertComments(comments) {    
   16:   comments.forEach(comment => {         
   17:     if (comment.type === 'SingleLine') {

  Error thrown in test:

  TypeError {
    message: 'Cannot read property \'forEach\' of undefined',
  }

  convertComments (lib/index.js:16:12)
  Object.parse (lib/index.js:41:3)
  t (test/snapshot.js:17:21)

  snapshot › comments

  /Users/weiran/repo/cherow/packages/cherow-eslint/lib/index.js:16

   15: function convertComments(comments) {    
   16:   comments.forEach(comment => {         
   17:     if (comment.type === 'SingleLine') {

  Error thrown in test:

  TypeError {
    message: 'Cannot read property \'forEach\' of undefined',
  }

  convertComments (lib/index.js:16:12)
  Object.parse (lib/index.js:41:3)
  t (test/snapshot.js:21:21)

  snapshot › regular expression

  /Users/weiran/repo/cherow/packages/cherow-eslint/lib/index.js:16

   15: function convertComments(comments) {    
   16:   comments.forEach(comment => {         
   17:     if (comment.type === 'SingleLine') {

  Error thrown in test:

  TypeError {
    message: 'Cannot read property \'forEach\' of undefined',
  }

  convertComments (lib/index.js:16:12)
  Object.parse (lib/index.js:41:3)
  t (test/snapshot.js:25:21)

</details>

**Comment by KFlash** [comment]
cc/ @g-plane

**Comment by Aladdin-ADD** [comment]
seems cherow-ts tests failed, too.

**Comment by g-plane** [comment]
I assume that there are some breaking changes in the core of Cherow.

**Comment by KFlash** [comment]
No breaking changes there my, friend. Everything up to date with the ECMAScript specs.

**Comment by g-plane** [comment]
I will check it later.

**Comment by KFlash** [comment]
Closing as this will be fixed in new workflow
