### ISSUE TITLE
comment attachment

### ISSUE THREAD

**Issue by KFlash** [cherow/cherow#197]
Seems like we have got a challenge if we try to follow what's mentioned in https://github.com/cherow/cherow/issues/64.

Let's say we want to parse out an simple literal node. That node is wrapped inside a Expressionstatement node. So if we try to parse this `/* foo */ 123`. What node should we use?

The main point here is that we will trigger `onComment` in `finishNode`. Only way to do it if we should keep track on `prev` and `next` AST node. 

But acc. my example above the `onComment` will be triggered twice. The comment data have to be set to `undefined` for each parse, but still if we have a deep nested code to parse, should we trigger `onComment` for each of this nodes?

If we look at Esprima, the comment should be on `Expressionstatement` as a leading comment.

So after parsing out `Expressionstatement` we can just set it to undefined. 

Second issue if we try to parse out this one  `/* foo */ foo /* bar */ bar` and follow the method above - setting to undefined. The second comment will not exist!

I kick the ball to @g-plane and let him fix this.

@fkleuver @Aladdin-ADD Any thoughts?

**Comment by g-plane** [comment]
Not only me but also everyone can do that because I'm not sure if I can finish it.

**Comment by KFlash** [comment]
If you start on it, I'm sure someone else can continue on your PR in case you can't finish.

**Comment by g-plane** [comment]
I haven't started to do anything.

**Comment by KFlash** [comment]
Just take your time. If you can't do it because of RL stuff. We all understand that. But if that's the case I may suggest you close this issue, and open a new issue with a help wanted badge and a brief description of the problem and how it is thought to be resolved.

**Comment by g-plane** [comment]
No need to close it and just add "help wanted".

**Comment by Aladdin-ADD** [comment]
the eslint team have decided to remove `comment attachment` from espree. maybe we can reconsider the issue?

**Comment by KFlash** [comment]
Agree. Just close this and I will clean up the code when I get to work
again. The comment code itself will change anyway soon
