### ISSUE TITLE
Mini Optimizations Suggestions

### ISSUE THREAD

**Issue by bd82** [cherow/cherow#20]
Going over the code and writing some possible micro optimizations as no time to implement those right now.

- [ ] U**se NOOP pattern** to avoid rechecking "static" values which cannot change during parsing.
   * ```javascript
         // This branch condition will be executed for each and every single token.
         // Yet these flags should never **during** parsing.  
         if (this.flags & Flags.OptionsOnToken && this.token !== Token.EndOfSource) {
            this.collectTokens(this.token);
         }
      ```
   * ```javascript
          
          // -- Init time code --
          function NOOP() {}
          
          // execute this condition ONCE during parser initialization or per invocation
         // of the parse[Script|Module] APi
          if (this.flags & Flags.OptionsOnToken) {
             // The "realCollectTokens" contains the actual implementation.
             this.collectTokens = this.realCollectTokens
          }
          else {
           // the NOOP function is empty and will be inlined into nothing.
            this.collectTokens = NOOP
          }      

         // Parsing time code
         // Either NOOP or the real logic, no cost for executing the condition ten of thousands of times.
         this.collectTokens(this.token)
      ```

- [ ] **More precise boolean conditions.**
      * ```javascript
            // !x === !(x === false || x === 0 || x === undefined || x === null || x ===  "")
            if (!this.hasNext()) return Token.LessThan;

           // So it is more efficient to just write
           if (this.hasNext() === false) return Token.LessThan;
           // because hasNext always returns a boolean
         ```

- [ ] **Avoid unnecessary property access.**
   * ```javascript
         // the length of the source does not change during parsing
         if (index < this.source.length) { }

         // unsure if this would help but alternative options are:
         // 1. maintaining another property
         if (index < this.sourceLength) { }

        // 2. using a closure, (JS is single threaded, so no danger)
        if (index < sourceLength) { }

- [ ] A**void computing lines/columns** if full location tracking is not enabled 
      * can be implemented using the NOOP pattern described above.

**Comment by KFlash** [comment]
I think better to talk about thisin gitter rather than here?

**Comment by KFlash** [comment]
@bd82 im closing this and adding it to my todo. Im in the middle of finalizing the parser now so will adress this issues in the end.

**Comment by KFlash** [comment]
@bd82 Changed how  [location tracking works](https://github.com/cherow/cherow/blob/105bb3757251bea466a9e1c3182c2ef7b5c71676/src/parser.ts#L1732). Undefined are passed instead of objects if no location tracking enabled.
