### ISSUE TITLE
cherow v2.0.0

### ISSUE THREAD

**Issue by Aladdin-ADD** [cherow/cherow#233]
this issue is to track cherow todo in v2.0.0.

- [ ]  new workflow
- [ ] pass all test262
- [ ] `cherow@2.0.0-alpha` release
- [ ] `cherow@2.0.0-beta` release
- [ ] `cherow@2.0.0` release

**Comment by KFlash** [comment]
Delays in my end with current 2.0 version. I'm soon back on track

**Comment by Aladdin-ADD** [comment]
Duplicate of #245
