### ISSUE TITLE
Await expression not allowed in formal parameter

### ISSUE THREAD

**Issue by calebboyd** [cherow/cherow#237]
**Code**
https://github.com/GoogleChrome/puppeteer/blob/cd54ce388eec426034ae7b7ee5058e54b5ac5da8/lib/Launcher.js

**Expected behavior:**
Should parse the file
**Actual behavior:**
`SyntaxError: Line 104, column 29: Await expression not allowed in formal parameter`

**Comment by KFlash** [comment]
Which version of cherow is this?

**Comment by calebboyd** [comment]
1.6.8

**Comment by KFlash** [comment]
OK. There will be no 1.6.8 fixes but should work in 2.0. No npm release of 2.0. Hopefully before December 24. Try bundle current 2.0

**Comment by KFlash** [comment]
Closing as this will be fixed in 2.0

**Comment by KFlash** [comment]
This have just now been addressed and solved in the upcoming v. 2.0
