### ISSUE TITLE
Need to update package.json

### ISSUE THREAD

**Issue by KFlash** [cherow/cherow#240]
Package.json need to be updated

Cc/ @fkleuver @Aladdin-ADD @g-plane

**Comment by g-plane** [comment]
Can you state the details?

**Comment by KFlash** [comment]
Just bump version numbers

**Comment by Aladdin-ADD** [comment]
the master is build failing. do you mean to try to fix it?

**Comment by Aladdin-ADD** [comment]
I can take it.
