### ISSUE TITLE
New and changed options in 2.0

### ISSUE THREAD

**Issue by KFlash** [cherow/cherow#247]
In Cherow 2.0 the parser options have changed. 

* next
* ecmaVersion
* loc
* disableWebCompat
* module
* ranges
* globalReturn
* native
* impliedStrict
* jsx
* source
* experimental
* tokenize
* collectComments
* raw

The `raw` option changed from 1.6.8 and merged with `RawIdentifier`.

`disableWebCompat` option added to make it optional to parse with or without web compat restrictions. It's set by default.

`tokenize` does what the option says.

The `native` option let you use the native regexp validator among other things shipped with NodeJS / V8 instead of Cherows own.

**Comment by KFlash** [comment]
Note that both `AnnexB` is enabled by default to be compatible with other parsers, and the `ESVersion` is set to latest. If the `next` option is set. It will override the `ESVersion` option.

**Comment by KFlash** [comment]
@g-plane @fkleuver @Aladdin-ADD there and will probably be another new option too `buildAST` and set to default. With this option off cherow can be used as pure validator e.g. in a IDE environment. And without AST building this will be super fast. 
This also solve a problem both Acorn and Esprima have with tokenizing. With this option set to off it can do tokenizing without building AST

**Comment by Aladdin-ADD** [comment]
`ESVersion` => `ecmaVersion` (be the same as other parsers)?

docs need to be updated anyway. (related #248 )

**Comment by KFlash** [comment]
Can use the same name but I wrote `ESVersion` because `es` is shorthand for
`EcmaScript`

Update my post on it if u want

**Comment by futagoza** [comment]
Agree with @Aladdin-ADD, should be `ecmaVersion` so as to align with other parsers and avoid confusion.

Also, if [top level await statements](https://github.com/tc39/proposal-top-level-await) aren't supported by `Experimental` (haven't checked yet), then how about another option: `GlobalAwait`?

**Comment by KFlash** [comment]
The `experimental` option will in 2.0 support the same experimental
features as in NodeJS / V8. If it supported there I will make sure its
supported in 2.0.

Both NodeJS and V8 have experimental option

**Comment by KFlash** [comment]
Allow hashbang skipping was done automatically in 1.6.8 and has it's own option in current 2.0. This will be a BC now because skipping a hashbang will only be possible with the `next` option set. This because of the Stage 3 proposal "Hashbang Grammar".

**Comment by g-plane** [comment]
Does 2.0 support BigInt?

**Comment by KFlash** [comment]
Yes. Also 1.6.8 support that.

**Comment by KFlash** [comment]
All new options have been added, so take a look at latest PR for update. `disableWebCompat` is a new one, and let you disable AnnexB support.

**Comment by KFlash** [comment]
The `native` option is kind of redundant. @fkleuver How we solve this? The only purpose with this option is to use the *existing* regexp validator and scoping in `NodeJS` & `V8`. But we also have the `disableWebCompat` option which have an impact on how the scoping and regular expression validation works as well.

**Comment by KFlash** [comment]
Closing as this will be explained and documented when the beta get released
