### ISSUE TITLE
document need to be updated

### ISSUE THREAD

**Issue by aladdin-add** [cherow/cherow#248]
I've found some issues in the readme:

- [ ] some links in the readme seems broken.
![image](https://user-images.githubusercontent.com/13050025/49696421-91152f00-fbe4-11e8-8e7f-b7e66ec4bfd5.png)
![image](https://user-images.githubusercontent.com/13050025/49696437-b144ee00-fbe4-11e8-9dad-63cd64e0039a.png)

- [ ] default options not documented (https://github.com/cherow/cherow/tree/master/packages/cherow#options)

**Comment by KFlash** [comment]
Do you want to correct it in a PR?
You can also remove help wanted in readme in root

**Comment by KFlash** [comment]
@Aladdin-ADD can you try to document somewhere that cherow 2.0 have annexB support enabled by default but you can disable it. If you disable the code will behave differently. E.g. in block scoping and lexical bindings

**Comment by KFlash** [comment]
Closing as the main readme will be updated when the beta releases
