### ISSUE TITLE
Cherow 2.0 - Beta release

### ISSUE THREAD

**Issue by KFlash** [cherow/cherow#261]
Cherow 2.0 is in progress and an expected beta release will be shipped around mid of january 2019.

**Comment by KFlash** [comment]
@cherow/cherow-team The beta will probably land earlier than expected. I'm now working on finalizing the code so I can push it :) In the upcoming beta. Don't expect everything to fail as it should, and I also know about a few bugs. But at least the beta will give a "taste" of what Cherow 2.0 will become.

**Comment by KFlash** [comment]
@cherow/cherow-team The beta code will be pushed in two stages - first the scanner and then the parser code. Both are not what you guys would expect, and I'm not pushing anything before things are finalized. 

**Info** I went back to zero, and all "legacy" Cherow code is no longer. Everything is gone :)

At least the number scanner gained performance - up 20% from v. 1.6.x

```js
  Lexer - Numbers
    seek()
      script
        √ scans '1'
        √ scans '54'
        √ scans '7890'
        √ scans '.54'
        √ scans '1234567890.0987654321'
        √ scans '2e3'
        √ scans '43.78'
        √ scans '54.98'
        √ scans '9.10'
        √ scans '6e7'
        √ scans '.54E5'
        √ scans '.1E-100'
        √ scans '.0E-100'
        √ scans '0.E+100'
        √ scans '1e+100'
        √ scans '.1E+100'
        √ scans '0o12345670'
        √ scans '0o5'
        √ scans '0o34'
        √ scans '0o1'
        √ scans '0o12'
        √ scans '0o45'
        √ scans '0b01'
        √ scans '0b00'
        √ scans '0b1'
        √ scans '0b0'
        √ scans '0b10'
        √ scans '0o1'
        √ scans '00'
        √ scans '043'
        √ scans '065'
        √ scans '09'
        √ scans '09.7'
        √ scans '09.E+100'
        √ scans '08.7'
        √ scans '08.E+100'
        √ scans '06'
        √ scans '09'
        √ scans '087'


  39 passing (13ms)
```

**Comment by g-plane** [comment]
I think it's OK.

**Comment by KFlash** [comment]
@g-plane To your information. When I very soon now push the finale lexer code for Cherow 2.0, please be aware that this parser now are AnnexB sensitive. So if you turn off the AnnexB support and try to run all regular expression tests in the Acorn repo, it will fail BIG TIME!!  I wasted 2 hours myself just now to track why the h*** all Acorn tests failed until I found out I was parsing without AnnexB support!

**Comment by KFlash** [comment]
@cherow/cherow-team Let us do [everything right}(https://github.com/cherow/cherow/blob/beta/test/lexer/regExp.ts) with v. 2.0!!!

**Comment by aladdin-add** [comment]
where I can see the latest code, or a nightly version?

**Comment by KFlash** [comment]
@aladdin-add I haven't pushed anything yet, but the lexer code will be pushed within a few days. I was forced to push the regex tests now due to the huge size of that file and I don't want too have an accident with the tests :)

Night version is only on Master branch, but it's failing to push nightly builds. I asked @fkleuver a few days ago to try to fix it after his first attempt didn't work out.

**Comment by aladdin-add** [comment]
https://github.com/cherow/cherow/blob/15d0e1e28e756e0c57d43f7c2789424f33d0a960/.circleci/config.yml#L110-L112
seems the nightly build failing when running these command, as git identity not configured. I've no idea where to config, but the most easy way would be adding something like
```bash
  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"
```

**Comment by KFlash** [comment]
cc / @fkleuver Can you look into this?

**Comment by fkleuver** [comment]
Whoops. I [adjusted it](https://github.com/cherow/cherow/commit/f1aedccd544c7e5b1bcdca14e14fa263d11a1b33)

**Comment by KFlash** [comment]
@fkleuver Any thoughts about this code. Fast enough? 

```js
      // '['
      case Chars.LeftBracket: {
        // See V8: https://github.com/v8/v8/blob/master/src/regexp/regexp-parser.cc#L295
        let newState = validateCharacterClass(state, context);
        if (newState & RegexpState.Fail) {
          regExpState = RegexpState.Fail;
        } else if (newState & (RegexpState.Plain | RegexpState.Unicode)) {
          regExpState = updateRegExpState(
            state,
            regExpState,
            newState & RegexpState.Unicode
              ? RegexpState.Unicode
              : RegexpState.Plain,
            Errors.InvalidRegExpWithUFlag
          );
        }
     break;
```

**Comment by fkleuver** [comment]
Given how little regex the average code base actually contains, I think small code size ought to be a bigger concern than performance anyway. It is not worth your time to overdo it on the regex.

That said, would it help to eliminate the branching perhaps?
```ts
newState & RegexpState.Unicode
              ? RegexpState.Unicode
              : RegexpState.Plain,
```

I don't know what the `Unicode` and `Plain` flags are, but let's say they're like so (next to each other):
```ts
const enum RegexpState {
    Unicode = 1 << 1,
    Plain   = 1 << 2
}
```

Then you could rewrite that state thing to this:
```ts
(newState & State.Unicode) | (((newState & State.Unicode) ^ State.Unicode) << 1)
```
I probably don't need to explain to you :)

**Comment by KFlash** [comment]
@fkleuver Regarding regex I started out big so it was easier to keep track on failing / non-failing regex. I actually ended up with 72 KB :( Now I have my 7000 regex tests and are slowly reducing the code size and pack everything I can into bit masks. Current code size is 51 KB now.
So in the end I need to get rid of branching and optimize, but for now reducing the code size is first priority. I may need a second brain for optimizing because this turned out to be way too complex..

The `Unicode` and `Plain` - you are right. It is to keep track of wich regex should fail & not-fail with and without the unicode flag. Similiar things I have for escapes and classes. In fact I have 13 different states to keep track of, and in the end all this 13 states should tell if the regex is valid or not. 


You will see it in a few days :)

**Comment by KFlash** [comment]
@cherow/cherow-team Some beta code have been pushed. Rest is coming soon.

@fkleuver Could you take over the regexp code now and optimize it? I need to finish the lexer code

**Comment by KFlash** [comment]
@cherow/cherow-team I pushed the Cherow 2.0 lexer code. It's still early WIP because I'm experimenting with performance etc, but the code online now works and it's super fast :)

WS and comment issues from the past is all gone, and there are many tests to confirm it. Line and column now is set correctly.

**Comment by fkleuver** [comment]
@KFlash You need to push your code..

**Comment by KFlash** [comment]
@fkleuver I think I did that 3 hours ago. Maybe you should look at the beta branch?

**Comment by fkleuver** [comment]
Ah, didn't know, thanks

**Comment by fkleuver** [comment]
Lol. Why did you inline this everywhere? `(AsciiLookup[next] & CharType.IDStart) !== 0 && ((unicodeLookup[(next >>> 5) + 0] >>> next) & 31 & 1) === 0`
V8 can do that for you easily

**Comment by KFlash** [comment]
Well. What else should I do? hehe  You optimize the regex now? I'm dealing with the lexer.

**Note:** So you don't get panic. I avoided a function wrapping for single tokens in the new design. That was a slow down. Therefor some crazy code. I also try to avoid member access for everything in the lexer coz that was an slow down as well. I'm still experimenting with this, so don't think so much about it :)

**Comment by fkleuver** [comment]
The main thing that's crazy about it is you inlining bit twiddles as much as possible 😆 come on lol

**Comment by KFlash** [comment]
I know, but the code is super un-optimized. I had to get it working first :) You fix it?

**Comment by KFlash** [comment]
@fkleuver I plan to flatten the entire regex  to an infinite state machine. Want to do it? Then you just add `TopLevel` to `Type` and do `type |= Type.TopLevel` and you can increment the  `depth++`; like  `depth++` for each level; So the finale `depth` check would be `if (depth)`.
If flatten like this it is easy to swap out the switch statement with table lookup wich also is my plan.

**Comment by KFlash** [comment]
@cherow/cherow-team In the upcoming beta both `onComment` and `onToken` have been added and the `onComment` works the same way as in Acorn. The line and column bug with comments known from 1.6.x is fixed. I added tests for this.

**Comment by KFlash** [comment]
@fkleuver Did you optimize that file?

**Comment by KFlash** [comment]
@cherow/cherow-team The beta lexer code is almost done. I have to think a little more about identifiers before open an PR. There are some design changes in the scanner - e.g. one char punctuator lookup and reduced use of member access.  In fact it should be faster.

@fkleuver Did you optimize anything, or do I need to fix it *before* I open an PR?

**Comment by fkleuver** [comment]
@KFlash I did not have time today

**Comment by KFlash** [comment]
No rush. I'm still focused on identifiers.
I noticed you got the nightly build working. Great work!!

**Comment by KFlash** [comment]
@fkleuver I'm now starting to implement the parser code for 2.0 Beta. I skipped the advance identifier code for now until parser code is done because I need to rethink how to implement escaped identifiers etc.

If you have time and feel to play around, can you try to benchmark the scanner and optimize the code?

**Comment by KFlash** [comment]
Very soon I can merge to Master, but right now I'm not so happy with a few files. E.g the regex that need a clean up before moved to Master. Did you look at it?

**Comment by fkleuver** [comment]
Master is basically the development branch, you shouldn't apply "release" quality bars to it. If you wait for all code to be perfect then there will be one big merge to master in a couple weeks and only sporadic changes/fixes afterwards. It kind of beats the purpose of having a nightly.

I did look at it, but I prefer to do perf optimizations and such when you are done with the spec compliance side of things and it's all tested. It's both more efficient and more effective for me to treat the code base as a whole and apply certain optimizations across everything rather than do it in bits and pieces while you're still working on other parts.

You can leave code behind in an ugly state if that's easier for you, I'm cool with that. I don't think it's a good idea for us to work on the same parts at the same time since we both have a tendency of overscoping everything :)

**Comment by KFlash** [comment]
I work locale as of now and will merge to Master within a few days. 
Regarding lexer and the regex stuff. As of now I'm done with that. It should now follow the ES specs and even TC39 tests pass for most of the lexer code. And you got around 10 200 tests to prove it as well. 
Did I miss anything?  And the parser code is now build on top of the lexer as a dependency, and independent.
I'm now mainly focusing on fixing the parser code and stopped doing anything on the lexer level.

**Comment by fkleuver** [comment]
> But in the long run it's up to you if you choose to do something or not. It's a open source project.

As you know I'm also actively working on Aurelia and an SPA framework is a bit more sensitive to timing, thus I put most of my free time into that right now. It is taking a longer time than expected though. But that's just how it goes. If I did not want to help out I would say so, but I do, and it's just not the right time.
I don't understand why everything suddenly has to happen in one month after you've been gone for half a year, after already working on this for over another year. If you retire, I'll still be around.

I explained to you how I wanted to do this. While you are working on it, I want to help lower the friction for you as much as possible by assisting with CI / workflow / release management. And of course tell you whatever I know regarding perf.
When you are done (or lowering the pace / going into maintenance mode), things have stabilized, that's when I want to help polishing things, add demo's/examples, etc. Otherwise I just end up chasing you fixing stuff that previously worked. We've been there in 1.6 and I know how you work, so this is the best way.


Keep in mind your departure and return were both unplanned and so I due to there being much more competition in SPA land there is more time pressure to get things done. Eventually that will settle down when the new major version is done. I also want to use that new version to make a cool online REPL for cherow.

**Comment by KFlash** [comment]
@fkleuver I got it. And it also complicate things for me when I'm in the middle of development. 
BTW. Could you solve [this issue](https://github.com/cherow/cherow/issues/277) and also convert token.ts back to binary?

**Comment by KFlash** [comment]
@fkleuver You convert back to binary? And for the scope.ts.Should we use map or set instead?

**Comment by fkleuver** [comment]
@KFlash pushed. Note that 12 tests fail, not sure if that's due to the change or if they were already failing. Also note that it created some typing errors since the tokens are now strongly typed and I had to explicitly cast a few to `<Token>` in `state.ts`. This is because typescript can't always infer the types correctly (either that or it actually indicates an error in the logic)

**Comment by KFlash** [comment]
@fkleuver I have no failing tests locale, so the 12 failing tests was new to me. Can you verify that they was existing before you did you change? CircleCi didn't fail as far as I could see.

Why map or set? See the scope.ts file. I need to refactor that one for performance reasons. Guaranteed uniqueness / checking for existence is what needed in block scoping and lexicals

**Comment by KFlash** [comment]
@fkleuver I tested your token.ts change against my locale copy. No errors except for this test `async: await`.
Are `await` seen as a contextual keyword and / or identifier?

**Comment by fkleuver** [comment]
We're full on bit slots. Are there any we can safely overlap?

**Comment by KFlash** [comment]
Context masks? You can still create a few.  `OptionsExperimental` needed?  I also think `TopLevel` and `Global` can become one in near future. It depends on the arrows and `new.target`.  `ExpressionStart` should be renamed I guess. It's only purpose is to allow regular expressions. So maybe `AllowPossibleRegEx`. Same thing with `InArguments` should be `InArgList` to match up `Type`.
`InMethod` could be passed as an func arg instead.   `Statement` could also be passed as arg in func decl. It's only purpose is for `IFStatement`.

I'm offline now. Wanna take a stab at it?

**Comment by KFlash** [comment]
@fkleuver Could you also update token.ts and create a token for this to reduce branching? 
`state.token === Token.NumericLiteral || state.token  === Token.StringLiteral`

**Comment by KFlash** [comment]
@fkleuver The reason you need to use `<Token>` is because - in my original `token.ts` that you converted  to binary literal - have metadata attached to the `enum` values.

**Comment by axefrog** [comment]
With reference to being full on bit slots, if someone wanted to fork cherow and extend it with experimental language features, how difficult will this be? For instance, let's say I wanted to introduce experimental async-like syntax but for observables, and then have cherow parse my code and understand 2-3 new keywords, how much friction is to be expected in adapting the code? I know you have favoured the current approach in order to maximise performance, and that performance is the reason that cherow does not have a plugin-enabled architecture, but I also know that the intention has been that people should be able to fork cherow and add any desired extensions relatively easily. I suppose this question is also relevant with respect to future official language extensions we might see in years to come.

**Comment by KFlash** [comment]
Fork and extend Cherow with 2 -3 new keywords is easy enough. Just extend [this list](https://github.com/cherow/cherow/blob/beta/src/token.ts) and modify the lexer code - add your keyword to the [lookup table](https://github.com/cherow/cherow/blob/beta/src/scanner/scan.ts#L15) in the lexer code. That is easy and have nothing to say if Cherow is full on bit slots. The bitmasks used is internal and used to keep track of the states.

But I will try to think of a performant way to extend some part of Cherow.

**Comment by axefrog** [comment]
Ah cool, good to know!

**Comment by fkleuver** [comment]
@axefrog To further clarify, we have 8 bits slots reserved for types, 4 for precedence and the remaining 19 are standalone bit masks we use for simple `token & Token.SomeMask` checks. Those 19 are all in use (although we could probably clear up 3-4 slots by carefully analyzing where they do not overlap and merging those)
For the 8 bit slots used by the type we don't use a slot per type but we fully count them one by one and use the `Token.Type` mask to isolate them like so: `(token & Token.Type) === Token.SomeThing`. 8 bits gives you 256 slots to use within the `Token.Type` mask and we're currently only using 117, so there's still *plenty* of room there.

@KFlash Another thing we could do is apply the same principle as `Token.Type` to merge a few bits that are not on hot paths. I'm don't have any particular tokens in mind yet, but I'm sure a few of them would be fair candidates.

**Comment by KFlash** [comment]
@fkleuver If still slots available, can you extend token.ts with this. Kind of urgent

- Eval and Arguments token as it was before
- One token for StringNumeric
- One token for IsComputed

plus the  other tokens I mentioned before

**Comment by fkleuver** [comment]
Can you give me a complete list of all the tokens you need now and in likely near future with very brief clarification of what for? Then I can plan it better and not create a new problem

**Comment by KFlash** [comment]
@fkleuver Here you go!

- Token.Eval and Token.Arguments  (*need to be identifier and also marked as reserved keyword*)
- Token.IsEOCO (*comma, semicolon, right brace, assign*)
- Token.IsGetSet (*Get, Set*)
- Token.IsStringOrNumeric (*NumericLiteral + StringLiteral*)
- Token.IsString (*StringLiteral*)
- Token.IsComputed (*Left bracket*)
- Token.IsIteration (*whilekeyword, dokeyword, forkeyword*)
- IsPattern (*LeftBrace, LeftBracket*)

**Comment by fkleuver** [comment]
Well it's just a button, and I think the honor should be yours ;p

**Comment by KFlash** [comment]
Ok. I will do it soon. Btw. you fix the tokens?

**Comment by KFlash** [comment]
@fkleuver Whatever I do I can't get this program `class o {f(){ let x; var x; }}` to pass anymore. It did pass in 1.6.x. Should it be documented as a bug or a new feature?

**Comment by fkleuver** [comment]
The tokens are not easy to fix. Some logic probably needs to change. There's always a couple tests that go bad

`class o {f(){ let x; var x; }}` is valid because it's in a function, so the `var` is hoisted to the top and technically comes before the `let`. It is only valid in a function

**Comment by KFlash** [comment]
Read [this](https://tc39.github.io/ecma262/#sec-function-definitions-static-semantics-early-errors) It should fail, but V8 got it  wrong. Or I missed something? You can also check it with [this parser](https://astexplorer.net/#/gist/749818a5f75b69e0dd84854e441fd851/74ec08719a951f8d398d584e4089f0d3a285790a)

Is there any of the tokens that's possible to fix?

**Comment by fkleuver** [comment]
Yeah, you missed this:

> NOTE 1
The LexicallyDeclaredNames of a FunctionBody does not include identifiers bound using var or function declaration

Possible, but tricky, and I don't know if I merge/remove something that might cause problems later down the road because currently you only have 11k tests. It seems like many more tests are needed before we can safely play around with the tokens.

**Comment by KFlash** [comment]
hmm interesting...

Let tokens be for now then and save the list a secure place until we are ready for fixing tokens.

You have time to help cleanup and optimize? I'm opening PR  now for  every new change I do

**Comment by fkleuver** [comment]
Don't we need more tests first?

**Comment by KFlash** [comment]
We have 13k tests now and it covers around 95% of the code base.

**Comment by fkleuver** [comment]
What about the 45k in 1.6?

**Comment by KFlash** [comment]
The 45k tests include failing tests. Most of current code base doesn't fail yet after the spec. That's next to fix.
Anyway. I will try add some more tests now. Give me a few hours 

Btw. Will this Master code end up as a nightly build?

**Comment by fkleuver** [comment]
Yeah it should

**Comment by KFlash** [comment]
Ok. Regarding browser stack. Will you add it and update the readme with a logo?

**Comment by fkleuver** [comment]
Yeah I added the logo and filled in the request form. Now we wait.

**Comment by KFlash** [comment]
I found one nasty lexer bug. I fixed it but now it doesn't fail on implicit octals in strict mode. Can you have a look?

**Comment by fkleuver** [comment]
If you tell me what bug you fixed and what test fails. Lol :)

**Comment by KFlash** [comment]
Line 76. It failed on `0` in strict mode. The scanner saw it as  an implicit octal. I added additonal code on line 76 - ` else if (index < state.length && (next >= Chars.Zero && next <= Chars.Nine)) {` so if it's a leading 0 like `01`, `0800`  etc it should be seen as implicit octal. For `0` it now falls through and works.

Line 1 in `scanImplicitOctalDigits` tell is should fail in strict mode, but doesn't.

I removed the tests for it so need to create new tests and probably optimize that logic.

**Comment by KFlash** [comment]
@fkleuver Can you investigate why this goes into a infinity loop?

```js
chars.escapeRegex = {
  '?': /\?/g,
  '@': /\@/g,
  '!': /\!/g,
  '+': /\+/g,
  '*': /\*/g,
  '(': /\(/g,
  ')': /\)/g,
  '[': /\[/g,
  ']': /\]/g
};
```

**Comment by KFlash** [comment]
@cherow/cherow-team **Info** The code for class and object literal implementation is larger than in 1.6.x because we agreed early on that we prefer performance over code size. 

Here is the performance difference between 2.0 Beta and 1.6.x:

![bench](https://user-images.githubusercontent.com/31855118/51069013-9b05d400-1661-11e9-8fdc-1a8fe9e68f9e.png)

**Comment by KFlash** [comment]
This is the first official benchmark result for Cherow 2.0. It's  now twice as fast as Acorn.

![bench](https://user-images.githubusercontent.com/31855118/51087039-f1b9fd80-1788-11e9-81f7-fec897aeffb7.png)

**Comment by KFlash** [comment]
@cherow/cherow-team My crazy arrow and arrow async implementation in Cherow 2.0 had a reason. See benchmark  below. Over 100% faster than 1.6x plus fixed a few bugs in 1.6.x as well.

![arrows](https://user-images.githubusercontent.com/31855118/51111662-aa3e7a80-1837-11e9-876a-3e7eb993917b.png)

**Comment by KFlash** [comment]
@fkleuver Would also need to add a `HashKeyword` token for `#` (*private names*)

**Comment by KFlash** [comment]
@axefrog [Here](https://github.com/cherow/cherow/commit/d023b5d14a2eb0cf78ed83d95ed11b9a8092fefd) you can see how easy it is to extend the parser to accept new tokens and modify the scanner to accept it

**Comment by KFlash** [comment]
Closing this as we now are on RC2
