### ISSUE TITLE
Performance vs. Code size

### ISSUE THREAD

**Issue by KFlash** [cherow/cherow#262]
@Aladdin-ADD @fkleuver what do we prefer. Performance or small code size? If we prefer code size I need to merge several method which will cause performance regression and unwanted branching. E.g. merging func decl with func expr require a lot of if else to keep track of current state.

**Comment by fkleuver** [comment]
Merging function declaration with function expression parsing sounds reasonable, but I I'd argue for leaving them separate for now. When 2.0 is truly near completion we can always go around trying to merge stuff as a final polishing step but doing that before even the test suites are complete seems rather risky

**Comment by futagoza** [comment]
I prefer performance :)

**Comment by KFlash** [comment]
@fkleuver Agree that we should optimize and tweak in the end. Doing that now can break more than it can heal :)
@futagoza I prefer performance too, and to archive that goal I sometimes have to create different code paths and walk down them separately to avoid branching bottlenecks. If I do so, the code size will increase. Within a few hours I hope I will push a code snippet for object literal parsing that better can illustrate this.

**Comment by g-plane** [comment]
I prefer performance.

**Comment by KFlash** [comment]
Ok, guys. I will increase performance in the most critical parts of the parsing with a perfect hash 👍

**Comment by Aladdin-ADD** [comment]
performance +1

offtopic: we have a team: @cherow/cherow-team , so you can use it and  no need to mention everyone in the team.

**Comment by KFlash** [comment]
@cherow/cherow-team Guys! If we all prefer performance over code size we need to expect to see code {like this](https://github.com/cherow/cherow/blob/cherow_2/src/parser/expressions.ts). Is that acceptable?

**Comment by g-plane** [comment]
What's the problem of that file?

**Comment by KFlash** [comment]
@g-plane Is there any problem? As you see of this tread the question was performance vs code size. So in case we prefer performance we need to see code like that I linked too. It's has many more code lines comparing to a "slow" version.

**Comment by fkleuver** [comment]
@KFlash What would be the slow version of that?

**Comment by KFlash** [comment]
Look at the old code. You parse out async, get, set first etc. Then you
need to backtrack to do the rest and call 'parseAssignmentExpression'
before ending up in a huge switch statement. For validation you need global
masks and a lot more.

That's a short explanation. You can also look at acorn and esprima for a
slow version

**Comment by KFlash** [comment]
@fkleuver And also doing a "slow version" will do it much harder to make the parser fails on cases like `(a, {a:a}) => {}`, `(a, {a}) => {}`. Then I'm also forced to do a "slow" implementation of the scoping code.
