### ISSUE TITLE
FunctionExpression 'expression' property is deprecated

### ISSUE THREAD

**Issue by axefrog** [cherow/cherow#263]
Just noticed an unexplained `expression` property in `FunctionExpression` and upon further investigation it appears to be deprecated.

https://github.com/estree/estree/blob/master/deprecated.md#functions

```
extend interface Function {
    body: BlockStatement | Expression;
    expression: boolean;
}
```

Screenshot of my own console output produced by cherow, in this case as the value of a `Property` in an `ObjectExpression`:

![image](https://user-images.githubusercontent.com/298883/50371261-c79a7300-0602-11e9-9f4b-c2a1d40a66ef.png)

**Comment by KFlash** [comment]
The expression property are used for 2 reasons. The first one is to be compatible with other parsers, and also the arrow function uses it to determine if it's an arrow with / without an block body.

I'm agree that there is an difference from the ESTree specs for function decl & expr as seen [here](https://github.com/estree/estree/blob/master/es5.md#functions) and the arrow ESTree specs seen [here](https://github.com/estree/estree/blob/master/es2015.md#arrowfunctionexpression)

But what action to take? Break compatibility with other parsers? As you see [here](http://esprima.org/demo/parse.html?code=(function()%7B%7D)) Esprima  do the same thing. Acorn too.

I can change this in the upcoming 2.0, but doing so will make the AST output produced by Cherow non-compatible with other parsers.

**Comment by axefrog** [comment]
All good, just reporting what I see :)
