### ISSUE TITLE
Coverage stopped working on december 3 - 2018

### ISSUE THREAD

**Issue by KFlash** [cherow/cherow#277]
cc / @fkleuver Coverage doesn't work, and the coveralls.io haven't been updated since december 3 - 2018. You fix this?

**Comment by KFlash** [comment]
@fkleuver Can you also add to your TODO to fix CircleCI? Is the tests running at all? Locale on my computer most of all tests are broken for the last 12h. Same files on CircleCI and they pass there,

Further. If you look at my latest commit, you see the assignment tests. The last test is a literal AST node. And it pass on CircleCI.

See my second last commit. Same test, but now there the literal AST node is an identifier and the test should have been broken. But it also pass on CircleCi without any error.

So CircleCi broken?  I'm not sure what's wrong locale but I'm reformatting the computer now and if that's not working I will go out and buy a new one today.

**Comment by fkleuver** [comment]
What version of NodeJS are you running on your computer?

**Comment by fkleuver** [comment]
I get 10025 passing and 2 failing tests when I run locally. CircleCI for some reason only sees the 10025 ones that pass. Smells like a caching issue. I'll take a look tomorrow.

How many computers have you gone through in the last 5 years? 😆

**Comment by fkleuver** [comment]
How is your new computer?

**Comment by KFlash** [comment]
It works much better than the laptop  I used a few days ago. Bought a desktop computer now.

**Comment by KFlash** [comment]
@fkleuver Any ideas when this issue will be solved?

**Comment by fkleuver** [comment]
Any preference? Do you want coveralls back?
For some reason codecov can't get access

**Comment by KFlash** [comment]
Coveralls we used before and access to that one

**Comment by KFlash** [comment]
I tried to activate Codecov now

**Comment by KFlash** [comment]
Closed as it seems that @fkleuver is on vacation.

**Comment by KFlash** [comment]
@fkleuver We never used codecov before, and it doesn't seem to work. Anyway you got permission to access all Github apps to this repo.

**Comment by KFlash** [comment]
@fkleuver You was the one who fixed the workflow for v. 1.6x, remember? As seen [here](https://github.com/cherow/cherow/blob/1.x/package.json#L7) and [here](https://github.com/cherow/cherow/blob/1.x/.travis.yml#L32) and [here](https://github.com/cherow/cherow/blob/1.x/package-scripts.js#L27) we always used coveralls. **not** Codecov. And it was working. After the refactor of the workflow for v. 2.0 this stopped working somehow and not related to CodeCov. Coveralls have GH access and should work.
You forgot this?
