### ISSUE TITLE
false positive parsing numric literals

### ISSUE THREAD

**Issue by lorenzofox3** [cherow/cherow#28]
Hi,

```Javascript
"const t = 2.34e-;const b = 4.3e--3;"
```
are parsed (on the online tool) whereas they should not.

**Comment by KFlash** [comment]
Hi. I didn't address all failing tests yet, but will take a look at this one.

**Comment by KFlash** [comment]
@lorenzofox3 Sorry delays, but the problem should have been solved. Can you confirm?

**Comment by lorenzofox3** [comment]
👍
