### ISSUE TITLE
CircleCi fails to run all tests

### ISSUE THREAD

**Issue by KFlash** [cherow/cherow#285]
On latest commit CircleCi only runs `10025 passing (3s)` tests. The real amount of tests should be  `11740 passing (3s)`. 1700 tests doesn't run!

@aladdin-add Ideas?

**Comment by aladdin-add** [comment]
that's strange, I've got 3 failing tests, while the circleCI passed.

```bash
 1) Lexer - OnToken
       tokenize right brace:

      AssertionError [ERR_ASSERTION]: { hasNext: false, line: 1, column: 1, index: 1, token: 536870927 } deepEqual { token: 15, hasNext: false, line: 1, column: 1, index: 1 }
      + expected - actual

         "column": 1
         "hasNext": false
         "index": 1
         "line": 1
      -  "token": 536870927
      +  "token": 15
       }
      
      at Context.it (test/lexer/onToken.ts:27:9)

  2) Lexer - Whitespace
       script
         fails on HTML comment in strict mode:
     AssertionError [ERR_ASSERTION]: Missing expected exception.
      at Context.it (test/lexer/whitespace.ts:41:9)

  3) Lexer - Whitespace
       module
         fails on HTML comment in strict mode:
     AssertionError [ERR_ASSERTION]: Missing expected exception.
      at Context.it (test/lexer/whitespace.ts:41:9)
```

**Comment by KFlash** [comment]
@aladdin-add Can you comment out the 3 tests that fails for you and push to the  repo?

**Comment by aladdin-add** [comment]
pushed to the branch beta.

Did you forget to push some tests? seems circleCI were only getting 10025 tests, same result on my computer.

**Comment by KFlash** [comment]
Everything is pushed to the beta branch. Over 11k tests. And no failing tests in my end.

**Comment by KFlash** [comment]
11738 passing (2s) is what I have pushed to the repo

**Comment by aladdin-add** [comment]
I see, I've make a PR (#286) to fix it.

**Comment by KFlash** [comment]
Ok.I also now added more tests. You can  run them?

**Comment by KFlash** [comment]
@aladdin-add You update beta branch  with same patch?
