### ISSUE TITLE
Rollup hooks deprecated warnings during bundling

### ISSUE THREAD

**Issue by KFlash** [cherow/cherow#287]
After upgrading to Rollup 1.x a lot of warnings when you try to bundle.

cc / @fkleuver

**Comment by aladdin-add** [comment]
FYI: https://github.com/ezolenko/rollup-plugin-typescript2/issues/126

**Comment by KFlash** [comment]
@aladdin-add You will try to fix it?

**Comment by aladdin-add** [comment]
I can update when it was fixed in rpt2.
