### ISSUE TITLE
token.ts ends   in infinity loop

### ISSUE THREAD

**Issue by KFlash** [cherow/cherow#291]
cc / @fkleuver `*` isn't set as an valid expression start in `token.ts` so this program `function *a(){yield*}` goes into a infinity loop before the parser dies. Can you confirm this?

**Comment by KFlash** [comment]
@fkleuver You plan to fix this or I roll back to previous token.ts?

**Comment by KFlash** [comment]
Hmm how can it be then that it runs into infinity loop because it can't consume the `*`?

**Comment by fkleuver** [comment]
I debugged locally but it's consuming the `*` just fine, and throws `"Line 1, column 21: Unexpected token"` in both `Context.Empty` and `Context.Strict | Context.Module` so how are you getting an infinite loop?

**Comment by fkleuver** [comment]
Speaking of which, I pushed that config to master so you can use it as well if you need to debug tests.

Just go to debug in VS code and pick "Launch mocha tests":
![image](https://user-images.githubusercontent.com/9655331/51099512-7cbee600-17d1-11e9-99a4-fd48d5e3728b.png)

Comment out the tests you don't want it to loop into, put a breakpoint, wait a bit and voila: 
(F11 to step in, F10 to step over, F5 to continue, you know the drill)

![image](https://user-images.githubusercontent.com/9655331/51099547-ac6dee00-17d1-11e9-88b2-b0c0a806cb0f.png)

**Comment by KFlash** [comment]
Get it, and I think this issue is fixed. It now fails as expected, so I think my validation code last night fixed  it from running infinity loop without me knowing it :) Closing.
