### ISSUE TITLE
Extensibility

### ISSUE THREAD

**Issue by devsnek** [cherow/cherow#292]
Wow this parser looks fantastic. I'm super excited to see that its being tested against test262 unlike many of the other options.

I'm working on a js engine written in js (https://github.com/devsnek/engine262) and currently using acorn. I'd love to switch to cherow but I'm concerned about being able to extend the parser. This is very important to me because the engine is used to prototype and test new features for js. In acorn you can just subclass and override, but it looks like everything here is direct calls to other functions.

Are there any plans to allow extending and modifying the parser?

**Comment by devsnek** [comment]
i'm not to concerned about performance being affected, as the bottleneck in the engine definitely isn't parsing.

With the current design i can't really come up with any good ideas for overriding that wouldn't hurt perf (for example stuff like checking in every function for an override on the state).

Maybe every parser could be put onto an exported object and referred to that way? `parsers.parseCallExpression(state, etc)` instead of just `parseCallExpression(state, etc)`.

**Comment by KFlash** [comment]
cc / @fkleuver You have any good ideas about this?

**Comment by fkleuver** [comment]
We could distribute differently bundled versions of the parser where an optimized version only exports the main API entry point (meeting the speed and library size goal) and a full version could export everything as well as retain the const enums.

I imagine folks who build advanced tooling on top of this are far less concerned about library size and more with the parser simply being as correct, accurate and reliable as possible (with speed being a nice bonus but not even a primary concern).

Ultimately the unmatched spec compliance, backed by superb test coverage and density, paired with it being very fast, is what would drive most people to cherow. I don't think a lot of people care about 30kb more or less.

**Comment by KFlash** [comment]
Sounds like a good solution, but it will not kill the performance? And is that something you can implement?

**Comment by fkleuver** [comment]
It will not affect performance because the code is entirely removed during the bundling process for that particular output. It will of course affect performance for the output *with* the code included, but the user can choose for themselves whether to make that tradeoff.

I do not have time for that right now due to priorities as I explained earlier, but I've no doubt I can add it in at a later point in time without introducing breaking changes. This sort of thing is easy to inject

**Comment by KFlash** [comment]
See #293

**Comment by KFlash** [comment]
@devsnek 2.0 have been reached now, so waiting for @fkleuver to take care of this issue.

**Comment by KFlash** [comment]
@devsnek @aladdin-add @fkleuver 

I think we come to a conclusion that Cherow will **never** be so extandable as you hoped for, but take a look at the [Buntis TS parser](https://github.com/buntis/buntis) I'm working on. 

This will accept both JS and TS, and also support plug-ins in the same way as Acorn.
