### ISSUE TITLE
Roadmap - Cherow 2.0 finale

### ISSUE THREAD

**Issue by KFlash** [cherow/cherow#293]
Things needing finished before finale Cherow 2.0:

**RC1** - **completed!**

- Implement all Stage 3 features
- 100% test coverage for everything implemented

**RC2** - (*Work in progress*)

- Class decorators (*seems to be very popular so it will be added*)
- Location tracking
- Optimizing
- 100% failing acc. Test262
- Escaped identifiers

**RC3**

- Finish tokenization (*included edge cases*)
- Implement all options and make sure they work
- Re-implement our own Regex validator
- Optimize
- Cleanup the code base

**Finale**

- Run all Test262 tests
- Run all Test262 parser-tests
- Make sure all issues in all other parsers are fixed in Cherow
- Implement a way to extend the parser
- Optimization
- Make sure the code base is 20% smaller than Acorn
- Documentation

**Comment by aladdin-add** [comment]
updating the docs before rc-releasing, so we can get more feedback earlier. thoughts?

**Comment by KFlash** [comment]
The docs should be updated as early as possible. Huge changes so easier to keep track. Is that something you can do?

**Comment by aladdin-add** [comment]
I'm not sure I can do it -- someone has a full knowledge of the changes would be better! (e.g. you 😄)

**Comment by KFlash** [comment]
What knowledge are you lacking? I updated the readme already with the new options. Other than that is this

* Directive prologue no longer attached on literal node by default (*option: 'direvtive' to enable*)
* Block scoping
* Lexicals
* Exported binding restrictons. E.g `export {a}; is forbidden`.
* AnnexB on by default, but can be switched off so Cherow support both modes(*option*)
- OnComment (*works as in Acorn*)
- OnToken (*tokenization*). "Spits out" in array or callback current token with loc data

Most of this is in the ECMA specs

Will be enabled soon

- Ecma version

**Comment by aladdin-add** [comment]
hmmm, I missed you have updated readme. I will try.

**Comment by KFlash** [comment]
@cherow/cherow-team I'm now in a process where I fixing bugs and make the parser fail where it should, so I'm playing around :) However it's easy to get it to fail as it should, but the result would be 

1) Ugly looking code
2) Performance regression

So I need to come up with a performant and nice looking way !

**Comment by KFlash** [comment]
Current Cherow 2.0 perf benchmark

![bench](https://user-images.githubusercontent.com/31855118/51358013-76e04200-1afc-11e9-8815-26faff84b036.png)

**Comment by KFlash** [comment]
@aladdin-add You may as well document that Cherow 2.0 strictly follow the ESTree specs so not 100% compatible with the ESTree AST produced by other parsers. For arrows the `generator` property is gone and for functions the `expression`  property is gone.

**Comment by g-plane** [comment]
I think we should open a new issue to discuss what should be documented.

**Comment by KFlash** [comment]
You fix that @g-plane  ?

**Comment by g-plane** [comment]
I mean just open an issue for discussion.

**Comment by aladdin-add** [comment]
@g-plane I've opened an issue for this: https://github.com/cherow/cherow/issues/284

**Comment by KFlash** [comment]
@cherow/cherow-team Cherow have now reached RC 1 stage. It's enough tests to confirm that "basic" parsing works. The TODO on RC 2 stage is a little more complex, so will make another branch for that.

**Comment by aladdin-add** [comment]
how can I run the benchmark in my local computer?

**Comment by KFlash** [comment]
Use the benchmark in the root folder

**Comment by KFlash** [comment]
@cherow/cherow-team I have until now spent some days to get Cherow parsing after the specs and wrote enough tests to avoid trouble when I'm now going to get the parser to fail after the specs. This will be done in a separate branch. But at this stage Cherow 2.0 can be used as a normal parser.

**Comment by fkleuver** [comment]
@KFlash have you been able to run the Test262 suite yet?

**Comment by KFlash** [comment]
I know. If you scroll up you will notice I'm working on RC 2 and one of the bullets 
are `100% failing acc. Test262` and also notice the *Finale*

**Comment by KFlash** [comment]
@fkleuver Did you try to parse anything with Cherow 2.0 RC1 ?

**Comment by KFlash** [comment]
@cherow/cherow-team This is the benchmark results with the cover grammar implemented:

![coverg](https://user-images.githubusercontent.com/31855118/51435159-39bab200-1cac-11e9-8bbd-e09e1bab2d8c.png)

**Comment by KFlash** [comment]
@cherow/cherow-team Guys! Sorry to say this, but the performance dropped with 2% after I implemented the cover grammar. Cherow 2.0 is still in average 36% faster than v. 1.6.x.

I'm still scared to "*lock down*" the grammar code, but hopefully I can reduce the performance loss with only 1% soon.

**Comment by KFlash** [comment]
@fkleuver @cherow/cherow-team I just pushed Cherow 2.0 to the finale stage. What's left to fix is some basic development again and the last non-failing tests. It's now much left :)

I only have 9 days left to finish Cherow 2.0 now. January 30 is the date I hope to log out for the very last time.

**Comment by axefrog** [comment]
Just playing around with 2.0 at the moment and seems to be working nicely, though my experiments are hardly comprehensive. I was wondering how `onToken` is supposed to work. The first argument is just a big number. I'm not sure what it relates to. The `onComment` option is great and seems to work well.

**Comment by KFlash** [comment]
Good to know 2.0 finally starts to work as it should!
Regarding the `onToken` option is just me being lazy. The big number is actually the token you are parsing, and I have to finalize a wrapper around it so the output will be `Identifer`, `Keyword`, `Numericliteral` etc. It's a tokenization and the first argument is always the token you just parsed..

**Comment by KFlash** [comment]
@fkleuver It's only 255 Test262 non-failing tests left to fix. Most of them are related to arrows & async arrows and need to be tracked with the mutual parser flag. It's an easy fix, but before I do that, do you have time to start to optimize the code?  
After optimization easier to get the last non-failing cases fixed.

**Comment by KFlash** [comment]
@cherow/cherow-team I'm getting closer now. Not so many non-failing left

```js
 ✔ 4548 invalid programs produced a parsing error
 ✔ 201 invalid programs did not produce a parsing error (and allowed by the whitelist file)
```

**Comment by KFlash** [comment]
@fkleuver I sent you a PM on Gitter. Try read it and respond.

**Comment by KFlash** [comment]
@fkleuver It seems like we got a lot of token issues!? First I got `JavaScript heap out of memory` in `objlit` parsing, and without modifying anything it suddenly worked again.

Now the issue have moved to class decl / expr parsing. I thought it happen because I was removing a "stopper" that did throw an error. And because of that it ran out of memory. 

But... I started to re-write class decl / expr parsing as seen in [this gist](https://gist.github.com/KFlash/440f1c7b44982122a5d836c741b13519). And easy to notice there is a "stopper" for each non-valid token so there shouldn't be any infinity loop etc.

I bundled with the new code and got the same issue `JavaScript heap out of memory`.

I then copied back in the old class decl / expr code, and it works just fine.

I tried to track this a little and it seems it bailing on `Token.IsIdentifier`.

**Comment by KFlash** [comment]
@cherow/cherow-team @axefrog I finally managed to finalize the complexity of Cherow 2.0 and are in the process of finalizing.

To point out how complex I made Cherow 2.0, you can try it [here](https://cherow.github.io/cherow/?code=function%20a()%20%7B%7D%0A%0Afunction%20a()%20%7B%7D&method=parse&range=false&loc=undefined&next=false&module=true&raw=false&jsx=undefined&directives=undefined&attachComment=undefined&webCompat=true)

In the demo both `AnnexB` and `module code` are enabled, and you get the same result as in Acorn. **But** try to turn off `AnnexB` support, and the `module code` will parse without errors. 

Also note that `AnnexB` behave differently. It depends if it is enabled, and also if you have enabled module code.

**Comment by KFlash** [comment]
Guys! I reached my second last goal - to go alive with a demo and show off what you can expect from Cherow 2.0. From now on I will work offline and finalize it. And there will be a PR for the last stuff so we can agree about error messages and other basic stuff. Give or take a few days and I'm going to land this !!

**Comment by KFlash** [comment]
@cherow/cherow-team Cherow 2.0 now exist on Master branch  and should fail / pass acc. Test262 suite plus / minus a few tests, but a PR is allowed ;)

Ranges have been added and I think I stop working on this project for now. Cherow should be stable enough and parse what you would expect.

I may not be so active anymore from now on, but I will keep working on improving things and add in the small "missing" parts when I get time.

So. That's it!! End of january 2019 was my dead line :)

**Comment by axefrog** [comment]
Wow, great work, much appreciated by myself and many others I'm sure! Enjoy winding down, you've definitely earned it :)

**Comment by KFlash** [comment]
@axefrog I just want to inform you that there is an difference between Acorn and Cherow. Sometimes you can experience that you can parse code with Acorn that you can't parse with Cherow. 
`(a=1)=2` is one of many examples. In Acorn you can parse it but throws in Cherow because it's actually an invalid LHS assignment.

**Comment by KFlash** [comment]
I'm closing this now. 2.0 have been reached and the few things left I will take care of it when I get time except for the documentation that @aladdin-add should fix.
