### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by KFlash** [cherow/cherow#303]
Cherow 2.0 is very close to finale and this is the sad reality when it comes to performance. It's almost equal to 1.6.x in performance, but slower due to the fact that v. 2.0 include some new features:

- Scoping
- Lexical
- Cover grammar

![reality](https://user-images.githubusercontent.com/31855118/51446148-e34f8100-1d48-11e9-8fe0-8da0804e33d3.png)

I will try to improve the performance in the end.

**Comment by axefrog** [comment]
Given the intent to investigate the potential for generating an optional runtime-extendable build as discussed in #292, perhaps any successes in that area would also make it possible for developers to opt out of certain unneeded features and achieve performance gains as a result?

**Comment by KFlash** [comment]
Ok. I will focus on finalizing. @axefrog @fkleuver Can you try to run Cherow 2.0 on Grammar branch and see if I screwed up something?

**Comment by axefrog** [comment]
Hey, sorry which is the "Grammar" branch? I don't see it listed,

**Comment by KFlash** [comment]
@axefrog It'sgone. Try the "finale_2_0" branch

**Comment by KFlash** [comment]
Current benchmark. Please note that we have full scoping and lexical checks running in the background. And this benchmark is with location tracking on.

![bench](https://user-images.githubusercontent.com/31855118/51873020-7b2b1b80-2396-11e9-8ce0-f8628f37ab57.png)

**Comment by KFlash** [comment]
@fkleuver Do you plan to optimize Cherow?

**Comment by KFlash** [comment]
Closing this as it seems like @fkleuver have no time to improve performance for now.

**Comment by KFlash** [comment]
@fkleuver Bringing this up again now that Meriyah is out. How's the performance plans for Cherow? You mentioned in this ticket you had plans to tweak the source?

![perf1](https://user-images.githubusercontent.com/31855118/57448876-103e8a00-728d-11e9-82bc-89dbf0569c16.png)

**Comment by KFlash** [comment]
@fkleuver I'm bringing this issue up again now that Meriyah is out. What's the plan for optimizations of the Cherow source code as mentioned in this issue ticket? 

![perf2](https://user-images.githubusercontent.com/31855118/57449088-9f4ba200-728d-11e9-858b-6906bc69b806.png)
