### ISSUE TITLE
Question about directly parsing code snippets

### ISSUE THREAD

**Issue by axefrog** [cherow/cherow#308]
Is there any recommended approach for use cases where there is a need to directly parse an expression or something else more specific than just "script" or "module"? I've got a lot of places in code where I'm compiling, for example, just a string template literal expression on its own, or a function declaration, for instance. Obviously it's just a matter of parsing it as a script and then extracting `program.body[0].expression` (or similar)`, but the extraneous wrapper objects feel redundant. It's not really a huge issue, but if there's a more efficient path I should be using, it'd be good to know.

**Comment by axefrog** [comment]
_By the way, as an off-topic aside, just want to offer a genuine thankyou for all the effort you put into this. It's a really fantastic tool, and I'm finding it absolutely indispensable._

**Comment by KFlash** [comment]
@axefrog Try `Cherow.parseExpressions('foo', { ranges: true }` and see if that helps you :)

**Comment by axefrog** [comment]
Just noticed `parseExpressions` returns a regular AST with a `Program` node at the root. Reopen?

**Comment by KFlash** [comment]
Hi. I think @KFlash intensions with this was to directly allow expression parsing and skip 90% of the ceremony of the parser (*which include statements and declarations parsing*)l and still stay true to the ESTree specs. In EStree the root node is always `program`, but if the main goal is to grab the expression AST nodes directly without doing any `program[0]` at the end - well I think I understand your problem, 

Would it help you if we add an `skipRoot` option? If enabled it will not return the `program` AST node?

**Comment by axefrog** [comment]
Ah cheers.

Ultimately this was only a suggestion to improve the ergonomics of scenarios involving direct/granular parsing of expressions. It's not a huge deal, but it may well be of use to others. My suggestion would be to simply eliminate allocation of the root by default. The benefit of the function is to provide an AST node that directly represents the parsed expression. If the root node is actually desired, then the main `parse` function is probably fine as-is because the only difference would be the additional `ExpressionStatement` node between the root and the expression node, and if that's the only difference in output, the value of a standalone `parseExpression` function seems questionable at best.

So yeah to sum up, I'd say personally you'd be better off eliminating the `skipRoot` option and just returning the expression node directly. I'd also suggest changing `parseExpressions` to `parseExpression` as the plural form seems to contradict the actual behaviour, in that only one root expression node is actually returned.

**Comment by axefrog** [comment]
Great, thanks!
