### ISSUE TITLE
Possible issue with FieldDefinition in estree.d.ts

### ISSUE THREAD

**Issue by axefrog** [cherow/cherow#311]
See:

- https://github.com/cherow/cherow/blob/dev/src/estree.ts#L25
- https://github.com/cherow/cherow/blob/dev/src/estree.ts#L376

```
// 25:
'FieldDefinition ': FieldDefinition;

// 376:
export interface FieldDefinition extends _Node<'FieldDefinition '> {
```

Is the trailing space supposed to be there?

**Comment by KFlash** [comment]
I really doubt the trailing space should be there :) I will fix this in my next push to this repo!

**Comment by KFlash** [comment]
Fixed in https://github.com/cherow/cherow/commit/adcf60f73e25c38834fcc55b1ebef16c697d94b9
