### ISSUE TITLE
Unexpected occurrence of property key name in property value literal

### ISSUE THREAD

**Issue by axefrog** [cherow/cherow#312]
I'm getting this problem on my local copy of cherow, which is the latest `cherow.esm.min.js` in the `dist` folder. It looks like it was last built about a day ago?

Test script for cherow to parse, centered on the line that causes the issue:
https://gist.github.com/axefrog/d9e746c5d5bd2feb1e5c8e159a634e0a#file-cherow-test-js-L35

Lines 32-42 in the code are:

```js
const Position = {
  type: 'ESTree:Node',
  id: 'Position',
  superType: null,
  fields: {
    line: { kind: 'primitive', optional: false, type: 'number' },
    column: { kind: 'primitive', optional: false, type: 'number' }
  },
  getField: (name) => Position.fields[name],
  isInstanceOf: (type) => type === 'Position',
};
```

The property initializer `superType: null` produces:

```json
{
  "type": "Property",
  "key": {
    "type": "Identifier",
    "name": "superType",
    "raw": "superType"
  },
  "value": {
    "type": "Literal",
    "value": null,
    "raw": "superType" // <---- ISSUE HERE
  },
  "kind": "init",
  "computed": false,
  "method": false,
  "shorthand": false
}
```

Another script of mine is processing the AST and made an incorrect assessment of the state of the literal because it looked at `value` and forgot to consider the possibility of a `null` literal value, which is when I noticed that the value of `raw` was showing up with the value that appears in the key.

**Comment by KFlash** [comment]
@axefrog This was an interesting find :) I never use the raw property myself and didn't test it very well it seems. A fix for this will land within 30 minutes. I already fixed it, but need to finalize something else here first.

**Comment by axefrog** [comment]
Thanks! :)
