### ISSUE TITLE
Missing ranges/loc - work in progress or bug?

### ISSUE THREAD

**Issue by axefrog** [cherow/cherow#313]
As per subject. Noticed that ranges and loc are not producing results throughout the AST. I'm guessing this is work in progress, but if not, consider this issue a bug report.

**Comment by KFlash** [comment]
It's a work in progress. Need to get the code working first so it's easier to know where to pass the range data as function arg without a need to change the logic many times.

**Comment by axefrog** [comment]
@KFlash Sounds reasonable to me!

**Comment by KFlash** [comment]
@axefrog You can consider this to be implemented very soon now. I just started and will focus on finishing this before finishing non-failing cases for arrows. After that I push to NPM and cleanup and performance fixes will land in 2.01 if I'm around at that time.

**Comment by axefrog** [comment]
No rush. Not urgent :)

**Comment by axefrog** [comment]
Excellent, thanks!

**Comment by KFlash** [comment]
Complete location tracking have been implemented.
