### ISSUE TITLE
circular dependency found

### ISSUE THREAD

**Issue by aladdin-add** [cherow/cherow#318]
```bash
$ npm run bundle

> cherow@1.6.8 bundle /Users/weiran/repo/github/cherow
> cross-env rimraf dist && node scripts/bundle.js

creating normal bundle
Circular dependency: src/lexer/common.ts -> src/lexer/identifier.ts -> src/lexer/common.ts
Circular dependency: src/parser/expressions.ts -> src/parser/pattern.ts -> src/parser/expressions.ts
Circular dependency: src/parser/statements.ts -> src/parser/expressions.ts -> src/parser/statements.ts
Circular dependency: src/parser/expressions.ts -> src/parser/directives.ts -> src/parser/expressions.ts
Circular dependency: src/parser/expressions.ts -> src/parser/jsx.ts -> src/parser/expressions.ts

```

it works fine -- just a warning.

**Comment by KFlash** [comment]
@aladdin-add As far as I understand your example is not taken from the Master branch. `directives.ts` and `jsx.ts` doesn't exist in the `parser` folder on the Master branch as [seen here](https://github.com/cherow/cherow/tree/master/src/parser), But you are right - the circular dependency exist.

**Comment by aladdin-add** [comment]
Thanks for this issue. This repository and project will no longer be maintained, please consider its successor: https://github.com/meriyah/meriyah 

Thanks for understanding and we apologize for any inconvenience!
