### ISSUE TITLE
Curious about the name

### ISSUE THREAD

**Issue by axefrog** [cherow/cherow#320]
A couple of unimportant questions:

1. How is "cherow" pronounced?
2. What does it mean?

:-)

**Comment by KFlash** [comment]
I answer you personally on this. I'm K.F. 

Chernow is a common family name, so remove the letter "n" and pronounce it like that. The name is the family name on my mentor and teacher that one day was robbed and killed.

**Comment by axefrog** [comment]
Ah right, sorry to hear that...!

So, like "shur-roe" or "chur-roe"?

**Comment by KFlash** [comment]
I would say more like "shur-roe"
