### ISSUE TITLE
55k unused table entries

### ISSUE THREAD

**Issue by KFlash** [cherow/cherow#321]
@fkleuver The table lookup in the scanner code contain around 60k entries and 97% of them are represented as `null`. And we are only using 3% of that table. The lower ASCII range - 0 - 128.

I can't see any performance gain in mixing unicode chars into it to replace the `null`.

And use of the Array() constructor can be ambiguous. [Read this](http://bonsaiden.github.io/JavaScript-Garden/#array.constructor)

To gain improved performance we should use `[ ]` for smaller, faster lookup.

But if you try to flatten the table lookup you will end up with 65k code lines :)

We need to think about both memory usage and file size here. 

I experimented with it, and V8 do optimize a switch statement if it's small enough, so if you take a look at my experimental code you see what I try to do.

Whatever we will do, this need to be solved somehow. I just mention it to you.

Somewhere I have a newer code where I solved some of this issues, but can't find it right now.

**Comment by fkleuver** [comment]
Ever tried a plain object literal lookup, with `charAt` instead of `charCodeAt`?

**Comment by KFlash** [comment]
I haven't tried it, but in my recent code that  I can't find on this laptop - I limited the lookup table to a minimum for one char punctuators and the char starting with other punctuators plus string, template etc. And if no match it throws an error. Also WS skipping was different.

**Comment by KFlash** [comment]
@fkleuver I found the code I searched for, but it's half-done. I will spend a few hours trying to finish what I tried to do before, then you can decide if you want to use it when you optimize Cherow.

This is the generated table 

```js
[
  1073741824,
  1073741824,
  1073741824,
  1073741824,
  1073741824,
  1073741824,
  1073741824,
  1073741824,
  1073741824,
  268435456,
  268435456,
  268435456,
  268435456,
  268435456,
  1073741824,
  1073741824,
  1073741824,
  1073741824,
  1073741824,
  1073741824,
  1073741824,
  1073741824,
  1073741824,
  1073741824,
  1073741824,
  1073741824,
  1073741824,
  1073741824,
  1073741824,
  1073741824,
  1073741824,
  1073741824,
  268435456,
  16842799,
  536936451,
  196728,
  1073741824,
  8456758,
  8455494,
  536936451,
  65549,
  18,
  8457016,
  25233713,
  20,
  25233714,
  1073741824,
  8456759,
  536936450,
  536936450,
  536936450,
  536936450,
  536936450,
  536936450,
  536936450,
  536936450,
  536936450,
  536936450,
  23,
  19,
  8456001,
  2097183,
  8456002,
  24,
  1073741824,
  196609,
  196609,
  196609,
  196609,
  196609,
  196609,
  196609,
  196609,
  196609,
  196609,
  196609,
  196609,
  196609,
  196609,
  196609,
  196609,
  196609,
  196609,
  196609,
  196609,
  196609,
  196609,
  196609,
  196609,
  196609,
  196609,
  1114133,
  196609,
  22,
  8455240,
  1073741824,
  4259840,
  196609,
  196609,
  196609,
  196609,
  196609,
  196609,
  196609,
  196609,
  196609,
  196609,
  196609,
  196609,
  196609,
  196609,
  196609,
  196609,
  196609,
  196609,
  196609,
  196609,
  196609,
  196609,
  196609,
  196609,
  196609,
  196609,
  1114126,
  8454983,
  17,
  16842800,
  1073741824
];
```

**Comment by KFlash** [comment]
I admit development is a sickness. I prefer to spend my days with a Rookworst, but still miss coding :)

**Comment by fkleuver** [comment]
> I prefer to spend my days with a Rookworst

Hard to argue with that :)

> but still miss coding

The two don't appear to be incompatible

**Comment by KFlash** [comment]
@fkleuver What I'm trying to archive I haven't seen this done in JS at all, so I'm not sure it's doable at all.
**But** I'm flatten everything into a infinite state machine with a 0-128 ASCII range lookup table.

The whitespace skipping is done separate, but still part of the lookup and the WS state are represented by bit masks to figure out if we have skipped anything at all.

So far so good, and the performance is improved :) But I'm litle worried when it comes to the punctuators. And I can't promise this can't be done either because JS have it's limitations :(

Here is a code snippet so you see how I'm thinking:

```js
export function skipWhiteSpace(state: ParserState, scanState: ScannerState): Token {

  // Advance as long as character is a WhiteSpace or LineTerminator.
  while (AsciiLookup[state.source.charCodeAt(state.index)] & CharType.WhiteSpace) {
    advanceOne(state);
    scanState |= ScannerState.SameLine;
    if (AsciiLookup[state.source.charCodeAt(state.index)] & CharType.LineTerminator) {
      switch (state.source.charCodeAt(state.index)) {
        /* line terminators */
        case Chars.CarriageReturn:
          scanState |= ScannerState.NewLine | ScannerState.LastIsCR;
          advanceNewline(state);
          break;

        case Chars.LineFeed:
          consumeLineFeed(state, (scanState & ScannerState.LastIsCR) !== 0);
          scanState = (scanState & ~ScannerState.LastIsCR) | ScannerState.NewLine;
          break;

        case Chars.LineSeparator:
        case Chars.ParagraphSeparator:
          scanState = (scanState & ~ScannerState.LastIsCR) | ScannerState.NewLine;
          advanceNewline(state);
          break;
      }
    }
  }
  // TODO: Move to mutual parser flags
  if (scanState & (ScannerState.SameLine | ScannerState.NewLine)) return Token.WhiteSpace;
  // We haven't skipped a shit, so it's invalid chars
  return Token.Invalid;
}
```

**Comment by fkleuver** [comment]
So you want good ol' C++ then? ;p https://mbebenita.github.io/WasmExplorer/
![image](https://user-images.githubusercontent.com/9655331/52549908-e7197500-2dd5-11e9-82b5-615c709e213b.png)

**Comment by KFlash** [comment]
Just now I prefer it yes. Lack of both macros and `goto` got me stuck. I can't get up again after WS skipping. Need to rethink :(
And my WhiteSpace and LineTerminar are each represented by one bit mask so I don't have to do the extra comparison. That works, but I need it to return to the lookup table so I can skip the comments and fix punctuators.

**Comment by KFlash** [comment]
@fkleuver When I develop I prefer to see results like this ` 13 passing (21ms)`

Got it working :)

**Comment by KFlash** [comment]
@fkleuver This will take some more time to fix, but one thing I'm trying to do is to eliminate the scanner overhead all JS parsers suffers from because it's normal to find spaces and tabs after newlines due to indentation and none is optimized for this. 
Second thing I did was to still keep the whitespace skipping into the scanner, but I somehow separated the loop body and token dispatch. They are no longer in the same switch.
Third thing is that I got a state tracker that let me know if we have skipped anything at all, or still on same line. 

It still require a lot of experimenting and testing, but the code below should give you an idea on how I'm thinking. 

Punctuators now also works as expected!

```js
export function nextToken(state: ParserState, context: Context): Token {
  let seekState: Seek = Seek.None;
  do {
    const token = tableLookup[state.source.charCodeAt(state.index)];

    switch (token) {
      case Token.LeftParen:
      case Token.RightParen:
      case Token.LeftBrace:
      case Token.RightBrace:
      case Token.LeftBracket:
      case Token.RightBracket:
      case Token.QuestionMark:
      case Token.Colon:
      case Token.Semicolon:
      case Token.Comma:
      case Token.Invalid:
        advanceOne(state);
        return token;

      case Token.WhiteSpace:
      seekState = skipWhiteSpace(state, context);
      default: // TODO
    }

    seekState = skipWhiteSpace(state, context);
  } while (seekState !== Seek.None);

  return Token.EndOfSource;
}
```

**Comment by KFlash** [comment]
@fkleuver I got this working, but I need to improve the WS skipping big time, but for now I'm working on getting the experimental code working as before...

What it does is to use a lookup table (*0 - 128 ASCII range*) and a switch statement. 

Instead of
```js
  // `0`...`9`
        case Chars.Zero: case Chars.One: case Chars.Two: case Chars.Three: case Chars.Four:
        case Chars.Five: case Chars.Six: case Chars.Seven: case Chars.Eight: case Chars.Nine:
```
We simply can do this
```
case Token.NumericLiteral: 
```
Identifiers and everything else is done the same way.

**Current state**: `202 passing (94ms)`

**Comment by KFlash** [comment]
This is the numeric literal benchmark. You see the difference between 2.0 and my experiment?

Let's not mention WS skipping yet ;)

![improved](https://user-images.githubusercontent.com/31855118/52602208-b3ede900-2e9c-11e9-91b4-63642855a1db.png)

**Comment by KFlash** [comment]
@fkleuver As seen from this benchmark and if you do a comparison with the one to the one above you clearly see that whitespace skipping is a bottleneck just now. But I will fix it :)

![ws](https://user-images.githubusercontent.com/31855118/52602450-b43ab400-2e9d-11e9-935d-d6e8219190be.png)

And this is the benchmark for punctuator lookup - simple array

![punc](https://user-images.githubusercontent.com/31855118/52602545-0d0a4c80-2e9e-11e9-98e5-761263f8a375.png)

Not that big difference. Only 96% improvement over Cherow 2.0.

**Note** This is just for the lexer. It will act different during a parse and in RL usage.

**Comment by KFlash** [comment]
@fkleuver I forgot the identifier scanning benchmark. As you see it's a little faster than Cherow 2.0, but not that much. I already spotted a few places I can improve

![ident](https://user-images.githubusercontent.com/31855118/52602936-750d6280-2e9f-11e9-857b-d19d925a7da4.png)

**Comment by KFlash** [comment]
@fkleuver My experimental code now works the same as before, but give me at least a few more days to improve some of this mess. Than you can choose if you want to use it for 2.0

![done](https://user-images.githubusercontent.com/31855118/52605075-43e56000-2ea8-11e9-8e51-f0303d6c65e3.png)

**Comment by KFlash** [comment]
@fkleuver After I push a unpolished new experimental code, could you profile it so it could be improved?  BTW. Did you look at the experimental code?

My thinking now is easy. When you request for a new token in the stream, the code looks like this:

```js
export function nextToken(state: ParserState, context: Context): Token {
  const type = ScannerFlags.None;
  return (state.token = (scanSingleToken(state, context, type) as Token));
}
```
The `type` returns the current scanner type. E.g newline. This let us set the newline flag only once on the mutual parser flag instead of multiple times we are skipping LT as before.

Doing it this way should also improve tokenizing. Now that part is taken out of the hot loop, and return the token to the function you see above.

This to mention a few benefits with this. The lexer itself have become a infinite state machine with one set of bit masks that we need to pass to comments etc. It's used for several optimization tricks and to keep track of WS skipping. One change here, and most of the tests breaks. This should also help fixing the HTML close issue I think we suffer from if not J.K fixed it.

If you have seen the experimental code you know now that the numeric kind types are hooked on the mutual parser flags, and we are forced to use member access. This is now part of the scanner flags so no member access at all.

I'm soon to show you an early prototype, but hopefully you can profile it before I finish and optimize whitespace skipping.

Here is the latest benchmark. I improved the perf a litle compared to above, but I have no idea what's going on with the `.12123`

![new](https://user-images.githubusercontent.com/31855118/52612648-adc03280-2ec5-11e9-99b2-4dd98a5d8aa2.png)

**Comment by KFlash** [comment]
@fkleuver I'm closing this. You can find a temporary experimental solution in the experimental branch.

Can you try to profile it?  I'm already aware of a few things to fix, plus I need to optimize for WS!

**NOTE:** Because of the `scannerFlags` are passed around everywhere, you no longer need extra bitset or a comment type enum. Just move it on the `scannerFlags` to simplify and you can collect comments as before.

I'm gone now! I need to find me a Rookworst and relax :)

**Comment by KFlash** [comment]
For the record. We ended up with 55k unused entries because someone modified the table so we got this code:  `const table = new Array(0xffff).fill(scanMaybeIdentifier, 0x80)`. 
What we actually wanted was a 128 entry table, and correct code for that is 
`const table = new Array(128).fill(impossible)`.
