### ISSUE TITLE
Unexpected token "get"

### ISSUE THREAD

**Issue by nchanged** [cherow/cherow#328]
The error below happens when I try to parse `lodash-es` modules with `cherow@1.6.9`
`cherow@next` isn't available (I can't install it)

```
import get from './get.js';
```

```js
cherow.parseScript(contents, {
    module: true,
    next: true,
    experimental: true,
  });
```

**Expected behavior:**

Parsed correctly.
**Actual behavior:**

```
(node:26943) UnhandledPromiseRejectionWarning: SyntaxError: Line 1, column 7: Unexpected token 'get'
    at constructError (cherow/dist/umd/cherow.js:5625:21)
    at report (cherow/dist/umd/cherow.js:5664:7)
    at parseImportClause (cherow/dist/umd/cherow.js:6815:15)
    at parseImportDeclaration (cherow/dist/umd/cherow.js:6765:24)
    at parseModuleItem (cherow/dist/umd/cherow.js:6585:26)
    at parseModuleItemList (cherow/dist/umd/cherow.js:6561:15)
    at parseSource (cherow/dist/umd/cherow.js:7038:11)
    at Object.parseScript (cherow/dist/umd/cherow.js:7117:14)
```

I am the founder of `FuseBox` and I get to see all kind of weird cases, since FuseBox is a bundler, I feel that cherow isn't ready for production just yet, however, I have big hopes for it. I will keep testing it and submit issues. Thanks guys!

UPD.

I guess the only reserved words for imports should be `function` `class` `let` `var` `const` `for` `in` e.t.c but definitely not `get` nor `set`

**Comment by KFlash** [comment]
@fkleuver You take a look at this? I think the best solution is that you finish v. 2.0 and push to NPM because this issues have already been solved on Master.

**Comment by nchanged** [comment]
Please do so, I will start testing it extensively, I have around 600 tests for now to run it through.

**Comment by KFlash** [comment]
@nchanged I retired 2 months ago, and back then @fkleuver should continue this project, but until now 2.0  haven't been released yet and I'm not sure about his schedule. Sometimes I look at the project, but see no progress so don't expect too much to happen I guess.

Regarding `@next` is wrong. You should use  `@dev`. Example `npm i cherow@1.6.8-dev.20190406`

**Comment by fkleuver** [comment]
@nchanged The master branch is published to npm every night under `@dev`. `npm i cherow@dev` will do the trick. Let us know if that works.

@KFlash Yes, things are not going according to plan. I can only do one thing at a time, sorry.

**Comment by KFlash** [comment]
@fkleuver Maybe next year? Anyway. To help you out finish this I started to port my private parser code to open source. You can find it [here](https://github.com/meriyah/meriyah), Don't expect miracles within short time, but the private code works and kicks ass. So you can "borrow" ideas from there maybe? Meriyah will be gone soon as I'm done porting the code and can merge it *hopefully* into Cherow code base.

**Comment by nchanged** [comment]
I just wanted to know, can I expect cherow 2.0 to be published within 2 months?

**Comment by KFlash** [comment]
@nchanged With JSX extension? I think @fkleuver is the best to answer that question. But if not I may have another option for you within 1 month I guess.

**Comment by KFlash** [comment]
Closing this as I doubt @fkleuver can publish Cherow 2.0 within short time. 

Try the [meriyah parser](https://github.com/meriyah/meriyah) while whiting for NPM release of 2.0.
