### ISSUE TITLE
onComment doesn't seem to work

### ISSUE THREAD

**Issue by br0p0p** [cherow/cherow#329]
Commit in yarn.lock: `7c5e34fce297f152a6f7853dcc9fe2f9e1b36ab8`

**Code**

```js
const cherow = require('cherow');

const testScript = `
/* Test comment */
// Test module
module.exports = {
    // Test comment b
    b: true,
    // Test comment c
    c : 'constant',
    // Test comment num
    num: 1234,
    // Test comment obj
    obj: {first: 1, second: 2},
};
`;

let comments = [];

cherow.parse(testScript, {
    onComment: comments
});

cherow.parse(testScript, {
    onComment: comment => {
        console.log('comment:', comment);
    }
});

console.log('comments:', comments);
```

**Expected behavior:**
- `comments` to contain an entry for each comment
- log output for every comment

**Actual behavior:**
- `comments` is empty
- no log output except the final `comments: []`

**Comment by KFlash** [comment]
Only works with a callback function atm. If you are using master branch?

@fkleuver Could you look into this?

**Comment by br0p0p** [comment]
@KFlash cool, that works for me. Thanks!
