### ISSUE TITLE
Should decorators be implemented?

### ISSUE THREAD

**Issue by KFlash** [cherow/cherow#330]
@fkleuver Is this needed? You mentioned it in [this](https://github.com/cherow/cherow/issues/316) issue ticket.  In any case it has to land in 2.1 after you push 2.0 to NPM.

**Comment by ljharb** [comment]
No, not yet. Decorators are still in a lot of flux.

**Comment by KFlash** [comment]
Any idea when the specs are ready for an implementation? I implemented decorators in my private project, and yes I ran into several funny scenarios.

**Comment by ljharb** [comment]
Stage 3 is usually when it’s time for implementation; they’re still at stage 2.
