### ISSUE TITLE
Prepare and publish Cherow 2.0 to NPM

### ISSUE THREAD

**Issue by KFlash** [cherow/cherow#332]
Publish master branch to NPM

- [ ] Optimize tweak / code

- [ ] Fix https://github.com/cherow/cherow/issues/292

- [ ] Extract the scope logic

cc / @fkleuver

**Comment by KFlash** [comment]
@fkleuver Can you try to look into the performance stuff?  There are room for optimization.

Look at this ` 60557 passing (2s) vs 26368 passing (4s) for Cherow. `.  Private code runs twice as much tests in half of the time Cherow execute them in! Can you fix this somehow?

**Comment by KFlash** [comment]
cc/ @fkleuver ?

**Comment by KFlash** [comment]
cc/ @fkleuver ?

**Comment by KFlash** [comment]
cc/ @fkleuver Any NPM progress?

**Comment by KFlash** [comment]
cc/ @fkleuver Any NPM progress? Looks like Cherow 2.x is put on hold until public release...

**Comment by KFlash** [comment]
While we waiting for @fkleuver to publish 2.0, [Meriyah](https://github.com/meriyah/meriyah/commits/master) can be used to parse your JS code. 

**Note:** Meriyah is 100% spec compat, but a retirement project and it progress slowly

**Comment by KFlash** [comment]
@fkleuver ?

**Comment by KFlash** [comment]
@fkleuver You don't need to extract the scope logic I think when you decide to publish v. 2.0. You can hide it behind a flag. However you need to solve the arrow scoping somehow.
It's a little tricky to use a flag for this too, but you figure it out :) As a reference you can look at my retirement code. I implemented lexical scoping there hidden behind a flag (*not published that code yet*)

**Comment by KFlash** [comment]
@fkleuver You can simplify the scoping logic further if you merge both hoisted function decl and class decl into func decl and class decl and use bit masks to track. I have done it, tried it and it works :)

**Comment by KFlash** [comment]
@fkleuver The [Meriyah REPL](https://meriyah.github.io/meriyah/) is here and you can see that the scoping can be turned on and off :)

**Comment by KFlash** [comment]
@fkleuver You may as well refactor loc tracking in Cherow and avoid member access all together in the hot loop. Little tricky, but it should work. And if you manage to fix that, well you wouldn't need to calculate `column++;` on everywhere. 

I also noticed perf regression when it comes to loc tracking. Maybe you should improve it?

**Comment by KFlash** [comment]
@fkleuver Soon 4 months now since this should be release, so I think you have no time? I will update the readme then and let people know this parser is put on hold until you find time to finish your tasks.

**Comment by fkleuver** [comment]
@KFlash 
Since things don't seem to be going anywhere anytime soon for various reasons, I think it's best I completely withdraw from this project.

You are also working on a new parser which supposedly is already better, faster and more robust than Cherow so I'm not sure why you're trying to have me finish and maintain cherow (and in a certain sense "compete" with you - seems like a blast if I am retired like you are, but unfortunately I am not ;-)). 

I apologize for poorly managing expectations in the past half year. Lesson learned on my part. Two massively ambitious open source projects at the same time is too much for someone with a job.

**Comment by KFlash** [comment]
Hi. Long time :) I understand your situation, and I had plans that Cherow could "stay alive" because some people are using it. Hard to get people to "swap" even if the other parser are an huge improvement. Maybe you could put up a "not maintained" on NPM and readme? 

For various reasons my work on Cherow also stopped, and as you mentioned I'm working on or was working on another parser. That parser is feature complete soon as my last PR have landed - JSX implementation.

Anyway. Good luck with your future projects, and if you feel boring one day and want to tweak some bit masks, why not take a look at the Meriyah source. It's not fully optimized yet.
No one will swing the whip and force you, but you have a sharp brain when it comes to those things :)

**Comment by KFlash** [comment]
@fkleuver If you find time - try the [Meriyah REPL](https://meriyah.github.io/meriyah/). I'm done with that project now and moved on to TS parsing :)

**Comment by aladdin-add** [comment]
Thanks for this issue. This repository and project will no longer be maintained, please consider its successor: https://github.com/meriyah/meriyah 

Thanks for understanding and we apologize for any inconvenience!
