### ISSUE TITLE
We found a potential security vulnerability in one of your dependencies.

### ISSUE THREAD

**Issue by aladdin-add** [cherow/cherow#335]
it was found by github alerts:
![image](https://user-images.githubusercontent.com/13050025/57498276-cf3a8a00-730d-11e9-8c05-b4cee7f2b2d9.png)
![image](https://user-images.githubusercontent.com/13050025/57498332-0610a000-730e-11e9-86c3-bfded4b0189b.png)

**Comment by g-plane** [comment]
I think we just use jQuery in GitHub pages, so we can upgrade it.

**Comment by KFlash** [comment]
Who are willing to take a stab at it? And also Master branch should have been pushed to NPM. But @fkleuver seems to be out of radio range or switched off atm :)

**Comment by aladdin-add** [comment]
I'm willing to, but not atm. maybe the following 2~3 days.
