### ISSUE TITLE
Speed comparison page stop working because external script request failed

### ISSUE THREAD

**Issue by golopot** [cherow/cherow#336]
**Code**
1. Navigate to https://cherow.github.io/cherow/performance/ .
2. Click "Run speed comparison with warm JIT" .

**Expected behavior:**
Benchmark starts.

Aside from waiting for https://wzrd.in/ fixing their problems. This page can add a try catch around each parser run so that a failing run does not affect other run.

**Comment by aladdin-add** [comment]
Thanks for this issue. This repository and project will no longer be maintained, please consider its successor: https://github.com/meriyah/meriyah 

Thanks for understanding and we apologize for any inconvenience!
