### ISSUE TITLE
Bug: non-method object literal property marked as 'method' when following method property

### ISSUE THREAD

**Issue by axefrog** [cherow/cherow#338]
**Code**

```js
const a = {
  foo () { },
  '@': 1,
}
```

Cherow (all versions) parses the second property with `method: true`. This only occurs when preceded by a method property.

@KFlash Sorry, my intent is to test with meriyah, but in a hurry at the moment and haven't had a chance to clone/build meriyah, which naturally is necessary without a demo site like Cherow has.

**Comment by KFlash** [comment]
I will look into it. Not sure why it's happens?

@axefrog Do not worry too much about meriyah :) It was my private reference parser that I made public and also what I used to validate output with Cherow before. That parser is more spec compat than the Tes262 suite.  And I just parsed your example with meriyah, and I guess this is the correct result you want?

```ts
{
                                "type": "Property",
                                "key": {
                                    "type": "Literal",
                                    "value": "@"
                                },
                                "value": {
                                    "type": "Literal",
                                    "value": 1
                                },
                                "kind": "init",
                                "computed": false,
                                "method": false,
                                "shorthand": false
                            }
```

I will try to fix it in Cherow.

**Comment by axefrog** [comment]
@KFlash yep, looks good. cheers!
