### ISSUE TITLE
ECMAScript® 2018 in the README should be 2017

### ISSUE THREAD

**Issue by marcoemrich** [cherow/cherow#34]
The READM state "Full support for ECMAScript® 2018 (ECMA-262 8th Edition)". I think it should read "ECMAScript® 2017" not 2018, since 2017 matches with the 8 Edition and 2018 hasn't been ratified yet.

**Comment by KFlash** [comment]
Hi. Agree. It was added like this because of the `Next` support. Will change this.

**Comment by KFlash** [comment]
Closing. Updated readme.
