### ISSUE TITLE
Class fields - this should be working right?

### ISSUE THREAD

**Issue by axefrog** [cherow/cherow#340]
**Code**

```js
Cherow.parse(`class Foo { x = 1; }`, { next: true, experimental: true })
```

```
SyntaxError: Expected ( (1:15)
class Foo { x = 1; }
               ^
```

Just wondering if this is a bug or if I'm doing something wrong...

Note: I have tested it with some of the other samples on https://github.com/tc39/proposal-class-fields and I'm getting errors for all of them. It seems like the `next` option is being ignored by Cherow.

**Comment by KFlash** [comment]
Class fields are at Stage 3 and haven't been implemented on Cherow *yet*. That's why you get this error.

**Comment by axefrog** [comment]
@KFlash Got it. I misinterpreted the README as implying blanket support for stage 3 proposals, and given the increasing mainstream browser support for class fields, and corresponding increase in adoption that I've been noticing, I made the assumption without thinking too much about it.
