### ISSUE TITLE
JSX suppport with 2.0

### ISSUE THREAD

**Issue by nchanged** [cherow/cherow#341]
Any ETA on when it will be implemented? It doesn't seem to work with `1.6.8-dev.20190514`

@fkleuver

**Comment by KFlash** [comment]
@fkleuver ?? Any update on this?

**Comment by KFlash** [comment]
@fkleuver Whats the state on this?

**Comment by KFlash** [comment]
@fkleuver If you one day choose to implement JSX support for Cherow 2.0, be aware that there is an issue with JSX fragments in Cherow 1.6.1. `openingElement` is used instead of `openingFragment` on the `JSXFragment` AST node. 

This has to be corrected.

**Comment by aladdin-add** [comment]
Thanks for this issue. This repository and project will no longer be maintained, please consider its successor: https://github.com/meriyah/meriyah 

Thanks for understanding and we apologize for any inconvenience!
