### ISSUE TITLE
Failed to parse module

### ISSUE THREAD

**Issue by nchanged** [cherow/cherow#342]
I am attaching `medium-zoom.esm.js` file which cannot be parsed.
I don't have much time (unfortunately) to investigate it myself. All I can say that it's a valid js and works with acorn.

[medium-zoom.esm.js.zip](https://github.com/cherow/cherow/files/3176928/medium-zoom.esm.js.zip)

@fkleuver @KFlash

**Comment by KFlash** [comment]
@nchanged I guess you are doing something wrong in your end? The attached code parsed just fine with the [online demo](https://cherow.github.io/cherow/?code=%2F*!%20medium-zoom%201.0.4%20%7C%20MIT%20License%20%7C%20https%3A%2F%2Fgithub.com%2Ffrancoischalifour%2Fmedium-zoom%20*%2Fvar%20_extends%3DObject.assign%7C%7Cfunction(a)%7Bfor(var%20b%2Cc%3D1%3Bc%3Carguments.length%3Bc%2B%2B)for(var%20d%20in%20b%3Darguments%5Bc%5D%2Cb)Object.prototype.hasOwnProperty.call(b%2Cd)%26%26(a%5Bd%5D%3Db%5Bd%5D)%3Breturn%20a%7D%2CisSupported%3Dfunction(a)%7Breturn'IMG'%3D%3D%3Da.tagName%7D%2CisNodeList%3Dfunction(a)%7Breturn%20NodeList.prototype.isPrototypeOf(a)%7D%2CisNode%3Dfunction(a)%7Breturn%20a%26%261%3D%3D%3Da.nodeType%7D%2CisSvg%3Dfunction(a)%7Bvar%20b%3Da.currentSrc%7C%7Ca.src%3Breturn'.svg'%3D%3D%3Db.substr(-4).toLowerCase()%7D%2CgetImagesFromSelector%3Dfunction(a)%7Btry%7Breturn%20Array.isArray(a)%3Fa.filter(isSupported)%3AisNodeList(a)%3F%5B%5D.slice.call(a).filter(isSupported)%3AisNode(a)%3F%5Ba%5D.filter(isSupported)%3A'string'%3D%3Dtypeof%20a%3F%5B%5D.slice.call(document.querySelectorAll(a)).filter(isSupported)%3A%5B%5D%7Dcatch(a)%7Bthrow%20new%20TypeError('The%20provided%20selector%20is%20invalid.%5CnExpects%20a%20CSS%20selector%2C%20a%20Node%20element%2C%20a%20NodeList%20or%20an%20array.%5CnSee%3A%20https%3A%2F%2Fgithub.com%2Ffrancoischalifour%2Fmedium-zoom')%7D%7D%2CcreateOverlay%3Dfunction(a)%7Bvar%20b%3Ddocument.createElement('div')%3Breturn%20b.classList.add('medium-zoom-overlay')%2Cb.style.background%3Da%2Cb%7D%2CcloneTarget%3Dfunction(a)%7Bvar%20b%3Da.getBoundingClientRect()%2Cc%3Db.top%2Cd%3Db.left%2Ce%3Db.width%2Cf%3Db.height%2Cg%3Da.cloneNode()%2Ch%3Dwindow.pageYOffset%7C%7Cdocument.documentElement.scrollTop%7C%7Cdocument.body.scrollTop%7C%7C0%2Ci%3Dwindow.pageXOffset%7C%7Cdocument.documentElement.scrollLeft%7C%7Cdocument.body.scrollLeft%7C%7C0%3Breturn%20g.removeAttribute('id')%2Cg.style.position%3D'absolute'%2Cg.style.top%3Dc%2Bh%2B'px'%2Cg.style.left%3Dd%2Bi%2B'px'%2Cg.style.width%3De%2B'px'%2Cg.style.height%3Df%2B'px'%2Cg.style.transform%3D''%2Cg%7D%2CcreateCustomEvent%3Dfunction(a%2Cb)%7Bvar%20c%3D_extends(%7Bbubbles%3A!1%2Ccancelable%3A!1%2Cdetail%3Avoid%200%7D%2Cb)%3Bif('function'%3D%3Dtypeof%20window.CustomEvent)return%20new%20CustomEvent(a%2Cc)%3Bvar%20d%3Ddocument.createEvent('CustomEvent')%3Breturn%20d.initCustomEvent(a%2Cc.bubbles%2Cc.cancelable%2Cc.detail)%2Cd%7D%2CmediumZoom%3Dfunction%20a(b)%7Bvar%20c%3D1%3Carguments.length%26%26arguments%5B1%5D!%3D%3Dvoid%200%3Farguments%5B1%5D%3A%7B%7D%2Cd%3Dwindow.Promise%7C%7Cfunction(a)%7Bfunction%20b()%7B%7Da(b%2Cb)%7D%2Ce%3Dfunction(a)%7Bvar%20b%3Da.target%3Breturn%20b%3D%3D%3Dx%3Fvoid%20n()%3Avoid(-1%3D%3D%3Dr.indexOf(b)%7C%7Co(%7Btarget%3Ab%7D))%7D%2Cf%3Dfunction()%7Bif(!t%26%26w.original)%7Bvar%20a%3Dwindow.pageYOffset%7C%7Cdocument.documentElement.scrollTop%7C%7Cdocument.body.scrollTop%7C%7C0%3BMath.abs(u-a)%3Ev.scrollOffset%26%26setTimeout(n%2C150)%7D%7D%2Cg%3Dfunction()%7Bvar%20a%3D0%3Carguments.length%26%26void%200!%3D%3Darguments%5B0%5D%3Farguments%5B0%5D%3A%7B%7D%2Cb%3Da%3Bif(a.background%26%26(x.style.background%3Da.background)%2Ca.container%26%26a.container%20instanceof%20Object%26%26(b.container%3D_extends(%7B%7D%2Cv.container%2Ca.container))%2Ca.template)%7Bvar%20c%3DisNode(a.template)%3Fa.template%3Adocument.querySelector(a.template)%3Bb.template%3Dc%7Dreturn%20v%3D_extends(%7B%7D%2Cv%2Cb)%2Cr.forEach(function(a)%7Ba.dispatchEvent(createCustomEvent('medium-zoom%3Aupdate'%2C%7Bdetail%3A%7Bzoom%3Ay%7D%7D))%7D)%2Cy%7D%2Ch%3Dfunction()%7Bvar%20b%3D0%3Carguments.length%26%26arguments%5B0%5D!%3D%3Dvoid%200%3Farguments%5B0%5D%3A%7B%7D%3Breturn%20a(_extends(%7B%7D%2Cv%2Cb))%7D%2Ci%3Dfunction()%7Bfor(var%20a%3Darguments.length%2Cb%3DArray(a)%2Cc%3D0%3Bc%3Ca%3Bc%2B%2B)b%5Bc%5D%3Darguments%5Bc%5D%3Bvar%20d%3Db.reduce(function(a%2Cb)%7Breturn%5B%5D.concat(a%2CgetImagesFromSelector(b))%7D%2C%5B%5D)%3Breturn%20d.filter(function(a)%7Breturn-1%3D%3D%3Dr.indexOf(a)%7D).forEach(function(a)%7Br.push(a)%2Ca.classList.add('medium-zoom-image')%7D)%2Cs.forEach(function(a)%7Bvar%20b%3Da.type%2Cc%3Da.listener%2Ce%3Da.options%3Bd.forEach(function(a)%7Ba.addEventListener(b%2Cc%2Ce)%7D)%7D)%2Cy%7D%2Cj%3Dfunction()%7Bfor(var%20a%3Darguments.length%2Cb%3DArray(a)%2Cc%3D0%3Bc%3Ca%3Bc%2B%2B)b%5Bc%5D%3Darguments%5Bc%5D%3Bw.zoomed%26%26n()%3Bvar%20d%3D0%3Cb.length%3Fb.reduce(function(a%2Cb)%7Breturn%5B%5D.concat(a%2CgetImagesFromSelector(b))%7D%2C%5B%5D)%3Ar%3Breturn%20d.forEach(function(a)%7Ba.classList.remove('medium-zoom-image')%2Ca.dispatchEvent(createCustomEvent('medium-zoom%3Adetach'%2C%7Bdetail%3A%7Bzoom%3Ay%7D%7D))%7D)%2Cr%3Dr.filter(function(a)%7Breturn-1%3D%3D%3Dd.indexOf(a)%7D)%2Cy%7D%2Ck%3Dfunction(a%2Cb)%7Bvar%20c%3D2%3Carguments.length%26%26void%200!%3D%3Darguments%5B2%5D%3Farguments%5B2%5D%3A%7B%7D%3Breturn%20r.forEach(function(d)%7Bd.addEventListener('medium-zoom%3A'%2Ba%2Cb%2Cc)%7D)%2Cs.push(%7Btype%3A'medium-zoom%3A'%2Ba%2Clistener%3Ab%2Coptions%3Ac%7D)%2Cy%7D%2Cl%3Dfunction(a%2Cb)%7Bvar%20c%3D2%3Carguments.length%26%26void%200!%3D%3Darguments%5B2%5D%3Farguments%5B2%5D%3A%7B%7D%3Breturn%20r.forEach(function(d)%7Bd.removeEventListener('medium-zoom%3A'%2Ba%2Cb%2Cc)%7D)%2Cs%3Ds.filter(function(c)%7Breturn%20c.type!%3D%3D'medium-zoom%3A'%2Ba%7C%7Cc.listener.toString()!%3D%3Db.toString()%7D)%2Cy%7D%2Cm%3Dfunction()%7Bvar%20a%3D0%3Carguments.length%26%26arguments%5B0%5D!%3D%3Dvoid%200%3Farguments%5B0%5D%3A%7B%7D%2Cb%3Da.target%2Cc%3Dfunction()%7Bvar%20a%3DMath.min%2Cb%3D%7Bwidth%3Adocument.documentElement.clientWidth%2Cheight%3Adocument.documentElement.clientHeight%2Cleft%3A0%2Ctop%3A0%2Cright%3A0%2Cbottom%3A0%7D%2Cc%3Dvoid%200%2Cd%3Dvoid%200%3Bif(v.container)if(v.container%20instanceof%20Object)b%3D_extends(%7B%7D%2Cb%2Cv.container)%2Cc%3Db.width-b.left-b.right-2*v.margin%2Cd%3Db.height-b.top-b.bottom-2*v.margin%3Belse%7Bvar%20e%3DisNode(v.container)%3Fv.container%3Adocument.querySelector(v.container)%2Cf%3De.getBoundingClientRect()%2Cg%3Df.width%2Ch%3Df.height%2Ci%3Df.left%2Cj%3Df.top%3Bb%3D_extends(%7B%7D%2Cb%2C%7Bwidth%3Ag%2Cheight%3Ah%2Cleft%3Ai%2Ctop%3Aj%7D)%7Dc%3Dc%7C%7Cb.width-2*v.margin%2Cd%3Dd%7C%7Cb.height-2*v.margin%3Bvar%20k%3Dw.zoomedHd%7C%7Cw.original%2Cl%3DisSvg(k)%3Fc%3Ak.naturalWidth%7C%7Cc%2Cm%3DisSvg(k)%3Fd%3Ak.naturalHeight%7C%7Cd%2Cn%3Dk.getBoundingClientRect()%2Co%3Dn.top%2Cp%3Dn.left%2Cq%3Dn.width%2Cr%3Dn.height%2Cs%3Da(l%2Cc)%2Fq%2Ct%3Da(m%2Cd)%2Fr%2Cu%3Da(s%2Ct)%2Cx%3D(-p%2B(c-q)%2F2%2Bv.margin%2Bb.left)%2Fu%2Cy%3D(-o%2B(d-r)%2F2%2Bv.margin%2Bb.top)%2Fu%2Cz%3D'scale('%2Bu%2B')%20translate3d('%2Bx%2B'px%2C%20'%2By%2B'px%2C%200)'%3Bw.zoomed.style.transform%3Dz%2Cw.zoomedHd%26%26(w.zoomedHd.style.transform%3Dz)%7D%3Breturn%20new%20d(function(a)%7Bif(b%26%26-1%3D%3D%3Dr.indexOf(b))return%20void%20a(y)%3Bif(w.zoomed)return%20void%20a(y)%3Bif(b)w.original%3Db%3Belse%20if(0%3Cr.length)%7Bvar%20d%3Dr%3Bw.original%3Dd%5B0%5D%7Delse%20return%20void%20a(y)%3Bif(w.original.dispatchEvent(createCustomEvent('medium-zoom%3Aopen'%2C%7Bdetail%3A%7Bzoom%3Ay%7D%7D))%2Cu%3Dwindow.pageYOffset%7C%7Cdocument.documentElement.scrollTop%7C%7Cdocument.body.scrollTop%7C%7C0%2Ct%3D!0%2Cw.zoomed%3DcloneTarget(w.original)%2Cdocument.body.appendChild(x)%2Cv.template)%7Bvar%20e%3DisNode(v.template)%3Fv.template%3Adocument.querySelector(v.template)%3Bw.template%3Ddocument.createElement('div')%2Cw.template.appendChild(e.content.cloneNode(!0))%2Cdocument.body.appendChild(w.template)%7Dif(document.body.appendChild(w.zoomed)%2Cwindow.requestAnimationFrame(function()%7Bdocument.body.classList.add('medium-zoom--opened')%7D)%2Cw.original.classList.add('medium-zoom-image--hidden')%2Cw.zoomed.classList.add('medium-zoom-image--opened')%2Cw.zoomed.addEventListener('click'%2Cn)%2Cw.zoomed.addEventListener('transitionend'%2Cfunction%20b()%7Bt%3D!1%2Cw.zoomed.removeEventListener('transitionend'%2Cb)%2Cw.original.dispatchEvent(createCustomEvent('medium-zoom%3Aopened'%2C%7Bdetail%3A%7Bzoom%3Ay%7D%7D))%2Ca(y)%7D)%2Cw.original.getAttribute('data-zoom-src'))%7Bw.zoomedHd%3Dw.zoomed.cloneNode()%2Cw.zoomedHd.removeAttribute('srcset')%2Cw.zoomedHd.removeAttribute('sizes')%2Cw.zoomedHd.src%3Dw.zoomed.getAttribute('data-zoom-src')%2Cw.zoomedHd.onerror%3Dfunction()%7BclearInterval(f)%2Cconsole.warn('Unable%20to%20reach%20the%20zoom%20image%20target%20'%2Bw.zoomedHd.src)%2Cw.zoomedHd%3Dnull%2Cc()%7D%3Bvar%20f%3DsetInterval(function()%7Bw.zoomedHd.complete%26%26(clearInterval(f)%2Cw.zoomedHd.classList.add('medium-zoom-image--opened')%2Cw.zoomedHd.addEventListener('click'%2Cn)%2Cdocument.body.appendChild(w.zoomedHd)%2Cc())%7D%2C10)%7Delse%20if(w.original.hasAttribute('srcset'))%7Bw.zoomedHd%3Dw.zoomed.cloneNode()%2Cw.zoomedHd.removeAttribute('sizes')%3Bvar%20g%3Dw.zoomedHd.addEventListener('load'%2Cfunction()%7Bw.zoomedHd.removeEventListener('load'%2Cg)%2Cw.zoomedHd.classList.add('medium-zoom-image--opened')%2Cw.zoomedHd.addEventListener('click'%2Cn)%2Cdocument.body.appendChild(w.zoomedHd)%2Cc()%7D)%7Delse%20c()%7D)%7D%2Cn%3Dfunction()%7Breturn%20new%20d(function(a)%7Bif(t%7C%7C!w.original)return%20void%20a(y)%3Bt%3D!0%2Cdocument.body.classList.remove('medium-zoom--opened')%2Cw.zoomed.style.transform%3D''%2Cw.zoomedHd%26%26(w.zoomedHd.style.transform%3D'')%2Cw.template%26%26(w.template.style.transition%3D'opacity%20150ms'%2Cw.template.style.opacity%3D0)%2Cw.original.dispatchEvent(createCustomEvent('medium-zoom%3Aclose'%2C%7Bdetail%3A%7Bzoom%3Ay%7D%7D))%2Cw.zoomed.addEventListener('transitionend'%2Cfunction%20b()%7Bw.original.classList.remove('medium-zoom-image--hidden')%2Cdocument.body.removeChild(w.zoomed)%2Cw.zoomedHd%26%26document.body.removeChild(w.zoomedHd)%2Cdocument.body.removeChild(x)%2Cw.zoomed.classList.remove('medium-zoom-image--opened')%2Cw.template%26%26document.body.removeChild(w.template)%2Ct%3D!1%2Cw.zoomed.removeEventListener('transitionend'%2Cb)%2Cw.original.dispatchEvent(createCustomEvent('medium-zoom%3Aclosed'%2C%7Bdetail%3A%7Bzoom%3Ay%7D%7D))%2Cw.original%3Dnull%2Cw.zoomed%3Dnull%2Cw.zoomedHd%3Dnull%2Cw.template%3Dnull%2Ca(y)%7D)%7D)%7D%2Co%3Dfunction()%7Bvar%20a%3D0%3Carguments.length%26%26arguments%5B0%5D!%3D%3Dvoid%200%3Farguments%5B0%5D%3A%7B%7D%2Cb%3Da.target%3Breturn%20w.original%3Fn()%3Am(%7Btarget%3Ab%7D)%7D%2Cp%3Dfunction()%7Breturn%20v%7D%2Cq%3Dfunction()%7Breturn%20r%7D%2Cr%3D%5B%5D%2Cs%3D%5B%5D%2Ct%3D!1%2Cu%3D0%2Cv%3Dc%2Cw%3D%7Boriginal%3Anull%2Czoomed%3Anull%2CzoomedHd%3Anull%2Ctemplate%3Anull%7D%3B'%5Bobject%20Object%5D'%3D%3D%3DObject.prototype.toString.call(b)%3Fv%3Db%3A(b%7C%7C'string'%3D%3Dtypeof%20b)%26%26i(b)%2Cv%3D_extends(%7Bmargin%3A0%2Cbackground%3A'%23fff'%2CscrollOffset%3A40%2Ccontainer%3Anull%2Ctemplate%3Anull%7D%2Cv)%3Bvar%20x%3DcreateOverlay(v.background)%3Bdocument.addEventListener('click'%2Ce)%2Cdocument.addEventListener('keyup'%2Cfunction(a)%7B27%3D%3D%3D(a.keyCode%7C%7Ca.which)%26%26n()%7D)%2Cdocument.addEventListener('scroll'%2Cf)%2Cwindow.addEventListener('resize'%2Cn)%3Bvar%20y%3D%7Bopen%3Am%2Cclose%3An%2Ctoggle%3Ao%2Cupdate%3Ag%2Cclone%3Ah%2Cattach%3Ai%2Cdetach%3Aj%2Con%3Ak%2Coff%3Al%2CgetOptions%3Ap%2CgetImages%3Aq%2CgetZoomedImage%3Afunction()%7Breturn%20w.original%7D%7D%3Breturn%20y%7D%3Bfunction%20styleInject(a%2Cb)%7Bvoid%200%3D%3D%3Db%26%26(b%3D%7B%7D)%3Bvar%20c%3Db.insertAt%3Bif(a%26%26'undefined'!%3Dtypeof%20document)%7Bvar%20d%3Ddocument.head%7C%7Cdocument.getElementsByTagName('head')%5B0%5D%2Ce%3Ddocument.createElement('style')%3Be.type%3D'text%2Fcss'%2C'top'%3D%3D%3Dc%3Fd.firstChild%3Fd.insertBefore(e%2Cd.firstChild)%3Ad.appendChild(e)%3Ad.appendChild(e)%2Ce.styleSheet%3Fe.styleSheet.cssText%3Da%3Ae.appendChild(document.createTextNode(a))%7D%7Dvar%20css%3D'.medium-zoom-overlay%7Bposition%3Afixed%3Btop%3A0%3Bright%3A0%3Bbottom%3A0%3Bleft%3A0%3Bopacity%3A0%3Btransition%3Aopacity%20.3s%3Bwill-change%3Aopacity%7D.medium-zoom--opened%20.medium-zoom-overlay%7Bcursor%3Apointer%3Bcursor%3Azoom-out%3Bopacity%3A1%7D.medium-zoom-image%7Bcursor%3Apointer%3Bcursor%3Azoom-in%3Btransition%3Atransform%20.3s%20cubic-bezier(.2%2C0%2C.2%2C1)%7D.medium-zoom-image--hidden%7Bvisibility%3Ahidden%7D.medium-zoom-image--opened%7Bposition%3Arelative%3Bcursor%3Apointer%3Bcursor%3Azoom-out%3Bwill-change%3Atransform%7D'%3BstyleInject('.medium-zoom-overlay%7Bposition%3Afixed%3Btop%3A0%3Bright%3A0%3Bbottom%3A0%3Bleft%3A0%3Bopacity%3A0%3Btransition%3Aopacity%20.3s%3Bwill-change%3Aopacity%7D.medium-zoom--opened%20.medium-zoom-overlay%7Bcursor%3Apointer%3Bcursor%3Azoom-out%3Bopacity%3A1%7D.medium-zoom-image%7Bcursor%3Apointer%3Bcursor%3Azoom-in%3Btransition%3Atransform%20.3s%20cubic-bezier(.2%2C0%2C.2%2C1)%7D.medium-zoom-image--hidden%7Bvisibility%3Ahidden%7D.medium-zoom-image--opened%7Bposition%3Arelative%3Bcursor%3Apointer%3Bcursor%3Azoom-out%3Bwill-change%3Atransform%7D')%3Bexport%20default%20mediumZoom%3B%0A&method=parse&range=false&loc=undefined&next=false&module=true&raw=false&jsx=undefined&directives=undefined&attachComment=undefined&webCompat=false)

**Comment by nchanged** [comment]
[platform-browser-dynamic.js.zip](https://github.com/cherow/cherow/files/3177074/platform-browser-dynamic.js.zip)
wrong file sorry

**Comment by KFlash** [comment]
I noticed :) This is a issue related to https://github.com/cherow/cherow/issues/324

cc/ @fkleuver ??

**Comment by KFlash** [comment]
cc/ @fkleuver ??

**Comment by aladdin-add** [comment]
Thanks for this issue. This repository and project will no longer be maintained, please consider its successor: https://github.com/meriyah/meriyah 

Thanks for understanding and we apologize for any inconvenience!
