### ISSUE TITLE
doesn't calculate lines correctly at comment start of a func decl

### ISSUE THREAD

**Issue by KFlash** [cherow/cherow#343]
Try to parse this: `/**/ function a() {}`. 

The correct start and end value of the func decl should be 5 & 20. Currently this is reported at 0 & 20. I discovered it when I was implementing loc tracking on Meriyah.

cc @fkleuver Do you look into this?

**Comment by KFlash** [comment]
cc @fkleuver Do you look into this?

**Comment by aladdin-add** [comment]
Thanks for this issue. This repository and project will no longer be maintained, please consider its successor: https://github.com/meriyah/meriyah 

Thanks for understanding and we apologize for any inconvenience!
