### ISSUE TITLE
Incorect start value on call expr in class

### ISSUE THREAD

**Issue by KFlash** [cherow/cherow#344]
Code to reproduce: `class x extends feh(await) { }`

The `callexpression` start value is 0, but should be 16.

cc / @fkleuver Do you handle this?

**Comment by aladdin-add** [comment]
Thanks for this issue. This repository and project will no longer be maintained, please consider its successor: https://github.com/meriyah/meriyah 

Thanks for understanding and we apologize for any inconvenience!
