### ISSUE TITLE
Emit errors in standard format for compilers

### ISSUE THREAD

**Issue by lawrence-dol** [cherow/cherow#345]
I was wondering if it would be possible to change the error output to a more standard compiler format that would make the line and column easier to extract.

Current: `<file>:~: <error message> (<col>:<lin>)`

Preferred: `<file>:<line>:<column> <error-text>`

**Comment by KFlash** [comment]
@lawrence-dol Do you mean something like this `SyntaxError: [1:35]: Await is only valid in async functions`?
I did an experiment with [my retirement project](https://github.com/meriyah/meriyah) and it seems to be easy to port it.

**Comment by lawrence-dol** [comment]
@KFlash 

No, I mean the same as `javac` and almost every other compiler I've encountered (every C compiler uses the same format, too). For example, where the column is reported:

    c:\some\path\Version.java:12:37: Expected `;`

and where only the line number is reported:

    c:\some\path\Version.java:12: Expected `;`

**Comment by KFlash** [comment]
In the retirement project it's like that now except I wrapped it in brackets. It's similar to the error messages reported by the ShiftJS parser in ASTExplorer.

**Comment by aladdin-add** [comment]
Thanks for this issue. This repository and project will no longer be maintained, please consider its successor: https://github.com/meriyah/meriyah 

Thanks for understanding and we apologize for any inconvenience!
