### ISSUE TITLE
Wrong error message for duplicate ident in arrow head

### ISSUE THREAD

**Issue by KFlash** [cherow/cherow#347]
`(a, a)  => c` throws `Identifier 'function argument' has already been declared (1:12)`

@fkleuver I guess this is something you will fix when you separate the scope logic as talked about before?

**Comment by aladdin-add** [comment]
Thanks for this issue. This repository and project will no longer be maintained, please consider its successor: https://github.com/meriyah/meriyah 

Thanks for understanding and we apologize for any inconvenience!
