### ISSUE TITLE
bigint and import() arrived stage-4

### ISSUE THREAD

**Issue by aladdin-add** [cherow/cherow#348]

**Comment by KFlash** [comment]
@aladdin-add It's only to remove the first part of [this line](https://github.com/cherow/cherow/blob/master/src/parser/expression.ts#L1206) and update the readme. 

Same for BigInt .

As you can see of other issue ticket - @fkleuver should fix several things and publish a 2.0 version, but it seems to be delayed....

**Comment by aladdin-add** [comment]
Thanks for this issue. This repository and project will no longer be maintained, please consider its successor: https://github.com/meriyah/meriyah 

Thanks for understanding and we apologize for any inconvenience!
