### ISSUE TITLE
Cherow performance regression

### ISSUE THREAD

**Issue by KFlash** [cherow/cherow#349]
Cherow was until recently the fastest parser, but it seems too be way slower than the [Meriyah parser](https://github.com/meriyah/meriyah).

@aladdin-add Could you update the benchmark with the Meriyah parser?

@fkleuver You said a few months back you should improve Cherow's performance so I guess you fix this?

![mperf](https://user-images.githubusercontent.com/31855118/59725358-f0bd5880-925f-11e9-8d9a-b1fe1292341f.png)

**Comment by aladdin-add** [comment]
Thanks for this issue. This repository and project will no longer be maintained, please consider its successor: https://github.com/meriyah/meriyah 

Thanks for understanding and we apologize for any inconvenience!
