### ISSUE TITLE
Implement Flow

### ISSUE THREAD

**Issue by KFlash** [cherow/cherow#35]
Implement Flow soon as current refactoring have been completed. TypeScript is out of the scope. Maybe within 4 days this will be started.

**Comment by KFlash** [comment]
Closing. See #38. Flow will come very soon now.

**Comment by KFlash** [comment]
This will be released in v.1.0 of Cherow.  

Placeholdes located [here](https://github.com/cherow/cherow/tree/1.0/plugins)

**Comment by KFlash** [comment]
**Status quo* Flow plugin almost completed and works with v. 1.0 of Cherow

**Comment by KFlash** [comment]
Closing. Flow plugin have been added to the v. 1.0 branch with a few tests. The plugin will be improved and more tests added in near future.

**Comment by KFlash** [comment]
Reopen to keep track of the progress. So far basic implementation works.

**Comment by rattrayalex** [comment]
In https://github.com/cherow/cherow/issues/6#issuecomment-356518744 you asked: 

> Does it exist any ESTree look-a-like specs for the AST nodes?

Unfortunately, the best I know of is the Flow test suites in [babylon](https://github.com/babel/babel/tree/master/packages/babylon/test/fixtures/flow) and maybe flow's parser (I haven't found them though). 

In https://github.com/cherow/cherow/issues/5#issuecomment-335683240, @DanielRosenwasser (a leader on the TypeScript team) claimed that babylon's TypeScript support would be a good reference as well.

**Comment by KFlash** [comment]
One of my issues now is the AST. And my implementation will not be 100% the same as Babylon. This because I set the node properies to null if they don't exist. babylon doesn't attach them on the AST node. My solution on this gives improved performance.

Therefore I wonder about the AST.

For TS there exist two different AST so I need to sort that out too. Eslint has its own.  Same with Babel.

Anyway. Within a few dsys i will probably push an alpha version  to GH.

**Comment by KFlash** [comment]
**The challenges I'm facing now:**

1. Performance. Current implementations I have seen have horrible performance. Around 300 opts/sec in 
    microbenchmarks. Cherow needs to be around 2 - 3 million opts /sec.

2. Complexity

3. Cherow core need to be developed as modules, so each part can be overwritten without use of `call` or `apply`

**Comment by KFlash** [comment]
@rattrayalex Anything thing to say about this benchmarks results? 

```js
var a: number[]
Cherow (Flow) x 7,080 ops/sec ±4.90% (73 runs sampled)
Fastest is Cherow (Flow)


var a: ?number[]
Cherow (Flow) x 7,125 ops/sec ±5.04% (76 runs sampled)
Fastest is Cherow (Flow)


declare function foo<T>(): void;
Cherow (Flow) x 6,604 ops/sec ±4.44% (76 runs sampled)
Fastest is Cherow (Flow)


var a: () => number[]
Cherow (Flow) x 6,799 ops/sec ±4.89% (73 runs sampled)
Fastest is Cherow (Flow)


declare function foo(x: number, y: string): void;
Cherow (Flow) x 6,163 ops/sec ±4.28% (74 runs sampled)
Fastest is Cherow (Flow)
```

**Comment by rattrayalex** [comment]
Interesting. I'm not surprised that parsing a more complex language is slower, but that's a few orders of magnitude worse. Eek!

Do you have a good feel for why it's slow? Lookaheads/speculative parsing?

**Comment by KFlash** [comment]
The way they are dealing with AST nodes, setting the properties etc is the main reason for the slow down. Plus active use of native solutions and use of `call` and `apply`. There is no magical cure for fixing it either unless you start developing from scratch. Anyway. To be fair. Performance have been my strongest side for years, but when it comes to this... Well.

I also noticed a few other oddities during my latest 24h research. The Flow AST for Babylon are missing properties etc comparing to Flow itself.

Anyway. I basic Flow plugin will soon be pushed.

**Comment by KFlash** [comment]
Performance for type annotation parsing will be around 10 - 12 mill opts/sec when I'm done. Estimated.

**Comment by KFlash** [comment]
@rattrayalex Here is a new microbenchmark. I improved the performance with 2 million opts/sec. However. I ran into *too many* issues with this, but they are now solved and I started to write tests to make sure this basic plugin works.

```js
var a: number[]
Cherow (Flow) x 8,260 ops/sec ±7.43% (66 runs sampled)
Fastest is Cherow (Flow)


var a: ?number[]
Cherow (Flow) x 8,272 ops/sec ±6.21% (66 runs sampled)
Fastest is Cherow (Flow)


declare function foo<T>(): void;
Cherow (Flow) x 7,855 ops/sec ±5.50% (69 runs sampled)
Fastest is Cherow (Flow)


var a: () => number[]
Cherow (Flow) x 8,129 ops/sec ±7.02% (68 runs sampled)
Fastest is Cherow (Flow)


declare function foo(x: number, y: string): void;
Cherow (Flow) x 7,490 ops/sec ±6.51% (68 runs sampled)
Fastest is Cherow (Flow)


declare class A extends C.B.D { }
Cherow (Flow) x 8,203 ops/sec ±5.95% (65 runs sampled)
Fastest is Cherow (Flow)


type X = {+p:T}
Cherow (Flow) x 8,385 ops/sec ±6.70% (71 runs sampled)
Fastest is Cherow (Flow)
```

**Comment by KFlash** [comment]
Benchmark results showing the results after heavy use of speculative parsing

```js
declare function foo(x: number, string): void;
Cherow (Flow) x 6,535 ops/sec ±8.29% (67 runs sampled)
Fastest is Cherow (Flow)


type A = (Array<string>) => void
Cherow (Flow) x 4,474 ops/sec ±5.09% (76 runs sampled)
Fastest is Cherow (Flow)
```

**Comment by KFlash** [comment]
@rattrayalex [Here](https://github.com/cherow/cherow/blob/1.0/plugins/flow/parser.ts) is my latest work on the plugin. Just now it pass 123 tests. Still need to fix class and async / paren integration.
After that I'm more or less done with this. Except that I  also have to deal with the Flow comments.

**Comment by KFlash** [comment]
Left to fix

- [ ] object expression

- [ ] async / await

- [ ]  arrows

- [ ] Flow comments

**Comment by KFlash** [comment]
@rattrayalex Any knowledge about Flow and decorators? I found it mentioned in the AST, but as far as I know decorators are at stage 2. Or is this decorators different?  No problem to implement this either, but need to clarify.
I'm doing OK progress with the flow plugin. Complex language, so this take a few more days.

**Comment by KFlash** [comment]
@rattrayalex I'm closing this now. The plugin have been completed. Only a few things to fix, but I need to finish the Cherow rewrite before finishing the Flow plugin. 
Anyway. The Flow plugin is located [here](https://github.com/cherow/cherow/blob/1.0/plugins/flow/parser.ts)

**Comment by KFlash** [comment]
Add to the record that Travis is green and run 240 Flow tests. https://travis-ci.org/cherow/cherow/builds/328669905

**Comment by KFlash** [comment]
@rattrayalex Any knowledge about this stuff? 

```js
// @flow 
let value = 42;

(value: string) // invalid.
   
```
Is this because of the Flow comment, and because it's already defined as a numeric value? So in this case all that's needed is to count the index and check for that comment in the scanner, then flag it if a flow comment, and save the value after assignment operator. And then do a validation based on that ?

But is this validations for the parser? Same also for other cases like

```
let v: number;

v = 'string'; // error ?
```

Anyway. I'm doing progress, but run into way too many issues. Babylon have loads of bugs or incorrect code so I now follow the Flow parser itself to get it correct.

**Comment by rattrayalex** [comment]
Great to hear of the progress!

Not sure what you mean by "Flow comments"? I think comments are just like normal per the parser...

Sorry, I'm not sure what you're asking about with the typecasts there... the first example you posted parses just fine: [try flow](https://flow.org/try/#0DYUwLgBAbghsCuIIF4IBYBMBuAUDgFLAiAFwQDOYATgJYB2A5gJRA), [flow parser at astexplorer](https://astexplorer.net/#/gist/985185f4425127408ffe319cb9fc0eda/5667d748fa19365966c6b263378ce408cf70e5ae) and [babylon](https://astexplorer.net/#/gist/985185f4425127408ffe319cb9fc0eda/4d4bc5c9bde94f875120d16e00308749759051d1). 

Typechecking doesn't occur in compilation with Flow, so I'm not sure what your question is...

**Comment by KFlash** [comment]
Regarding "Flow comments". I noticed some of this comment should allow to include e.g. if you use "flow-include" as comment.

Good to know that Typechecking is out of the scope for the parser, because I ran into way too many issues.
Regarding Babylon. I'm done with it. Finito. Finsihed.  I will open an info issue regarding why I say that.

**Comment by KFlash** [comment]
@rattrayalex See #71

**Comment by KFlash** [comment]
The performance loss is minimal when it comes to arrows with one or multiple annotations. 

```js
var foo = (bar: string): number => {};
Cherow (Flow) x 5,117 ops/sec ±8.42% (70 runs sampled)
Fastest is Cherow (Flow)


var foo = (a: string, b: number): number => {};
Cherow (Flow) x 5,019 ops/sec ±7.20% (71 runs sampled)
Fastest is Cherow (Flow)
```

**Comment by KFlash** [comment]
@rattrayalex Could you give it a try and let me know where I messed up? Note that templates, getter and setter for both class and object and  async / yield isn't implemented *yet* in 1.0.  
The plugin is found [here](https://github.com/cherow/cherow/blob/1.0/plugins/flow/parser.ts) and you can see how I did it with [this tests ](https://github.com/cherow/cherow/tree/1.0/test/flow)

**Comment by rattrayalex** [comment]
Sure, I'll give it a look this weekend!

**Comment by KFlash** [comment]
The plugins will be moved [here](https://github.com/cherow). So the Flow plugin will be located [here](https://github.com/cherow/cherow-flow-plugin) here soon

**Comment by KFlash** [comment]
@rattrayalex Everything related to Flow are moved to [this repo](https://github.com/cherow/cherow-flow-plugin) and I'm now going to finish that plugin. 1 - 2 days and it should be completed.

**Comment by rattrayalex** [comment]
Awesome! Exciting to see the stage one and stage two repo's, too. You sure have your work cut out for you!

**Comment by KFlash** [comment]
@rattrayalex See #76

**Comment by rattrayalex** [comment]
Awesome! Focusing on the core first sounds wise.

**Comment by KFlash** [comment]
If you got time for it, could you try out the JSX plugin and see if it works for you? Then I would know if there will be any issues later on with the Flow plugin and the plugin system.

**Comment by rattrayalex** [comment]
You bet, lemme see if I can run Cherow over the work codebase... I'll only be able to catch errors, though, don't think I'll have time to pick through the generated AST to check for correctness. 

Actually, speaking of that, maybe you could write a test that runs both cherow's parser and, say, esprima or acorn's parser and asserts equality? Could even use their existing test suites.
