### ISSUE TITLE
Cherow 2.0 progress....

### ISSUE THREAD

**Issue by KFlash** [cherow/cherow#350]
Current Master branch is Cherow 2.0, but will not be released in near future it seems. @fkleuver has assigned that task, and no progress for now.

While we all waiting for @fkleuver I would recommend to migrate to the [meriyah parser](https://github.com/meriyah/meriyah). 

It's a faster parser, and more stable than Cherow 2.x in current state.

**Comment by aladdin-add** [comment]
do you have access to publish? @KFlash

**Comment by KFlash** [comment]
@aladdin-add Nope. I lost access last year.

**Comment by KFlash** [comment]
There are tons of things to fix, and the scope stuff issue haven't been solved last 4 months. It's one of the blockers before a Cherow 2.0 release. @fkleuver mentioned extracting the scope logic.

There are also several known issues with loc tracking, perf regression etc. Things I discovered while finishing the Meriyah parser. And there exist also some other issues I haven't opened a issue for.

So I leave Cherow in the hands of @fkleuver now and pull myself away from Cherow and instead focusing on Meriyah wich have no issues at all.

**Comment by aladdin-add** [comment]
Thanks for this issue. This repository and project will no longer be maintained, please consider its successor: https://github.com/meriyah/meriyah 

Thanks for understanding and we apologize for any inconvenience!
