### ISSUE TITLE
Cherow can't parse the regexp /=/g

### ISSUE THREAD

**Issue by mureinik** [cherow/cherow#352]
Cherow doesn't seem to properly parse the regex `/=/g`, and instead produces an empty pattern for it.
I've tested this with Cherow 1.6.9 on Node 6.0.0 and Node 12.5.0. Did not test in-between versions, but I suspect the same bug would reproduce there too, and is Node-version-agnostic.

**Code**

```js
const cherow = require('cherow');

const tree = cherow.parse('/=/g');
const pattern = tree.body[0].expression.regex.pattern;
```

**Expected behavior:**
`pattern` should be `'='` (a string with the character `=`).

**Actual behavior:**
`pattern` is  `''` (an empty string).

**Comment by g-plane** [comment]
Which version are you using?

**Comment by mureinik** [comment]
@g-plane oops, that was stupid of me. Mea culpa.

I'm using the latest available version in npm, 1.6.9. Also edited in to the original report so that we have all the info in a single post and don't need to read through the comments and fish it out.

**Comment by KFlash** [comment]
@mureinik @g-plane There are known bugs in v. 1.6.9. It should have been solved in the version on the Master branch, but it's only released as a nightly build.

I may suggest you swap Cherow with Meriyah. Try it in the [REPL here](https://meriyah.github.io/meriyah/)

**Comment by aladdin-add** [comment]
Thanks for this issue. This repository and project will no longer be maintained, please consider its successor: https://github.com/meriyah/meriyah 

Thanks for understanding and we apologize for any inconvenience!
