### ISSUE TITLE
Parsing TypeScript

### ISSUE THREAD

**Issue by KFlash** [cherow/cherow#353]
Everyone! Cherow will never be extended in any way to accept TypeScript syntax.

However. I'm working on a TypeScript parser that will output ESTree AST located [here](https://github.com/buntis/buntis).

I can't promise the same performance as in Cherow because there have been raised questions about possibility for plug-ins in Cherow.  

The [Buntis TS parser](https://github.com/buntis/buntis) will also support plug-ins.

In case you need a more stable and more performant parser than Cherow, I would recommend [Meriyah](https://github.com/meriyah/meriyah) wich are **only** build for high performance and less memory usage without any backtracking or lookahead.

**Comment by aladdin-add** [comment]
cherow will not be maintained, I think we should:

+ update the docs to recommend users switching to something like `Meriyah`.
+ archive the repo
+ deprecate the packages(npm)

**Comment by KFlash** [comment]
@aladdin-add I agree now after @fkleuver withdraw from this project.

Is your bullet list something you can take care of?

**Comment by aladdin-add** [comment]
I can take 1. and 2. but I don't have access to publish on npm, so better left to @fkleuver

**Comment by g-plane** [comment]
However, we should publish the last version of Cherow.

**Comment by aladdin-add** [comment]
@KFlash I'm going to archive the repo, please give me the admin access to repo, thanks!

**Comment by KFlash** [comment]
@aladdin-add done
