### ISSUE TITLE
Unable to parse blockStatement with key and value as literals

### ISSUE THREAD

**Issue by peeyush31** [cherow/cherow#354]
**Code**

```js
{ "test" : "hello"}

cherow.parseScript('some code');
```

**Expected behavior:**
Should give an AST. with BlockStatement{LabelledStatement{label:ExpresstionStatement, body:ExpressionStatement}}
 

**Actual behavior:**
It throws an error `Line 1, column 9: Unexpected token ':'`

**Comment by aladdin-add** [comment]
hi, cherow is going to be deprecated, and https://github.com/meriyah/meriyah is its successor. please consider to use that, thanks!

**Comment by aladdin-add** [comment]
Thanks for this issue. This repository and project will no longer be maintained, please consider its successor: https://github.com/meriyah/meriyah

Thanks for understanding and we apologize for any inconvenience!
