### ISSUE TITLE
Announcement

### ISSUE THREAD

**Issue by KFlash** [cherow/cherow#38]
Cherow have been rewritten. Huge improvements over the current one. It's in the [`next branch`](https://github.com/cherow/cherow/tree/next).
I will not merge to Master *yet*, but I recommend to use the new version.

**Comment by rattrayalex** [comment]
I'm curious to hear a sentence or two about the improvements. What was flawed with the original approach? May be informative to those interested in parsers.

**Comment by KFlash** [comment]
@rattrayalex There was no flaws with the original approach, but a rewrite was kind of required if I should implement the error location tracking without performance loss. Most of other parsers doesn't throw errors at correct location. So I just improved it.

The main changes are:

- uses less memory
- handheld friendly
- improved performance
- added new features such as `import.meta` and `throw expression`
- rewrote parts of the code where I did validations

Minor changes:

- rewrote scanner code to avoid possible feature bugs with new Stage 3  proposal implementations

**Comment by rattrayalex** [comment]
Makes sense! Thanks for sharing!

**Comment by KFlash** [comment]
@rattrayalex NP! And now if you run the live benchmark  you are using the new code. So you can see the new test results.

**Comment by KFlash** [comment]
Closing this. If anyone wonder why I'm closing, just take a look at latest Master commit ;)
