### ISSUE TITLE
Online demo?

### ISSUE THREAD

**Issue by rauschma** [cherow/cherow#4]
An online demo of the parser would be nice. This is Esprima’s: http://esprima.org/demo/parse.html

**Comment by KFlash** [comment]
@rauschma I couldn't get the Github pages to work, but will give it one more try. I'm using it in the browser locale so easy to set it up.

**Comment by KFlash** [comment]
I'm closing. A temporary demo can be found here: https://cherow.github.io/cherow/ It only do script code, and `next` are activated by default. Same with the `raw` property.

**Comment by KFlash** [comment]
Updated the demo to accept a few options. Including parsing module code.
