### ISSUE TITLE
Support for Flow and/or TypeScript

### ISSUE THREAD

**Issue by rattrayalex** [cherow/cherow#5]
Many people use these syntaxes. It might be useful to provide support for parsing them.

**Comment by KFlash** [comment]
@rattrayalex There was a plan to support TypeScript and the code exist too. However it was skipped due to the fact that the TS team haven't updated their documentation for years and only 50% of TS syntax are known to the public. How can I implement it when I don't know the remaining 50%?

The TS syntax are also changing all the time without any documentation. 

Regarding Flow. I haven't looked into it, but I guess it's the same issues?

**Comment by KFlash** [comment]
Closing for now. Will re-open if things change in the future.

**Comment by rattrayalex** [comment]
@KFlash I actually personally am much more interested in Flow, since TypeScript always "does its own thing" while Flow does not provide its own compiler so other tools (primarily Babel) are required to transpile it. 

This means that the Flow team can't really change the syntax without those changes being reflected in Babylon, which often requires publicly-viewable communication on github. So you may find it to be more stable.

You might have a look at https://github.com/babel/babylon/tree/master/test/fixtures/flow if you're interested. 

The test cases are fairly comprehensive, but I don't think there's a well-developed/publicly-available language spec, which I assume is something you are interested in.

In any case, I certainly understand if you do not want to burden your project with an implementation for an unspecified language. I've heard rumors of a real Flow language spec in the works, and will post a link here if I'm ever aware of its existence.

**Comment by KFlash** [comment]
TypeScript is out of the scope, but I can reconsider Flow. Do you have any statistic on how many uses Flow vs TS?  I added it as an *maybe* to my todo #3 so don't consider this discussion for closed  yet or my decisions for finale :)

**Comment by rattrayalex** [comment]
Awesome!

Here are likely lower (flow-bin) and upper (babel-plugin-syntax-flow) bounds: https://npm-stat.com/charts.html?package=babel-plugin-syntax-flow&package=flow-bin&from=2016-09-27&to=2017-09-27

`flow-bin` is often installed globally / with non-npm package managers (apt, brew), and `babel-plugin-syntax-flow` is included by default in `babel-preset-react`, not all users of which are using flow.

**Comment by bd82** [comment]
> but I don't think there's a well-developed/publicly-available language spec, which I assume is something you are interested in.

I believe you are correct @rattrayalex 
https://github.com/facebook/flow/issues/3429

**Comment by KFlash** [comment]
My main issue if I should implement this, I would need to know what to implement ;) Doesn't help me if I only know 50% /  60%. Anyway. Feel free to continue this discussion on the [Gitter channel](https://gitter.im/cherow/cherow)

**Comment by rattrayalex** [comment]
Yes, the babylon tests should be comprehensive but I understand your hesitation

**Comment by KFlash** [comment]
@rattrayalex Can you talk to me on Gitter? I can try to look into this

**Comment by KFlash** [comment]
@rattrayalex Seen [this](https://github.com/facebookarchive/esprima/blob/fb-harmony/esprima.js) Implementing Flow could be done following some of that code. However. Does it exist any industrial standard for the AST nodes? I notice that Babylon run one kind of type, that one I linked to another one and even on the ESTree repo there are no such AST info.

**Comment by KFlash** [comment]
@rattrayalex See #35

**Comment by DanielRosenwasser** [comment]
Just as a heads up, Babylon has TypeScript support if that helps at all if you need a second implementation. I'm pretty sure the node types are documented.
