### ISSUE TITLE
Incomplete HTML open comments are silently discarded

### ISSUE THREAD

**Issue by xiemaisi** [cherow/cherow#61]
Consider the following two parser invocations:

```js
cherow.parseScript('<!');
cherow.parseScript('<!-');
```

**Expected behaviour:**

I expect both invocations to fail with a parse error.

**Actual behaviour:**

Both succeed, returning an AST representing the empty program.

**Background:**

This behaviour is caused by a bug (indirectly) flagged by lgtm: https://lgtm.com/projects/g/cherow/cherow/alerts/?mode=tree&severity=warning&rule=7880096

The other alerts reported by lgtm may also be worth fixing. (Full disclosure: I work on lgtm's JavaScript analysis.)

**Comment by KFlash** [comment]
Thanks for this. Will take a look soon.

**Comment by KFlash** [comment]
@xiemaisi I couldn't find any Test262 tests for this? Do you know about any?  BTW. I clicked on your link, and looked at the 6 alerts. For line 869 where unicode line are flagged as never read is wrong. If I remove that line, the surrogate pairs will fail. The other warnings are fixed now.

I will try to fix the HTML comment issue soon as I'm done with something locale, or if you want to send a PR. It's ok too.

**Comment by xiemaisi** [comment]
> I couldn't find any Test262 tests for this? Do you know about any?

I'm not familiar enough with the test262 suite to tell whether there is a test. Maybe they just didn't think to add one?

> I clicked on your link, and looked at the 6 alerts.

Thanks, I'm always grateful for feedback!

> For line 869 where unicode line are flagged as never read is wrong. If I remove that line, the surrogate pairs will fail.

True, but the alert doesn't actually say that the entire line is useless; it's just that you don't need to assign the result of the call to `code`, since that variable isn't read before being overwritten. In other words, you can replace that line with `this.peekUnicodeChar()`, I think. (The rule help mentions this: "if the right-hand side has a side-effect, it is important to keep this to preserve overall behavior".)

> The other warnings are fixed now.

Great! If you want to make sure they don't accidentally get unfixed, you could take a look at our [CI integration](https://lgtm.com/docs/lgtm/using-lgtm-analysis-continuous-integration): once you turn it on, every GitHub pull request against your repo is analysed and information about new and fixed alerts is displayed as part of the PR status. Here is an example of what it looks like in practice: [Open-MBEE/MDK#132 (comment)](https://github.com/Open-MBEE/mdk/pull/132#issuecomment-331294008).

> I will try to fix the HTML comment issue soon as I'm done with something locale, or if you want to send a PR. It's ok too.

No rush, I'm happy to wait for your PR.

**Comment by KFlash** [comment]
Ok. I'm closing this now. The entire fix for this is up on NPM, not GH for now. It fails as expected. I also fixed the other alerts.

I will take a look at the CI soon as I find time. It's a great tool!
