### ISSUE TITLE
Include babylon in parser benchmarks

### ISSUE THREAD

**Issue by rattrayalex** [cherow/cherow#7]
According to [this](https://github.com/babel/babel/issues/3921#issuecomment-249225720) (rather old) thread it should be ~2x slower than Esprima.

**Comment by KFlash** [comment]
Babylon slower than Esprima? That's expected. Esprima have a few optimizations that make it faster than Acorn. Babylon started as a fork from Acirn wich is very slow.
Anyway. I can try add Babylon to the benchmarks soon as I get to a computer. In mobile now.

**Comment by KFlash** [comment]
Closing. Babylon added to the micro-benchmark.
