### ISSUE TITLE
Cant combine plugins

### ISSUE THREAD

**Issue by locomain** [cherow/cherow#77]
ast = cherow.parseScript(input,{
  next:true,
  raw:true,
  plugins:[
      jsx,
      do
  ]
});

input code 

class test{
  test(){ 
    let a = do {  console.log('test'); }
    return <stuff></stuff>
  }
}

Both plugins work individually but not together

**Comment by KFlash** [comment]
Hi. That sounds strange and should be an easy fix. However  i don't have an computer atm. Issue is [this line](https://github.com/cherow/cherow/blob/master/src/cherow.ts#L44) in case you want to investigate.
But will look into this soon.

**Comment by locomain** [comment]
if (options.plugins) {
            for (const plugin of options.plugins) {
                Parser = plugin(Parser);
            }
        }
    }

    const parser = new Parser(source, comments, sourceFile);


  fixes the issue:)

**Comment by KFlash** [comment]
Issue with that is that Parser is not an variable and can't be assigned to

**Comment by KFlash** [comment]
@locomain I still don't have access to a computer, but did a online fix. Does that help?

**Comment by KFlash** [comment]
@locomain I'm closing this one. See [this tests](https://github.com/cherow/cherow/blob/master/test/miscellaneous/plugins.ts). So I consider this as not an Cherow issue now. If any further issues it has to be plugin related.
