### ISSUE TITLE
Unexpectedly throws "Rest elements cannot have a default value"

### ISSUE THREAD

**Issue by loganfsmyth** [cherow/cherow#78]
**Code**

```js
function fn1() {
}

function fn2() {
  [...one, ...two];

  (p => p);
}
```

**Expected behavior:**

Should parse.

**Actual behavior:**

Throws

```
Rest elements cannot have a default value at :7:4
```

**Comment by KFlash** [comment]
@loganfsmyth I will fix this soon as I get to an computer.

**Comment by loganfsmyth** [comment]
No problem. No rush on my end, just playing around and noticed so I figured I'd file it.

**Comment by KFlash** [comment]
I'm using a strict 1-hour policy when I get a bug report. See readme. So every issue has to be solved within 1 hour from I see the report. Anyway. Closing this now. Issue solved.
