### ISSUE TITLE
Unexpectedly throws "Duplicate binding [object Object]"

### ISSUE THREAD

**Issue by loganfsmyth** [cherow/cherow#79]
**Code**

```js
"use strict";

((one, two) => {});
```

**Expected behavior:**

Should parse.

**Actual behavior:**

Throws

```
Duplicate binding [object Object] at :3:1
```

**Comment by KFlash** [comment]
@loganfsmyth Thanx for info. Will be fixed as soon as I get to my computer.

**Comment by KFlash** [comment]
Closing as the reported issue have been fixed.
