### ISSUE TITLE
Unexpected token '(' for arrow function with a function call in it

### ISSUE THREAD

**Issue by twiss** [cherow/cherow#8]
Parsing the following throws `Unexpected token '('`:

    var fn = () => test();

Similarly, parsing the following simply throws `Unexpected token`:

    (a => b.test())

**Comment by KFlash** [comment]
@twiss Hang on! A fix is coming in a few minutes. Running validations now but it's solved!

**Comment by KFlash** [comment]
@twiss Closing. Fix is up. You can try it in the online demo!

**Comment by twiss** [comment]
Yup, thanks a lot!
