### ISSUE TITLE
npm package doesn't contain tsd

### ISSUE THREAD

**Issue by zaaack** [cherow/cherow#80]
**Code**

Import in typescript files.
```ts
import cherow from 'cherow'
```

**Expected behavior:**

Can get type hints

**Actual behavior:**

Can not.

**Comment by KFlash** [comment]
@zaaack a usecase i never thought about actually. Sorry for that. ATM I'm stuck with a cimouter that can't boot, but will look into it soon. This will take more than 1 hour.

Or could you send a PR? It would speed things up

**Comment by zaaack** [comment]
It's not an emergency, I'm happy to send a PR but I just go out to take a launch, might take at least half an hour..

**Comment by KFlash** [comment]
No problem. I will wait for your PR.  For now i need to buy a new computer.

**Comment by KFlash** [comment]
Pushed your changes to NPM.
