### ISSUE TITLE
Common typescript code is not parsed: Unexpected keyword 'this'

### ISSUE THREAD

**Issue by calebboyd** [cherow/cherow#83]
executable code example (node 8.9.4):
```js
code = `
const tslib = require('tslib')
class Example {
  hello () { return Promise.resolve('hello') }
  sayHi() {
    return tslib.__awaiter(this, void 0, void 0, function* () {
        return yield this.hello()
    });
  }
}

!async function main () { console.log(await new Example().sayHi()) }()
`
cherow.parseScript(code);
```

**Expected behavior:**
It should parse `yield this...`

**Actual behavior:**
It produces and error `Unexpected keyword 'this' `

This is a common snippet in any compiled typescript that is is targeting es6

**Comment by KFlash** [comment]
@calebboyd Is this critical? It's an easy fix to it, but coz of different reasons I'm stuck on the next branch developing ATM. In case you need it fixed ASAP, you do:

1. Open token.ts and go down to line 144
2. Add `| IsExpressionStart,` after `Reserved`. Same as the line above.

You can track the next Cherow in the next branch. I will try to push an NPM version of this change later on.

**Comment by KFlash** [comment]
@calebboyd Try install from NPM now and let me know if it works for you

**Comment by calebboyd** [comment]
It looks you deployed an invalid version. the NPM package is broken.

**Comment by KFlash** [comment]
Re-published it now. And this should work. See [online demo here](https://cherow.github.io/cherow/?code=%0Aconst%20tslib%20%3D%20require(%27tslib%27)%0Aclass%20Example%20%7B%0A%20%20hello%20()%20%7B%20return%20Promise.resolve(%27hello%27)%20%7D%0A%20%20sayHi()%20%7B%0A%20%20%20%20return%20tslib.__awaiter(this%2C%20void%200%2C%20void%200%2C%20function*%20()%20%7B%0A%20%20%20%20%20%20%20%20return%20yield%20this.hello()%0A%20%20%20%20%7D)%3B%0A%20%20%7D%0A%7D%0A%0A!async%20function%20main%20()%20%7B%20console.log(await%20new%20Example().sayHi())%20%7D()&method=parse&range=false&loc=undefined&next=false&module=false&raw=false&jsx=undefined&directives=undefined&attachComment=undefined&early=false)

**Comment by calebboyd** [comment]
Works! Thanks, your response time is incredible. I am amazed.

**Comment by calebboyd** [comment]
There might still be some oddities here

see [here](https://cherow.github.io/cherow/?code=%0Aconst%20tslib%20%3D%20require('tslib')%0A%0Afunction%20tag()%7B%7D%0Aclass%20Example%20%7B%0A%20%20hello%20()%20%7B%20return%20Promise.resolve('hello')%20%7D%0A%20%20sayHi()%20%7B%0A%20%20%20%20return%20tslib.__awaiter(this%2C%20void%200%2C%20void%200%2C%20function*%20()%20%7B%0A%20%20%20%20%20%20yield%20bluebird.each(yield%20foo()%2C%20(foos)%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20return%20bar(foos)%0A%20%20%20%20%20%20%7D)%0A%20%20%20%20%7D)%0A%20%20%7D%0A%7D%0A%0A!async%20function%20main%20()%20%7B%20console.log(await%20new%20Example().sayHi())%20%7D()&method=parse&range=false&loc=undefined&next=false&module=false&raw=false&jsx=undefined&directives=undefined&attachComment=undefined&early=false)

**Comment by KFlash** [comment]
Download latest from NPM
