### ISSUE TITLE
Re-export all declarations in cherow.d.ts for better TypeScript support

### ISSUE THREAD

**Issue by fkleuver** [cherow/cherow#86]
First of all, absolutely love this parser! Great job :)

Currently it's very tricky to get definitions like ESTree imported in TypeScript. By default the node module points to `cherow.d.ts` which only exports `parse`, `parseModule` and `parseScript`. It would require manual path mappings in tsconfig and whatnot to get access to the other `.d.ts` files.

If you did `export * from './estree'` (as well as for the other definition files), this would make things so much easier for TypeScript users.

Is this an oversight or is this intentional for some particular reason? If so, what is currently the recommended way to get other definitions imported? If not, could the rest be re-exported in `cherow.d.ts` please?

Appreciate your time!

**Comment by KFlash** [comment]
Hi. This is just a thing that have slipped I guess. It was until recently several people working on it and it turned into a mess, so I'm re-develop the entire parser. 

Could you send a PR on this one, so I can implement it in the upcoming v. 1.4? If not I can try to get this fixed before I push 1.4.

You can find the upcoming version [here in next branch](https://github.com/cherow/cherow/tree/next)

**Comment by fkleuver** [comment]
Sure. There seems to be a name conflict though.

Both `estree.ts` and `flags.ts` have an export named `JSXElement` (the former is an interface, the latter is a const enum).

Would it be an idea perhaps to rename the enum to something like `JSXElementKind` to resolve the conflict? Could also just export it with that as an alias, but some might consider that to be messy.

**Comment by KFlash** [comment]
Go ahead and rename. And the name looks okay. I didn't look at that code now, but if it's a JSXFragment involved here I combine names like JSXElementOrFragment / JSXElementAndFragment. And / or depends on the end result of the parsing. Just a hint. If it's just a stand-alone kind is just fine.

**Comment by fkleuver** [comment]
Looking at the code that uses it, it seems like it's a state rather than a kind.

```ts
state & JSXElement.Fragment
let state = JSXElement.None
state |= JSXElement.Fragment
```
etc..

So `JSXElementState` then?

**Comment by KFlash** [comment]
yes, `JSXElementState`

**Comment by fkleuver** [comment]
Ok, PR is in. Let me know if there are any problems with it.
