### ISSUE TITLE
Decorator support

### ISSUE THREAD

**Issue by fkleuver** [cherow/cherow#87]
I found this mentioned in a related issue (#35) but did not see any final answer on whether that is (or will be) implemented.

Babylon supports this via a plugin option (but really it just sits in the normal parser): https://github.com/babel/babel/blob/master/packages/babylon/src/parser/statement.js @ `parseDecorator`

By the looks of it they just scan for an `@` token and then proceed to parse the decorator as a normal CallExpression. The decorators are then pushed onto whatever the current context is (afaik pretty much anything can have a decorator).

Is this something that could be supported in the next version perhaps?

**Comment by KFlash** [comment]
This is still on [stage 2](https://github.com/cherow/cherow/tree/next#builds) as seen here. But I thought about it before, and it will soon be implemented. 

You can see [here](https://github.com/cherow/cherow/tree/next#builds) that I have splitted Cherow into different builds, so this will land I guess in the `next` build.

First of all I need to get a stable version running now. Done within a few days.

**Comment by fkleuver** [comment]
Alright, I'll grab babylon for the time being and switch back to cherow when you're done. Good luck :-)

**Comment by KFlash** [comment]
@fkleuver can you survive with this feature hidden behind a flag? E.g `{decorators: true}` and that i later on move this to the `next` option soon as it reach stage 3? It's still a stage 2 proposal. 

If you can I'm going to implement this now so it will land in v. 1.4.

**Comment by fkleuver** [comment]
My original plan was to just add the `@` support via a plugin but then I figured it'd be better for long-term to ask you.

If it's hidden behind some option that's completely fine. As long as I can find the option :)

**Comment by KFlash** [comment]
An `experimental` option is what I planned. And regarding options. Several new have been added. See readme in the next branch. And still a few not implemented yet.
Hopefully within 24h I will push a "bleeding" version. After that I'm adding decorators stage 2 for classes.

**Comment by fkleuver** [comment]
That's crazy, how do you do that? You're generating them? :)

**Comment by KFlash** [comment]
@fkleuver I lost electricity so delayed here, but if you look at the tests in the next branch you will see I'm using an iteration loop and testing various combinations. The trick is to come up with what to test. 
Some of the tests has to be done manually so I can validate correct ESTree output etc

**Comment by KFlash** [comment]
Closing this now. I landed this, and the specs will change again soon, so will update this again when that happen.
