### ISSUE TITLE
Failing to parse jquery

### ISSUE THREAD

**Issue by calebboyd** [cherow/cherow#93]
**Code**
http://code.jquery.com/jquery-3.3.1.min.js
```js
cherow.parseScript(jquery_min);
```

**Expected behavior:**
Successful parse
**Actual behavior:**
`Line 2, column 1914: Invalid destructuring assignment target`

**Comment by KFlash** [comment]
@calebboyd Download latest from NPM and your issue should have been solved. I can't push latest changes to GH because there is an conflicting issue between my files and J.K's files. I'm closing this now.
